module Scripturable
SCRIPTURE_META = [ {"book_number"=>1,
    "abbrev"=>"GEN",
    "name"=>"Genesis",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>26},
      {"chapter_number"=>5, "verse_count"=>32},
      {"chapter_number"=>6, "verse_count"=>22},
      {"chapter_number"=>7, "verse_count"=>24},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>29},
      {"chapter_number"=>10, "verse_count"=>32},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>20},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>24},
      {"chapter_number"=>15, "verse_count"=>21},
      {"chapter_number"=>16, "verse_count"=>16},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>33},
      {"chapter_number"=>19, "verse_count"=>38},
      {"chapter_number"=>20, "verse_count"=>18},
      {"chapter_number"=>21, "verse_count"=>34},
      {"chapter_number"=>22, "verse_count"=>24},
      {"chapter_number"=>23, "verse_count"=>20},
      {"chapter_number"=>24, "verse_count"=>67},
      {"chapter_number"=>25, "verse_count"=>34},
      {"chapter_number"=>26, "verse_count"=>35},
      {"chapter_number"=>27, "verse_count"=>46},
      {"chapter_number"=>28, "verse_count"=>22},
      {"chapter_number"=>29, "verse_count"=>35},
      {"chapter_number"=>30, "verse_count"=>43},
      {"chapter_number"=>31, "verse_count"=>55},
      {"chapter_number"=>32, "verse_count"=>32},
      {"chapter_number"=>33, "verse_count"=>20},
      {"chapter_number"=>34, "verse_count"=>31},
      {"chapter_number"=>35, "verse_count"=>29},
      {"chapter_number"=>36, "verse_count"=>43},
      {"chapter_number"=>37, "verse_count"=>36},
      {"chapter_number"=>38, "verse_count"=>30},
      {"chapter_number"=>39, "verse_count"=>23},
      {"chapter_number"=>40, "verse_count"=>23},
      {"chapter_number"=>41, "verse_count"=>57},
      {"chapter_number"=>42, "verse_count"=>38},
      {"chapter_number"=>43, "verse_count"=>34},
      {"chapter_number"=>44, "verse_count"=>34},
      {"chapter_number"=>45, "verse_count"=>28},
      {"chapter_number"=>46, "verse_count"=>34},
      {"chapter_number"=>47, "verse_count"=>31},
      {"chapter_number"=>48, "verse_count"=>22},
      {"chapter_number"=>49, "verse_count"=>33},
      {"chapter_number"=>50, "verse_count"=>26}]},
  {"book_number"=>2,
    "abbrev"=>"EXO",
    "name"=>"Exodus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>23},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>32},
      {"chapter_number"=>9, "verse_count"=>35},
      {"chapter_number"=>10, "verse_count"=>29},
      {"chapter_number"=>11, "verse_count"=>10},
      {"chapter_number"=>12, "verse_count"=>51},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>27},
      {"chapter_number"=>16, "verse_count"=>36},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>27},
      {"chapter_number"=>19, "verse_count"=>25},
      {"chapter_number"=>20, "verse_count"=>26},
      {"chapter_number"=>21, "verse_count"=>36},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>33},
      {"chapter_number"=>24, "verse_count"=>18},
      {"chapter_number"=>25, "verse_count"=>40},
      {"chapter_number"=>26, "verse_count"=>37},
      {"chapter_number"=>27, "verse_count"=>21},
      {"chapter_number"=>28, "verse_count"=>43},
      {"chapter_number"=>29, "verse_count"=>46},
      {"chapter_number"=>30, "verse_count"=>38},
      {"chapter_number"=>31, "verse_count"=>18},
      {"chapter_number"=>32, "verse_count"=>35},
      {"chapter_number"=>33, "verse_count"=>23},
      {"chapter_number"=>34, "verse_count"=>35},
      {"chapter_number"=>35, "verse_count"=>35},
      {"chapter_number"=>36, "verse_count"=>38},
      {"chapter_number"=>37, "verse_count"=>29},
      {"chapter_number"=>38, "verse_count"=>31},
      {"chapter_number"=>39, "verse_count"=>43},
      {"chapter_number"=>40, "verse_count"=>38}]},
  {"book_number"=>3,
    "abbrev"=>"LEV",
    "name"=>"Leviticus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>35},
      {"chapter_number"=>5, "verse_count"=>19},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>38},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>24},
      {"chapter_number"=>10, "verse_count"=>20},
      {"chapter_number"=>11, "verse_count"=>47},
      {"chapter_number"=>12, "verse_count"=>8},
      {"chapter_number"=>13, "verse_count"=>59},
      {"chapter_number"=>14, "verse_count"=>57},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>34},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>30},
      {"chapter_number"=>19, "verse_count"=>37},
      {"chapter_number"=>20, "verse_count"=>27},
      {"chapter_number"=>21, "verse_count"=>24},
      {"chapter_number"=>22, "verse_count"=>33},
      {"chapter_number"=>23, "verse_count"=>44},
      {"chapter_number"=>24, "verse_count"=>23},
      {"chapter_number"=>25, "verse_count"=>55},
      {"chapter_number"=>26, "verse_count"=>46},
      {"chapter_number"=>27, "verse_count"=>34}]},
  {"book_number"=>4,
    "abbrev"=>"NUM",
    "name"=>"Numbers",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>54},
      {"chapter_number"=>2, "verse_count"=>34},
      {"chapter_number"=>3, "verse_count"=>51},
      {"chapter_number"=>4, "verse_count"=>49},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>27},
      {"chapter_number"=>7, "verse_count"=>89},
      {"chapter_number"=>8, "verse_count"=>26},
      {"chapter_number"=>9, "verse_count"=>23},
      {"chapter_number"=>10, "verse_count"=>36},
      {"chapter_number"=>11, "verse_count"=>35},
      {"chapter_number"=>12, "verse_count"=>16},
      {"chapter_number"=>13, "verse_count"=>33},
      {"chapter_number"=>14, "verse_count"=>45},
      {"chapter_number"=>15, "verse_count"=>41},
      {"chapter_number"=>16, "verse_count"=>50},
      {"chapter_number"=>17, "verse_count"=>13},
      {"chapter_number"=>18, "verse_count"=>32},
      {"chapter_number"=>19, "verse_count"=>22},
      {"chapter_number"=>20, "verse_count"=>29},
      {"chapter_number"=>21, "verse_count"=>35},
      {"chapter_number"=>22, "verse_count"=>41},
      {"chapter_number"=>23, "verse_count"=>30},
      {"chapter_number"=>24, "verse_count"=>25},
      {"chapter_number"=>25, "verse_count"=>18},
      {"chapter_number"=>26, "verse_count"=>65},
      {"chapter_number"=>27, "verse_count"=>23},
      {"chapter_number"=>28, "verse_count"=>31},
      {"chapter_number"=>29, "verse_count"=>40},
      {"chapter_number"=>30, "verse_count"=>16},
      {"chapter_number"=>31, "verse_count"=>54},
      {"chapter_number"=>32, "verse_count"=>42},
      {"chapter_number"=>33, "verse_count"=>56},
      {"chapter_number"=>34, "verse_count"=>29},
      {"chapter_number"=>35, "verse_count"=>34},
      {"chapter_number"=>36, "verse_count"=>13}]},
  {"book_number"=>5,
    "abbrev"=>"DEU",
    "name"=>"Deuteronomy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>46},
      {"chapter_number"=>2, "verse_count"=>37},
      {"chapter_number"=>3, "verse_count"=>29},
      {"chapter_number"=>4, "verse_count"=>49},
      {"chapter_number"=>5, "verse_count"=>33},
      {"chapter_number"=>6, "verse_count"=>25},
      {"chapter_number"=>7, "verse_count"=>26},
      {"chapter_number"=>8, "verse_count"=>20},
      {"chapter_number"=>9, "verse_count"=>29},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>32},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>29},
      {"chapter_number"=>15, "verse_count"=>23},
      {"chapter_number"=>16, "verse_count"=>22},
      {"chapter_number"=>17, "verse_count"=>20},
      {"chapter_number"=>18, "verse_count"=>22},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>20},
      {"chapter_number"=>21, "verse_count"=>23},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>25},
      {"chapter_number"=>24, "verse_count"=>22},
      {"chapter_number"=>25, "verse_count"=>19},
      {"chapter_number"=>26, "verse_count"=>19},
      {"chapter_number"=>27, "verse_count"=>26},
      {"chapter_number"=>28, "verse_count"=>68},
      {"chapter_number"=>29, "verse_count"=>29},
      {"chapter_number"=>30, "verse_count"=>20},
      {"chapter_number"=>31, "verse_count"=>30},
      {"chapter_number"=>32, "verse_count"=>52},
      {"chapter_number"=>33, "verse_count"=>29},
      {"chapter_number"=>34, "verse_count"=>12}]},
  {"book_number"=>6,
    "abbrev"=>"JOS",
    "name"=>"Joshua",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>24},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>27},
      {"chapter_number"=>7, "verse_count"=>26},
      {"chapter_number"=>8, "verse_count"=>35},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>43},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>24},
      {"chapter_number"=>13, "verse_count"=>33},
      {"chapter_number"=>14, "verse_count"=>15},
      {"chapter_number"=>15, "verse_count"=>63},
      {"chapter_number"=>16, "verse_count"=>10},
      {"chapter_number"=>17, "verse_count"=>18},
      {"chapter_number"=>18, "verse_count"=>28},
      {"chapter_number"=>19, "verse_count"=>51},
      {"chapter_number"=>20, "verse_count"=>9},
      {"chapter_number"=>21, "verse_count"=>45},
      {"chapter_number"=>22, "verse_count"=>34},
      {"chapter_number"=>23, "verse_count"=>16},
      {"chapter_number"=>24, "verse_count"=>33}]},
  {"book_number"=>7,
    "abbrev"=>"JDG",
    "name"=>"Judges",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>36},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>31},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>40},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>35},
      {"chapter_number"=>9, "verse_count"=>57},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>40},
      {"chapter_number"=>12, "verse_count"=>15},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>20},
      {"chapter_number"=>15, "verse_count"=>20},
      {"chapter_number"=>16, "verse_count"=>31},
      {"chapter_number"=>17, "verse_count"=>13},
      {"chapter_number"=>18, "verse_count"=>31},
      {"chapter_number"=>19, "verse_count"=>30},
      {"chapter_number"=>20, "verse_count"=>48},
      {"chapter_number"=>21, "verse_count"=>25}]},
  {"book_number"=>8,
    "abbrev"=>"RUT",
    "name"=>"Ruth",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>22}]},
  {"book_number"=>9,
    "abbrev"=>"1SA",
    "name"=>"1 Samuel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>28},
      {"chapter_number"=>2, "verse_count"=>36},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>12},
      {"chapter_number"=>6, "verse_count"=>21},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>27},
      {"chapter_number"=>11, "verse_count"=>15},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>23},
      {"chapter_number"=>14, "verse_count"=>52},
      {"chapter_number"=>15, "verse_count"=>35},
      {"chapter_number"=>16, "verse_count"=>23},
      {"chapter_number"=>17, "verse_count"=>58},
      {"chapter_number"=>18, "verse_count"=>30},
      {"chapter_number"=>19, "verse_count"=>24},
      {"chapter_number"=>20, "verse_count"=>42},
      {"chapter_number"=>21, "verse_count"=>15},
      {"chapter_number"=>22, "verse_count"=>23},
      {"chapter_number"=>23, "verse_count"=>29},
      {"chapter_number"=>24, "verse_count"=>22},
      {"chapter_number"=>25, "verse_count"=>44},
      {"chapter_number"=>26, "verse_count"=>25},
      {"chapter_number"=>27, "verse_count"=>12},
      {"chapter_number"=>28, "verse_count"=>25},
      {"chapter_number"=>29, "verse_count"=>11},
      {"chapter_number"=>30, "verse_count"=>31},
      {"chapter_number"=>31, "verse_count"=>13}]},
  {"book_number"=>10,
    "abbrev"=>"2SA",
    "name"=>"2 Samuel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>27},
      {"chapter_number"=>2, "verse_count"=>32},
      {"chapter_number"=>3, "verse_count"=>39},
      {"chapter_number"=>4, "verse_count"=>12},
      {"chapter_number"=>5, "verse_count"=>25},
      {"chapter_number"=>6, "verse_count"=>23},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>13},
      {"chapter_number"=>10, "verse_count"=>19},
      {"chapter_number"=>11, "verse_count"=>27},
      {"chapter_number"=>12, "verse_count"=>31},
      {"chapter_number"=>13, "verse_count"=>39},
      {"chapter_number"=>14, "verse_count"=>33},
      {"chapter_number"=>15, "verse_count"=>37},
      {"chapter_number"=>16, "verse_count"=>23},
      {"chapter_number"=>17, "verse_count"=>29},
      {"chapter_number"=>18, "verse_count"=>33},
      {"chapter_number"=>19, "verse_count"=>43},
      {"chapter_number"=>20, "verse_count"=>26},
      {"chapter_number"=>21, "verse_count"=>22},
      {"chapter_number"=>22, "verse_count"=>51},
      {"chapter_number"=>23, "verse_count"=>39},
      {"chapter_number"=>24, "verse_count"=>25}]},
  {"book_number"=>11,
    "abbrev"=>"1KG",
    "name"=>"1 Kings",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>53},
      {"chapter_number"=>2, "verse_count"=>46},
      {"chapter_number"=>3, "verse_count"=>28},
      {"chapter_number"=>4, "verse_count"=>34},
      {"chapter_number"=>5, "verse_count"=>18},
      {"chapter_number"=>6, "verse_count"=>38},
      {"chapter_number"=>7, "verse_count"=>51},
      {"chapter_number"=>8, "verse_count"=>66},
      {"chapter_number"=>9, "verse_count"=>28},
      {"chapter_number"=>10, "verse_count"=>29},
      {"chapter_number"=>11, "verse_count"=>43},
      {"chapter_number"=>12, "verse_count"=>33},
      {"chapter_number"=>13, "verse_count"=>34},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>34},
      {"chapter_number"=>16, "verse_count"=>34},
      {"chapter_number"=>17, "verse_count"=>24},
      {"chapter_number"=>18, "verse_count"=>46},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>43},
      {"chapter_number"=>21, "verse_count"=>29},
      {"chapter_number"=>22, "verse_count"=>53}]},
  {"book_number"=>12,
    "abbrev"=>"2KG",
    "name"=>"2 Kings",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>27},
      {"chapter_number"=>4, "verse_count"=>44},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>33},
      {"chapter_number"=>7, "verse_count"=>20},
      {"chapter_number"=>8, "verse_count"=>29},
      {"chapter_number"=>9, "verse_count"=>37},
      {"chapter_number"=>10, "verse_count"=>36},
      {"chapter_number"=>11, "verse_count"=>21},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>29},
      {"chapter_number"=>15, "verse_count"=>38},
      {"chapter_number"=>16, "verse_count"=>20},
      {"chapter_number"=>17, "verse_count"=>41},
      {"chapter_number"=>18, "verse_count"=>37},
      {"chapter_number"=>19, "verse_count"=>37},
      {"chapter_number"=>20, "verse_count"=>21},
      {"chapter_number"=>21, "verse_count"=>26},
      {"chapter_number"=>22, "verse_count"=>20},
      {"chapter_number"=>23, "verse_count"=>37},
      {"chapter_number"=>24, "verse_count"=>20},
      {"chapter_number"=>25, "verse_count"=>30}]},
  {"book_number"=>13,
    "abbrev"=>"1KR",
    "name"=>"1 Chronicles",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>54},
      {"chapter_number"=>2, "verse_count"=>55},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>43},
      {"chapter_number"=>5, "verse_count"=>26},
      {"chapter_number"=>6, "verse_count"=>81},
      {"chapter_number"=>7, "verse_count"=>40},
      {"chapter_number"=>8, "verse_count"=>40},
      {"chapter_number"=>9, "verse_count"=>44},
      {"chapter_number"=>10, "verse_count"=>14},
      {"chapter_number"=>11, "verse_count"=>47},
      {"chapter_number"=>12, "verse_count"=>40},
      {"chapter_number"=>13, "verse_count"=>14},
      {"chapter_number"=>14, "verse_count"=>17},
      {"chapter_number"=>15, "verse_count"=>29},
      {"chapter_number"=>16, "verse_count"=>43},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>17},
      {"chapter_number"=>19, "verse_count"=>19},
      {"chapter_number"=>20, "verse_count"=>8},
      {"chapter_number"=>21, "verse_count"=>30},
      {"chapter_number"=>22, "verse_count"=>19},
      {"chapter_number"=>23, "verse_count"=>32},
      {"chapter_number"=>24, "verse_count"=>31},
      {"chapter_number"=>25, "verse_count"=>31},
      {"chapter_number"=>26, "verse_count"=>32},
      {"chapter_number"=>27, "verse_count"=>34},
      {"chapter_number"=>28, "verse_count"=>21},
      {"chapter_number"=>29, "verse_count"=>30}]},
  {"book_number"=>14,
    "abbrev"=>"2KR",
    "name"=>"2 Chronicles",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>18},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>42},
      {"chapter_number"=>7, "verse_count"=>22},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>31},
      {"chapter_number"=>10, "verse_count"=>19},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>16},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>15},
      {"chapter_number"=>15, "verse_count"=>19},
      {"chapter_number"=>16, "verse_count"=>14},
      {"chapter_number"=>17, "verse_count"=>19},
      {"chapter_number"=>18, "verse_count"=>34},
      {"chapter_number"=>19, "verse_count"=>11},
      {"chapter_number"=>20, "verse_count"=>37},
      {"chapter_number"=>21, "verse_count"=>20},
      {"chapter_number"=>22, "verse_count"=>12},
      {"chapter_number"=>23, "verse_count"=>21},
      {"chapter_number"=>24, "verse_count"=>27},
      {"chapter_number"=>25, "verse_count"=>28},
      {"chapter_number"=>26, "verse_count"=>23},
      {"chapter_number"=>27, "verse_count"=>9},
      {"chapter_number"=>28, "verse_count"=>27},
      {"chapter_number"=>29, "verse_count"=>36},
      {"chapter_number"=>30, "verse_count"=>27},
      {"chapter_number"=>31, "verse_count"=>21},
      {"chapter_number"=>32, "verse_count"=>33},
      {"chapter_number"=>33, "verse_count"=>25},
      {"chapter_number"=>34, "verse_count"=>33},
      {"chapter_number"=>35, "verse_count"=>27},
      {"chapter_number"=>36, "verse_count"=>23}]},
  {"book_number"=>15,
    "abbrev"=>"EZR",
    "name"=>"Ezra",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>70},
      {"chapter_number"=>3, "verse_count"=>13},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>17},
      {"chapter_number"=>6, "verse_count"=>22},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>15},
      {"chapter_number"=>10, "verse_count"=>44}]},
  {"book_number"=>16,
    "abbrev"=>"NEH",
    "name"=>"Nehemiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>32},
      {"chapter_number"=>4, "verse_count"=>23},
      {"chapter_number"=>5, "verse_count"=>19},
      {"chapter_number"=>6, "verse_count"=>19},
      {"chapter_number"=>7, "verse_count"=>73},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>38},
      {"chapter_number"=>10, "verse_count"=>39},
      {"chapter_number"=>11, "verse_count"=>36},
      {"chapter_number"=>12, "verse_count"=>47},
      {"chapter_number"=>13, "verse_count"=>31}]},
  {"book_number"=>17,
    "abbrev"=>"EST",
    "name"=>"Esther",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>15},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>10},
      {"chapter_number"=>8, "verse_count"=>17},
      {"chapter_number"=>9, "verse_count"=>32},
      {"chapter_number"=>10, "verse_count"=>3}]},
  {"book_number"=>18,
    "abbrev"=>"JOB",
    "name"=>"Job",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>21},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>35},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>20},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>28},
      {"chapter_number"=>14, "verse_count"=>22},
      {"chapter_number"=>15, "verse_count"=>35},
      {"chapter_number"=>16, "verse_count"=>22},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>21},
      {"chapter_number"=>19, "verse_count"=>29},
      {"chapter_number"=>20, "verse_count"=>29},
      {"chapter_number"=>21, "verse_count"=>34},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>17},
      {"chapter_number"=>24, "verse_count"=>25},
      {"chapter_number"=>25, "verse_count"=>6},
      {"chapter_number"=>26, "verse_count"=>14},
      {"chapter_number"=>27, "verse_count"=>23},
      {"chapter_number"=>28, "verse_count"=>28},
      {"chapter_number"=>29, "verse_count"=>25},
      {"chapter_number"=>30, "verse_count"=>31},
      {"chapter_number"=>31, "verse_count"=>40},
      {"chapter_number"=>32, "verse_count"=>22},
      {"chapter_number"=>33, "verse_count"=>33},
      {"chapter_number"=>34, "verse_count"=>37},
      {"chapter_number"=>35, "verse_count"=>16},
      {"chapter_number"=>36, "verse_count"=>33},
      {"chapter_number"=>37, "verse_count"=>24},
      {"chapter_number"=>38, "verse_count"=>41},
      {"chapter_number"=>39, "verse_count"=>30},
      {"chapter_number"=>40, "verse_count"=>24},
      {"chapter_number"=>41, "verse_count"=>34},
      {"chapter_number"=>42, "verse_count"=>17}]},
  {"book_number"=>19,
    "abbrev"=>"PSA",
    "name"=>"Psalms",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>6},
      {"chapter_number"=>2, "verse_count"=>12},
      {"chapter_number"=>3, "verse_count"=>8},
      {"chapter_number"=>4, "verse_count"=>8},
      {"chapter_number"=>5, "verse_count"=>12},
      {"chapter_number"=>6, "verse_count"=>10},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>9},
      {"chapter_number"=>9, "verse_count"=>20},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>7},
      {"chapter_number"=>12, "verse_count"=>8},
      {"chapter_number"=>13, "verse_count"=>6},
      {"chapter_number"=>14, "verse_count"=>7},
      {"chapter_number"=>15, "verse_count"=>5},
      {"chapter_number"=>16, "verse_count"=>11},
      {"chapter_number"=>17, "verse_count"=>15},
      {"chapter_number"=>18, "verse_count"=>50},
      {"chapter_number"=>19, "verse_count"=>14},
      {"chapter_number"=>20, "verse_count"=>9},
      {"chapter_number"=>21, "verse_count"=>13},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>6},
      {"chapter_number"=>24, "verse_count"=>10},
      {"chapter_number"=>25, "verse_count"=>22},
      {"chapter_number"=>26, "verse_count"=>12},
      {"chapter_number"=>27, "verse_count"=>14},
      {"chapter_number"=>28, "verse_count"=>9},
      {"chapter_number"=>29, "verse_count"=>11},
      {"chapter_number"=>30, "verse_count"=>12},
      {"chapter_number"=>31, "verse_count"=>24},
      {"chapter_number"=>32, "verse_count"=>11},
      {"chapter_number"=>33, "verse_count"=>22},
      {"chapter_number"=>34, "verse_count"=>22},
      {"chapter_number"=>35, "verse_count"=>28},
      {"chapter_number"=>36, "verse_count"=>12},
      {"chapter_number"=>37, "verse_count"=>40},
      {"chapter_number"=>38, "verse_count"=>22},
      {"chapter_number"=>39, "verse_count"=>13},
      {"chapter_number"=>40, "verse_count"=>17},
      {"chapter_number"=>41, "verse_count"=>13},
      {"chapter_number"=>42, "verse_count"=>11},
      {"chapter_number"=>43, "verse_count"=>5},
      {"chapter_number"=>44, "verse_count"=>26},
      {"chapter_number"=>45, "verse_count"=>17},
      {"chapter_number"=>46, "verse_count"=>11},
      {"chapter_number"=>47, "verse_count"=>9},
      {"chapter_number"=>48, "verse_count"=>14},
      {"chapter_number"=>49, "verse_count"=>20},
      {"chapter_number"=>50, "verse_count"=>23},
      {"chapter_number"=>51, "verse_count"=>19},
      {"chapter_number"=>52, "verse_count"=>9},
      {"chapter_number"=>53, "verse_count"=>6},
      {"chapter_number"=>54, "verse_count"=>7},
      {"chapter_number"=>55, "verse_count"=>23},
      {"chapter_number"=>56, "verse_count"=>13},
      {"chapter_number"=>57, "verse_count"=>11},
      {"chapter_number"=>58, "verse_count"=>11},
      {"chapter_number"=>59, "verse_count"=>17},
      {"chapter_number"=>60, "verse_count"=>12},
      {"chapter_number"=>61, "verse_count"=>8},
      {"chapter_number"=>62, "verse_count"=>12},
      {"chapter_number"=>63, "verse_count"=>11},
      {"chapter_number"=>64, "verse_count"=>10},
      {"chapter_number"=>65, "verse_count"=>13},
      {"chapter_number"=>66, "verse_count"=>20},
      {"chapter_number"=>67, "verse_count"=>7},
      {"chapter_number"=>68, "verse_count"=>35},
      {"chapter_number"=>69, "verse_count"=>36},
      {"chapter_number"=>70, "verse_count"=>5},
      {"chapter_number"=>71, "verse_count"=>24},
      {"chapter_number"=>72, "verse_count"=>20},
      {"chapter_number"=>73, "verse_count"=>28},
      {"chapter_number"=>74, "verse_count"=>23},
      {"chapter_number"=>75, "verse_count"=>10},
      {"chapter_number"=>76, "verse_count"=>12},
      {"chapter_number"=>77, "verse_count"=>20},
      {"chapter_number"=>78, "verse_count"=>72},
      {"chapter_number"=>79, "verse_count"=>13},
      {"chapter_number"=>80, "verse_count"=>19},
      {"chapter_number"=>81, "verse_count"=>16},
      {"chapter_number"=>82, "verse_count"=>8},
      {"chapter_number"=>83, "verse_count"=>18},
      {"chapter_number"=>84, "verse_count"=>12},
      {"chapter_number"=>85, "verse_count"=>13},
      {"chapter_number"=>86, "verse_count"=>17},
      {"chapter_number"=>87, "verse_count"=>7},
      {"chapter_number"=>88, "verse_count"=>18},
      {"chapter_number"=>89, "verse_count"=>52},
      {"chapter_number"=>90, "verse_count"=>17},
      {"chapter_number"=>91, "verse_count"=>16},
      {"chapter_number"=>92, "verse_count"=>15},
      {"chapter_number"=>93, "verse_count"=>5},
      {"chapter_number"=>94, "verse_count"=>23},
      {"chapter_number"=>95, "verse_count"=>11},
      {"chapter_number"=>96, "verse_count"=>13},
      {"chapter_number"=>97, "verse_count"=>12},
      {"chapter_number"=>98, "verse_count"=>9},
      {"chapter_number"=>99, "verse_count"=>9},
      {"chapter_number"=>100, "verse_count"=>5},
      {"chapter_number"=>101, "verse_count"=>8},
      {"chapter_number"=>102, "verse_count"=>28},
      {"chapter_number"=>103, "verse_count"=>22},
      {"chapter_number"=>104, "verse_count"=>35},
      {"chapter_number"=>105, "verse_count"=>45},
      {"chapter_number"=>106, "verse_count"=>48},
      {"chapter_number"=>107, "verse_count"=>43},
      {"chapter_number"=>108, "verse_count"=>13},
      {"chapter_number"=>109, "verse_count"=>31},
      {"chapter_number"=>110, "verse_count"=>7},
      {"chapter_number"=>111, "verse_count"=>10},
      {"chapter_number"=>112, "verse_count"=>10},
      {"chapter_number"=>113, "verse_count"=>9},
      {"chapter_number"=>114, "verse_count"=>8},
      {"chapter_number"=>115, "verse_count"=>18},
      {"chapter_number"=>116, "verse_count"=>19},
      {"chapter_number"=>117, "verse_count"=>2},
      {"chapter_number"=>118, "verse_count"=>29},
      {"chapter_number"=>119, "verse_count"=>176},
      {"chapter_number"=>120, "verse_count"=>7},
      {"chapter_number"=>121, "verse_count"=>8},
      {"chapter_number"=>122, "verse_count"=>9},
      {"chapter_number"=>123, "verse_count"=>4},
      {"chapter_number"=>124, "verse_count"=>8},
      {"chapter_number"=>125, "verse_count"=>5},
      {"chapter_number"=>126, "verse_count"=>6},
      {"chapter_number"=>127, "verse_count"=>5},
      {"chapter_number"=>128, "verse_count"=>6},
      {"chapter_number"=>129, "verse_count"=>8},
      {"chapter_number"=>130, "verse_count"=>8},
      {"chapter_number"=>131, "verse_count"=>3},
      {"chapter_number"=>132, "verse_count"=>18},
      {"chapter_number"=>133, "verse_count"=>3},
      {"chapter_number"=>134, "verse_count"=>3},
      {"chapter_number"=>135, "verse_count"=>21},
      {"chapter_number"=>136, "verse_count"=>26},
      {"chapter_number"=>137, "verse_count"=>9},
      {"chapter_number"=>138, "verse_count"=>8},
      {"chapter_number"=>139, "verse_count"=>24},
      {"chapter_number"=>140, "verse_count"=>13},
      {"chapter_number"=>141, "verse_count"=>10},
      {"chapter_number"=>142, "verse_count"=>7},
      {"chapter_number"=>143, "verse_count"=>12},
      {"chapter_number"=>144, "verse_count"=>15},
      {"chapter_number"=>145, "verse_count"=>21},
      {"chapter_number"=>146, "verse_count"=>10},
      {"chapter_number"=>147, "verse_count"=>20},
      {"chapter_number"=>148, "verse_count"=>14},
      {"chapter_number"=>149, "verse_count"=>9},
      {"chapter_number"=>150, "verse_count"=>6}]},
  {"book_number"=>20,
    "abbrev"=>"PRO",
    "name"=>"Proverbs",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>33},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>35},
      {"chapter_number"=>4, "verse_count"=>27},
      {"chapter_number"=>5, "verse_count"=>23},
      {"chapter_number"=>6, "verse_count"=>35},
      {"chapter_number"=>7, "verse_count"=>27},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>18},
      {"chapter_number"=>10, "verse_count"=>32},
      {"chapter_number"=>11, "verse_count"=>31},
      {"chapter_number"=>12, "verse_count"=>28},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>35},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>33},
      {"chapter_number"=>17, "verse_count"=>28},
      {"chapter_number"=>18, "verse_count"=>24},
      {"chapter_number"=>19, "verse_count"=>29},
      {"chapter_number"=>20, "verse_count"=>30},
      {"chapter_number"=>21, "verse_count"=>31},
      {"chapter_number"=>22, "verse_count"=>29},
      {"chapter_number"=>23, "verse_count"=>35},
      {"chapter_number"=>24, "verse_count"=>34},
      {"chapter_number"=>25, "verse_count"=>28},
      {"chapter_number"=>26, "verse_count"=>28},
      {"chapter_number"=>27, "verse_count"=>27},
      {"chapter_number"=>28, "verse_count"=>28},
      {"chapter_number"=>29, "verse_count"=>27},
      {"chapter_number"=>30, "verse_count"=>33},
      {"chapter_number"=>31, "verse_count"=>31}]},
  {"book_number"=>21,
    "abbrev"=>"ECC",
    "name"=>"Ecclesiastes",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>20},
      {"chapter_number"=>6, "verse_count"=>12},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>17},
      {"chapter_number"=>9, "verse_count"=>18},
      {"chapter_number"=>10, "verse_count"=>20},
      {"chapter_number"=>11, "verse_count"=>10},
      {"chapter_number"=>12, "verse_count"=>14}]},
  {"book_number"=>22,
    "abbrev"=>"SO",
    "name"=>"Song",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>11},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>16},
      {"chapter_number"=>6, "verse_count"=>13},
      {"chapter_number"=>7, "verse_count"=>13},
      {"chapter_number"=>8, "verse_count"=>14}]},
  {"book_number"=>23,
    "abbrev"=>"ISA",
    "name"=>"Isaiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>6},
      {"chapter_number"=>5, "verse_count"=>30},
      {"chapter_number"=>6, "verse_count"=>13},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>21},
      {"chapter_number"=>10, "verse_count"=>34},
      {"chapter_number"=>11, "verse_count"=>16},
      {"chapter_number"=>12, "verse_count"=>6},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>32},
      {"chapter_number"=>15, "verse_count"=>9},
      {"chapter_number"=>16, "verse_count"=>14},
      {"chapter_number"=>17, "verse_count"=>14},
      {"chapter_number"=>18, "verse_count"=>7},
      {"chapter_number"=>19, "verse_count"=>25},
      {"chapter_number"=>20, "verse_count"=>6},
      {"chapter_number"=>21, "verse_count"=>17},
      {"chapter_number"=>22, "verse_count"=>25},
      {"chapter_number"=>23, "verse_count"=>18},
      {"chapter_number"=>24, "verse_count"=>23},
      {"chapter_number"=>25, "verse_count"=>12},
      {"chapter_number"=>26, "verse_count"=>21},
      {"chapter_number"=>27, "verse_count"=>13},
      {"chapter_number"=>28, "verse_count"=>29},
      {"chapter_number"=>29, "verse_count"=>24},
      {"chapter_number"=>30, "verse_count"=>33},
      {"chapter_number"=>31, "verse_count"=>9},
      {"chapter_number"=>32, "verse_count"=>20},
      {"chapter_number"=>33, "verse_count"=>24},
      {"chapter_number"=>34, "verse_count"=>17},
      {"chapter_number"=>35, "verse_count"=>10},
      {"chapter_number"=>36, "verse_count"=>22},
      {"chapter_number"=>37, "verse_count"=>38},
      {"chapter_number"=>38, "verse_count"=>22},
      {"chapter_number"=>39, "verse_count"=>8},
      {"chapter_number"=>40, "verse_count"=>31},
      {"chapter_number"=>41, "verse_count"=>29},
      {"chapter_number"=>42, "verse_count"=>25},
      {"chapter_number"=>43, "verse_count"=>28},
      {"chapter_number"=>44, "verse_count"=>28},
      {"chapter_number"=>45, "verse_count"=>25},
      {"chapter_number"=>46, "verse_count"=>13},
      {"chapter_number"=>47, "verse_count"=>15},
      {"chapter_number"=>48, "verse_count"=>22},
      {"chapter_number"=>49, "verse_count"=>26},
      {"chapter_number"=>50, "verse_count"=>11},
      {"chapter_number"=>51, "verse_count"=>23},
      {"chapter_number"=>52, "verse_count"=>15},
      {"chapter_number"=>53, "verse_count"=>12},
      {"chapter_number"=>54, "verse_count"=>17},
      {"chapter_number"=>55, "verse_count"=>13},
      {"chapter_number"=>56, "verse_count"=>12},
      {"chapter_number"=>57, "verse_count"=>21},
      {"chapter_number"=>58, "verse_count"=>14},
      {"chapter_number"=>59, "verse_count"=>21},
      {"chapter_number"=>60, "verse_count"=>22},
      {"chapter_number"=>61, "verse_count"=>11},
      {"chapter_number"=>62, "verse_count"=>12},
      {"chapter_number"=>63, "verse_count"=>19},
      {"chapter_number"=>64, "verse_count"=>12},
      {"chapter_number"=>65, "verse_count"=>25},
      {"chapter_number"=>66, "verse_count"=>24}]},
  {"book_number"=>24,
    "abbrev"=>"JER",
    "name"=>"Jeremiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>19},
      {"chapter_number"=>2, "verse_count"=>37},
      {"chapter_number"=>3, "verse_count"=>25},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>34},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>26},
      {"chapter_number"=>10, "verse_count"=>25},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>17},
      {"chapter_number"=>13, "verse_count"=>27},
      {"chapter_number"=>14, "verse_count"=>22},
      {"chapter_number"=>15, "verse_count"=>21},
      {"chapter_number"=>16, "verse_count"=>21},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>23},
      {"chapter_number"=>19, "verse_count"=>15},
      {"chapter_number"=>20, "verse_count"=>18},
      {"chapter_number"=>21, "verse_count"=>14},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>40},
      {"chapter_number"=>24, "verse_count"=>10},
      {"chapter_number"=>25, "verse_count"=>38},
      {"chapter_number"=>26, "verse_count"=>24},
      {"chapter_number"=>27, "verse_count"=>22},
      {"chapter_number"=>28, "verse_count"=>17},
      {"chapter_number"=>29, "verse_count"=>32},
      {"chapter_number"=>30, "verse_count"=>24},
      {"chapter_number"=>31, "verse_count"=>40},
      {"chapter_number"=>32, "verse_count"=>44},
      {"chapter_number"=>33, "verse_count"=>26},
      {"chapter_number"=>34, "verse_count"=>22},
      {"chapter_number"=>35, "verse_count"=>19},
      {"chapter_number"=>36, "verse_count"=>32},
      {"chapter_number"=>37, "verse_count"=>21},
      {"chapter_number"=>38, "verse_count"=>28},
      {"chapter_number"=>39, "verse_count"=>18},
      {"chapter_number"=>40, "verse_count"=>16},
      {"chapter_number"=>41, "verse_count"=>18},
      {"chapter_number"=>42, "verse_count"=>22},
      {"chapter_number"=>43, "verse_count"=>13},
      {"chapter_number"=>44, "verse_count"=>30},
      {"chapter_number"=>45, "verse_count"=>5},
      {"chapter_number"=>46, "verse_count"=>28},
      {"chapter_number"=>47, "verse_count"=>7},
      {"chapter_number"=>48, "verse_count"=>47},
      {"chapter_number"=>49, "verse_count"=>39},
      {"chapter_number"=>50, "verse_count"=>46},
      {"chapter_number"=>51, "verse_count"=>64},
      {"chapter_number"=>52, "verse_count"=>34}]},
  {"book_number"=>25,
    "abbrev"=>"LAM",
    "name"=>"Lamentations",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>66},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>22}]},
  {"book_number"=>26,
    "abbrev"=>"EZE",
    "name"=>"Ezekiel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>28},
      {"chapter_number"=>2, "verse_count"=>10},
      {"chapter_number"=>3, "verse_count"=>27},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>17},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>27},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>11},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>25},
      {"chapter_number"=>12, "verse_count"=>28},
      {"chapter_number"=>13, "verse_count"=>23},
      {"chapter_number"=>14, "verse_count"=>23},
      {"chapter_number"=>15, "verse_count"=>8},
      {"chapter_number"=>16, "verse_count"=>63},
      {"chapter_number"=>17, "verse_count"=>24},
      {"chapter_number"=>18, "verse_count"=>32},
      {"chapter_number"=>19, "verse_count"=>14},
      {"chapter_number"=>20, "verse_count"=>49},
      {"chapter_number"=>21, "verse_count"=>32},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>49},
      {"chapter_number"=>24, "verse_count"=>27},
      {"chapter_number"=>25, "verse_count"=>17},
      {"chapter_number"=>26, "verse_count"=>21},
      {"chapter_number"=>27, "verse_count"=>36},
      {"chapter_number"=>28, "verse_count"=>26},
      {"chapter_number"=>29, "verse_count"=>21},
      {"chapter_number"=>30, "verse_count"=>26},
      {"chapter_number"=>31, "verse_count"=>18},
      {"chapter_number"=>32, "verse_count"=>32},
      {"chapter_number"=>33, "verse_count"=>33},
      {"chapter_number"=>34, "verse_count"=>31},
      {"chapter_number"=>35, "verse_count"=>15},
      {"chapter_number"=>36, "verse_count"=>38},
      {"chapter_number"=>37, "verse_count"=>28},
      {"chapter_number"=>38, "verse_count"=>23},
      {"chapter_number"=>39, "verse_count"=>29},
      {"chapter_number"=>40, "verse_count"=>49},
      {"chapter_number"=>41, "verse_count"=>26},
      {"chapter_number"=>42, "verse_count"=>20},
      {"chapter_number"=>43, "verse_count"=>27},
      {"chapter_number"=>44, "verse_count"=>31},
      {"chapter_number"=>45, "verse_count"=>25},
      {"chapter_number"=>46, "verse_count"=>24},
      {"chapter_number"=>47, "verse_count"=>23},
      {"chapter_number"=>48, "verse_count"=>35}]},
  {"book_number"=>27,
    "abbrev"=>"DAN",
    "name"=>"Daniel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>49},
      {"chapter_number"=>3, "verse_count"=>30},
      {"chapter_number"=>4, "verse_count"=>37},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>28},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>27},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>21},
      {"chapter_number"=>11, "verse_count"=>45},
      {"chapter_number"=>12, "verse_count"=>13}]},
  {"book_number"=>28,
    "abbrev"=>"HOS",
    "name"=>"Hosea",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>5},
      {"chapter_number"=>4, "verse_count"=>19},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>11},
      {"chapter_number"=>7, "verse_count"=>16},
      {"chapter_number"=>8, "verse_count"=>14},
      {"chapter_number"=>9, "verse_count"=>17},
      {"chapter_number"=>10, "verse_count"=>15},
      {"chapter_number"=>11, "verse_count"=>12},
      {"chapter_number"=>12, "verse_count"=>14},
      {"chapter_number"=>13, "verse_count"=>16},
      {"chapter_number"=>14, "verse_count"=>9}]},
  {"book_number"=>29,
    "abbrev"=>"JOE",
    "name"=>"Joel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>32},
      {"chapter_number"=>3, "verse_count"=>21}]},
  {"book_number"=>30,
    "abbrev"=>"AMO",
    "name"=>"Amos",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>15},
      {"chapter_number"=>4, "verse_count"=>13},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>14},
      {"chapter_number"=>9, "verse_count"=>15}]},
  {"book_number"=>31,
    "abbrev"=>"OBA",
    "name"=>"Obadiah",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>21}]},
  {"book_number"=>32,
    "abbrev"=>"JON",
    "name"=>"Jonah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>10},
      {"chapter_number"=>3, "verse_count"=>10},
      {"chapter_number"=>4, "verse_count"=>11}]},
  {"book_number"=>33,
    "abbrev"=>"MIC",
    "name"=>"Micah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>16},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>12},
      {"chapter_number"=>4, "verse_count"=>13},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>16},
      {"chapter_number"=>7, "verse_count"=>20}]},
  {"book_number"=>34,
    "abbrev"=>"NAH",
    "name"=>"Nahum",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>19}]},
  {"book_number"=>35,
    "abbrev"=>"HAB",
    "name"=>"Habakkuk",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>19}]},
  {"book_number"=>36,
    "abbrev"=>"ZEP",
    "name"=>"Zephaniah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>20}]},
  {"book_number"=>37,
    "abbrev"=>"HAG",
    "name"=>"Haggai",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15}, 
      {"chapter_number"=>2, "verse_count"=>23}]},
  {"book_number"=>38,
    "abbrev"=>"ZEC",
    "name"=>"Zechariah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>10},
      {"chapter_number"=>4, "verse_count"=>14},
      {"chapter_number"=>5, "verse_count"=>11},
      {"chapter_number"=>6, "verse_count"=>15},
      {"chapter_number"=>7, "verse_count"=>14},
      {"chapter_number"=>8, "verse_count"=>23},
      {"chapter_number"=>9, "verse_count"=>17},
      {"chapter_number"=>10, "verse_count"=>12},
      {"chapter_number"=>11, "verse_count"=>17},
      {"chapter_number"=>12, "verse_count"=>14},
      {"chapter_number"=>13, "verse_count"=>9},
      {"chapter_number"=>14, "verse_count"=>21}]},
  {"book_number"=>39,
    "abbrev"=>"MAL",
    "name"=>"Malachi",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>14},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>6}]},
  {"book_number"=>40,
    "abbrev"=>"MAT",
    "name"=>"Matthew",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>25},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>25},
      {"chapter_number"=>5, "verse_count"=>48},
      {"chapter_number"=>6, "verse_count"=>34},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>34},
      {"chapter_number"=>9, "verse_count"=>38},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>30},
      {"chapter_number"=>12, "verse_count"=>49},
      {"chapter_number"=>13, "verse_count"=>58},
      {"chapter_number"=>14, "verse_count"=>36},
      {"chapter_number"=>15, "verse_count"=>39},
      {"chapter_number"=>16, "verse_count"=>28},
      {"chapter_number"=>17, "verse_count"=>26},
      {"chapter_number"=>18, "verse_count"=>34},
      {"chapter_number"=>19, "verse_count"=>30},
      {"chapter_number"=>20, "verse_count"=>34},
      {"chapter_number"=>21, "verse_count"=>46},
      {"chapter_number"=>22, "verse_count"=>46},
      {"chapter_number"=>23, "verse_count"=>38},
      {"chapter_number"=>24, "verse_count"=>51},
      {"chapter_number"=>25, "verse_count"=>46},
      {"chapter_number"=>26, "verse_count"=>75},
      {"chapter_number"=>27, "verse_count"=>66},
      {"chapter_number"=>28, "verse_count"=>20}]},
  {"book_number"=>41,
    "abbrev"=>"MAR",
    "name"=>"Mark",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>45},
      {"chapter_number"=>2, "verse_count"=>28},
      {"chapter_number"=>3, "verse_count"=>35},
      {"chapter_number"=>4, "verse_count"=>41},
      {"chapter_number"=>5, "verse_count"=>43},
      {"chapter_number"=>6, "verse_count"=>56},
      {"chapter_number"=>7, "verse_count"=>36},
      {"chapter_number"=>8, "verse_count"=>38},
      {"chapter_number"=>9, "verse_count"=>48},
      {"chapter_number"=>10, "verse_count"=>52},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>44},
      {"chapter_number"=>13, "verse_count"=>37},
      {"chapter_number"=>14, "verse_count"=>72},
      {"chapter_number"=>15, "verse_count"=>46},
      {"chapter_number"=>16, "verse_count"=>20}]},
  {"book_number"=>42,
    "abbrev"=>"LUK",
    "name"=>"Luke",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>80},
      {"chapter_number"=>2, "verse_count"=>52},
      {"chapter_number"=>3, "verse_count"=>38},
      {"chapter_number"=>4, "verse_count"=>44},
      {"chapter_number"=>5, "verse_count"=>39},
      {"chapter_number"=>6, "verse_count"=>49},
      {"chapter_number"=>7, "verse_count"=>50},
      {"chapter_number"=>8, "verse_count"=>56},
      {"chapter_number"=>9, "verse_count"=>62},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>54},
      {"chapter_number"=>12, "verse_count"=>59},
      {"chapter_number"=>13, "verse_count"=>35},
      {"chapter_number"=>14, "verse_count"=>35},
      {"chapter_number"=>15, "verse_count"=>32},
      {"chapter_number"=>16, "verse_count"=>31},
      {"chapter_number"=>17, "verse_count"=>36},
      {"chapter_number"=>18, "verse_count"=>43},
      {"chapter_number"=>19, "verse_count"=>48},
      {"chapter_number"=>20, "verse_count"=>47},
      {"chapter_number"=>21, "verse_count"=>38},
      {"chapter_number"=>22, "verse_count"=>71},
      {"chapter_number"=>23, "verse_count"=>55},
      {"chapter_number"=>24, "verse_count"=>53}]},
  {"book_number"=>43,
    "abbrev"=>"JOH",
    "name"=>"John",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>51},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>36},
      {"chapter_number"=>4, "verse_count"=>54},
      {"chapter_number"=>5, "verse_count"=>46},
      {"chapter_number"=>6, "verse_count"=>71},
      {"chapter_number"=>7, "verse_count"=>53},
      {"chapter_number"=>8, "verse_count"=>59},
      {"chapter_number"=>9, "verse_count"=>41},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>57},
      {"chapter_number"=>12, "verse_count"=>50},
      {"chapter_number"=>13, "verse_count"=>38},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>27},
      {"chapter_number"=>16, "verse_count"=>33},
      {"chapter_number"=>17, "verse_count"=>26},
      {"chapter_number"=>18, "verse_count"=>40},
      {"chapter_number"=>19, "verse_count"=>42},
      {"chapter_number"=>20, "verse_count"=>31},
      {"chapter_number"=>21, "verse_count"=>25}]},
  {"book_number"=>44,
    "abbrev"=>"ACT",
    "name"=>"Acts",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>26},
      {"chapter_number"=>2, "verse_count"=>47},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>37},
      {"chapter_number"=>5, "verse_count"=>42},
      {"chapter_number"=>6, "verse_count"=>15},
      {"chapter_number"=>7, "verse_count"=>60},
      {"chapter_number"=>8, "verse_count"=>39},
      {"chapter_number"=>9, "verse_count"=>43},
      {"chapter_number"=>10, "verse_count"=>48},
      {"chapter_number"=>11, "verse_count"=>30},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>52},
      {"chapter_number"=>14, "verse_count"=>28},
      {"chapter_number"=>15, "verse_count"=>40},
      {"chapter_number"=>16, "verse_count"=>40},
      {"chapter_number"=>17, "verse_count"=>34},
      {"chapter_number"=>18, "verse_count"=>28},
      {"chapter_number"=>19, "verse_count"=>41},
      {"chapter_number"=>20, "verse_count"=>38},
      {"chapter_number"=>21, "verse_count"=>40},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>35},
      {"chapter_number"=>24, "verse_count"=>26},
      {"chapter_number"=>25, "verse_count"=>27},
      {"chapter_number"=>26, "verse_count"=>32},
      {"chapter_number"=>27, "verse_count"=>44},
      {"chapter_number"=>28, "verse_count"=>30}]},
  {"book_number"=>45,
    "abbrev"=>"ROM",
    "name"=>"Romans",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>32},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>31},
      {"chapter_number"=>4, "verse_count"=>25},
      {"chapter_number"=>5, "verse_count"=>21},
      {"chapter_number"=>6, "verse_count"=>23},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>39},
      {"chapter_number"=>9, "verse_count"=>33},
      {"chapter_number"=>10, "verse_count"=>21},
      {"chapter_number"=>11, "verse_count"=>36},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>14},
      {"chapter_number"=>14, "verse_count"=>23},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>26}]},
  {"book_number"=>46,
    "abbrev"=>"1CO",
    "name"=>"1 Corinthians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>23},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>13},
      {"chapter_number"=>6, "verse_count"=>20},
      {"chapter_number"=>7, "verse_count"=>40},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>33},
      {"chapter_number"=>11, "verse_count"=>34},
      {"chapter_number"=>12, "verse_count"=>31},
      {"chapter_number"=>13, "verse_count"=>13},
      {"chapter_number"=>14, "verse_count"=>40},
      {"chapter_number"=>15, "verse_count"=>58},
      {"chapter_number"=>16, "verse_count"=>24}]},
  {"book_number"=>47,
    "abbrev"=>"2CO",
    "name"=>"2 Corinthians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>24},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>18},
      {"chapter_number"=>5, "verse_count"=>21},
      {"chapter_number"=>6, "verse_count"=>18},
      {"chapter_number"=>7, "verse_count"=>16},
      {"chapter_number"=>8, "verse_count"=>24},
      {"chapter_number"=>9, "verse_count"=>15},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>33},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>14}]},
  {"book_number"=>48,
    "abbrev"=>"GAL",
    "name"=>"Galatians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>24},
      {"chapter_number"=>2, "verse_count"=>21},
      {"chapter_number"=>3, "verse_count"=>29},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>26},
      {"chapter_number"=>6, "verse_count"=>18}]},
  {"book_number"=>49,
    "abbrev"=>"EPH",
    "name"=>"Ephesians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>23},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>32},
      {"chapter_number"=>5, "verse_count"=>33},
      {"chapter_number"=>6, "verse_count"=>24}]},
  {"book_number"=>50,
    "abbrev"=>"PHI",
    "name"=>"Philippians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>30},
      {"chapter_number"=>2, "verse_count"=>30},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>23}]},
  {"book_number"=>51,
    "abbrev"=>"COL",
    "name"=>"Colossians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>29},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>25},
      {"chapter_number"=>4, "verse_count"=>18}]},
  {"book_number"=>52,
    "abbrev"=>"1TH",
    "name"=>"1 Thessalonians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>10},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>13},
      {"chapter_number"=>4, "verse_count"=>18},
      {"chapter_number"=>5, "verse_count"=>28}]},
  {"book_number"=>53,
    "abbrev"=>"2TH",
    "name"=>"2 Thessalonians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>12},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18}]},
  {"book_number"=>54,
    "abbrev"=>"1TI",
    "name"=>"1 Timothy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>16},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>25},
      {"chapter_number"=>6, "verse_count"=>21}]},
  {"book_number"=>55,
    "abbrev"=>"2TI",
    "name"=>"2 Timothy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>22}]},
  {"book_number"=>56,
    "abbrev"=>"TIT",
    "name"=>"Titus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>16},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>15}]},
  {"book_number"=>57,
    "abbrev"=>"PHM",
    "name"=>"Philemon",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>25}]},
  {"book_number"=>58,
    "abbrev"=>"HEB",
    "name"=>"Hebrews",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>14},
      {"chapter_number"=>2, "verse_count"=>18},
      {"chapter_number"=>3, "verse_count"=>19},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>20},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>28},
      {"chapter_number"=>10, "verse_count"=>39},
      {"chapter_number"=>11, "verse_count"=>40},
      {"chapter_number"=>12, "verse_count"=>29},
      {"chapter_number"=>13, "verse_count"=>25}]},
  {"book_number"=>59,
    "abbrev"=>"JAM",
    "name"=>"James",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>27},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>20}]},
  {"book_number"=>60,
    "abbrev"=>"1PE",
    "name"=>"1 Peter",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>25},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>19},
      {"chapter_number"=>5, "verse_count"=>14}]},
  {"book_number"=>61,
    "abbrev"=>"2PE",
    "name"=>"2 Peter",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>18}]},
  {"book_number"=>62,
    "abbrev"=>"1JO",
    "name"=>"1 John",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>10},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>21}]},
  {"book_number"=>63,
    "abbrev"=>"2JO",
    "name"=>"2 John",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>13}]},
  {"book_number"=>64,
    "abbrev"=>"3JO",
    "name"=>"3 John",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>15}]},
  {"book_number"=>65,
    "abbrev"=>"JUD",
    "name"=>"Jude",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>25}]},
  {"book_number"=>66,
    "abbrev"=>"REV",
    "name"=>"Revelation",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>11},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>17},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>21},
      {"chapter_number"=>10, "verse_count"=>11},
      {"chapter_number"=>11, "verse_count"=>19},
      {"chapter_number"=>12, "verse_count"=>17},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>20},
      {"chapter_number"=>15, "verse_count"=>8},
      {"chapter_number"=>16, "verse_count"=>21},
      {"chapter_number"=>17, "verse_count"=>18},
      {"chapter_number"=>18, "verse_count"=>24},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>15},
      {"chapter_number"=>21, "verse_count"=>27},
      {"chapter_number"=>22, "verse_count"=>21}]}]
end
