module Scripturable
SCRIPTURE_BOOKS_META = [ {"number"=>1,
    "abbr"=>"GEN",
    "name"=>"Genesis",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>26},
      {"chapter_number"=>5, "verse_count"=>32},
      {"chapter_number"=>6, "verse_count"=>22},
      {"chapter_number"=>7, "verse_count"=>24},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>29},
      {"chapter_number"=>10, "verse_count"=>32},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>20},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>24},
      {"chapter_number"=>15, "verse_count"=>21},
      {"chapter_number"=>16, "verse_count"=>16},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>33},
      {"chapter_number"=>19, "verse_count"=>38},
      {"chapter_number"=>20, "verse_count"=>18},
      {"chapter_number"=>21, "verse_count"=>34},
      {"chapter_number"=>22, "verse_count"=>24},
      {"chapter_number"=>23, "verse_count"=>20},
      {"chapter_number"=>24, "verse_count"=>67},
      {"chapter_number"=>25, "verse_count"=>34},
      {"chapter_number"=>26, "verse_count"=>35},
      {"chapter_number"=>27, "verse_count"=>46},
      {"chapter_number"=>28, "verse_count"=>22},
      {"chapter_number"=>29, "verse_count"=>35},
      {"chapter_number"=>30, "verse_count"=>43},
      {"chapter_number"=>31, "verse_count"=>55},
      {"chapter_number"=>32, "verse_count"=>32},
      {"chapter_number"=>33, "verse_count"=>20},
      {"chapter_number"=>34, "verse_count"=>31},
      {"chapter_number"=>35, "verse_count"=>29},
      {"chapter_number"=>36, "verse_count"=>43},
      {"chapter_number"=>37, "verse_count"=>36},
      {"chapter_number"=>38, "verse_count"=>30},
      {"chapter_number"=>39, "verse_count"=>23},
      {"chapter_number"=>40, "verse_count"=>23},
      {"chapter_number"=>41, "verse_count"=>57},
      {"chapter_number"=>42, "verse_count"=>38},
      {"chapter_number"=>43, "verse_count"=>34},
      {"chapter_number"=>44, "verse_count"=>34},
      {"chapter_number"=>45, "verse_count"=>28},
      {"chapter_number"=>46, "verse_count"=>34},
      {"chapter_number"=>47, "verse_count"=>31},
      {"chapter_number"=>48, "verse_count"=>22},
      {"chapter_number"=>49, "verse_count"=>33},
      {"chapter_number"=>50, "verse_count"=>26}]},
  {"number"=>2,
    "abbr"=>"EXO",
    "name"=>"Exodus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>23},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>32},
      {"chapter_number"=>9, "verse_count"=>35},
      {"chapter_number"=>10, "verse_count"=>29},
      {"chapter_number"=>11, "verse_count"=>10},
      {"chapter_number"=>12, "verse_count"=>51},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>27},
      {"chapter_number"=>16, "verse_count"=>36},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>27},
      {"chapter_number"=>19, "verse_count"=>25},
      {"chapter_number"=>20, "verse_count"=>26},
      {"chapter_number"=>21, "verse_count"=>36},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>33},
      {"chapter_number"=>24, "verse_count"=>18},
      {"chapter_number"=>25, "verse_count"=>40},
      {"chapter_number"=>26, "verse_count"=>37},
      {"chapter_number"=>27, "verse_count"=>21},
      {"chapter_number"=>28, "verse_count"=>43},
      {"chapter_number"=>29, "verse_count"=>46},
      {"chapter_number"=>30, "verse_count"=>38},
      {"chapter_number"=>31, "verse_count"=>18},
      {"chapter_number"=>32, "verse_count"=>35},
      {"chapter_number"=>33, "verse_count"=>23},
      {"chapter_number"=>34, "verse_count"=>35},
      {"chapter_number"=>35, "verse_count"=>35},
      {"chapter_number"=>36, "verse_count"=>38},
      {"chapter_number"=>37, "verse_count"=>29},
      {"chapter_number"=>38, "verse_count"=>31},
      {"chapter_number"=>39, "verse_count"=>43},
      {"chapter_number"=>40, "verse_count"=>38}]},
  {"number"=>3,
    "abbr"=>"LEV",
    "name"=>"Leviticus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>35},
      {"chapter_number"=>5, "verse_count"=>19},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>38},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>24},
      {"chapter_number"=>10, "verse_count"=>20},
      {"chapter_number"=>11, "verse_count"=>47},
      {"chapter_number"=>12, "verse_count"=>8},
      {"chapter_number"=>13, "verse_count"=>59},
      {"chapter_number"=>14, "verse_count"=>57},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>34},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>30},
      {"chapter_number"=>19, "verse_count"=>37},
      {"chapter_number"=>20, "verse_count"=>27},
      {"chapter_number"=>21, "verse_count"=>24},
      {"chapter_number"=>22, "verse_count"=>33},
      {"chapter_number"=>23, "verse_count"=>44},
      {"chapter_number"=>24, "verse_count"=>23},
      {"chapter_number"=>25, "verse_count"=>55},
      {"chapter_number"=>26, "verse_count"=>46},
      {"chapter_number"=>27, "verse_count"=>34}]},
  {"number"=>4,
    "abbr"=>"NUM",
    "name"=>"Numbers",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>54},
      {"chapter_number"=>2, "verse_count"=>34},
      {"chapter_number"=>3, "verse_count"=>51},
      {"chapter_number"=>4, "verse_count"=>49},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>27},
      {"chapter_number"=>7, "verse_count"=>89},
      {"chapter_number"=>8, "verse_count"=>26},
      {"chapter_number"=>9, "verse_count"=>23},
      {"chapter_number"=>10, "verse_count"=>36},
      {"chapter_number"=>11, "verse_count"=>35},
      {"chapter_number"=>12, "verse_count"=>16},
      {"chapter_number"=>13, "verse_count"=>33},
      {"chapter_number"=>14, "verse_count"=>45},
      {"chapter_number"=>15, "verse_count"=>41},
      {"chapter_number"=>16, "verse_count"=>50},
      {"chapter_number"=>17, "verse_count"=>13},
      {"chapter_number"=>18, "verse_count"=>32},
      {"chapter_number"=>19, "verse_count"=>22},
      {"chapter_number"=>20, "verse_count"=>29},
      {"chapter_number"=>21, "verse_count"=>35},
      {"chapter_number"=>22, "verse_count"=>41},
      {"chapter_number"=>23, "verse_count"=>30},
      {"chapter_number"=>24, "verse_count"=>25},
      {"chapter_number"=>25, "verse_count"=>18},
      {"chapter_number"=>26, "verse_count"=>65},
      {"chapter_number"=>27, "verse_count"=>23},
      {"chapter_number"=>28, "verse_count"=>31},
      {"chapter_number"=>29, "verse_count"=>40},
      {"chapter_number"=>30, "verse_count"=>16},
      {"chapter_number"=>31, "verse_count"=>54},
      {"chapter_number"=>32, "verse_count"=>42},
      {"chapter_number"=>33, "verse_count"=>56},
      {"chapter_number"=>34, "verse_count"=>29},
      {"chapter_number"=>35, "verse_count"=>34},
      {"chapter_number"=>36, "verse_count"=>13}]},
  {"number"=>5,
    "abbr"=>"DEU",
    "name"=>"Deuteronomy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>46},
      {"chapter_number"=>2, "verse_count"=>37},
      {"chapter_number"=>3, "verse_count"=>29},
      {"chapter_number"=>4, "verse_count"=>49},
      {"chapter_number"=>5, "verse_count"=>33},
      {"chapter_number"=>6, "verse_count"=>25},
      {"chapter_number"=>7, "verse_count"=>26},
      {"chapter_number"=>8, "verse_count"=>20},
      {"chapter_number"=>9, "verse_count"=>29},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>32},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>29},
      {"chapter_number"=>15, "verse_count"=>23},
      {"chapter_number"=>16, "verse_count"=>22},
      {"chapter_number"=>17, "verse_count"=>20},
      {"chapter_number"=>18, "verse_count"=>22},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>20},
      {"chapter_number"=>21, "verse_count"=>23},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>25},
      {"chapter_number"=>24, "verse_count"=>22},
      {"chapter_number"=>25, "verse_count"=>19},
      {"chapter_number"=>26, "verse_count"=>19},
      {"chapter_number"=>27, "verse_count"=>26},
      {"chapter_number"=>28, "verse_count"=>68},
      {"chapter_number"=>29, "verse_count"=>29},
      {"chapter_number"=>30, "verse_count"=>20},
      {"chapter_number"=>31, "verse_count"=>30},
      {"chapter_number"=>32, "verse_count"=>52},
      {"chapter_number"=>33, "verse_count"=>29},
      {"chapter_number"=>34, "verse_count"=>12}]},
  {"number"=>6,
    "abbr"=>"JOS",
    "name"=>"Joshua",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>24},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>27},
      {"chapter_number"=>7, "verse_count"=>26},
      {"chapter_number"=>8, "verse_count"=>35},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>43},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>24},
      {"chapter_number"=>13, "verse_count"=>33},
      {"chapter_number"=>14, "verse_count"=>15},
      {"chapter_number"=>15, "verse_count"=>63},
      {"chapter_number"=>16, "verse_count"=>10},
      {"chapter_number"=>17, "verse_count"=>18},
      {"chapter_number"=>18, "verse_count"=>28},
      {"chapter_number"=>19, "verse_count"=>51},
      {"chapter_number"=>20, "verse_count"=>9},
      {"chapter_number"=>21, "verse_count"=>45},
      {"chapter_number"=>22, "verse_count"=>34},
      {"chapter_number"=>23, "verse_count"=>16},
      {"chapter_number"=>24, "verse_count"=>33}]},
  {"number"=>7,
    "abbr"=>"JDG",
    "name"=>"Judges",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>36},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>31},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>40},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>35},
      {"chapter_number"=>9, "verse_count"=>57},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>40},
      {"chapter_number"=>12, "verse_count"=>15},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>20},
      {"chapter_number"=>15, "verse_count"=>20},
      {"chapter_number"=>16, "verse_count"=>31},
      {"chapter_number"=>17, "verse_count"=>13},
      {"chapter_number"=>18, "verse_count"=>31},
      {"chapter_number"=>19, "verse_count"=>30},
      {"chapter_number"=>20, "verse_count"=>48},
      {"chapter_number"=>21, "verse_count"=>25}]},
  {"number"=>8,
    "abbr"=>"RUT",
    "name"=>"Ruth",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>22}]},
  {"number"=>9,
    "abbr"=>"1SA",
    "name"=>"1 Samuel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>28},
      {"chapter_number"=>2, "verse_count"=>36},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>12},
      {"chapter_number"=>6, "verse_count"=>21},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>27},
      {"chapter_number"=>11, "verse_count"=>15},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>23},
      {"chapter_number"=>14, "verse_count"=>52},
      {"chapter_number"=>15, "verse_count"=>35},
      {"chapter_number"=>16, "verse_count"=>23},
      {"chapter_number"=>17, "verse_count"=>58},
      {"chapter_number"=>18, "verse_count"=>30},
      {"chapter_number"=>19, "verse_count"=>24},
      {"chapter_number"=>20, "verse_count"=>42},
      {"chapter_number"=>21, "verse_count"=>15},
      {"chapter_number"=>22, "verse_count"=>23},
      {"chapter_number"=>23, "verse_count"=>29},
      {"chapter_number"=>24, "verse_count"=>22},
      {"chapter_number"=>25, "verse_count"=>44},
      {"chapter_number"=>26, "verse_count"=>25},
      {"chapter_number"=>27, "verse_count"=>12},
      {"chapter_number"=>28, "verse_count"=>25},
      {"chapter_number"=>29, "verse_count"=>11},
      {"chapter_number"=>30, "verse_count"=>31},
      {"chapter_number"=>31, "verse_count"=>13}]},
  {"number"=>10,
    "abbr"=>"2SA",
    "name"=>"2 Samuel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>27},
      {"chapter_number"=>2, "verse_count"=>32},
      {"chapter_number"=>3, "verse_count"=>39},
      {"chapter_number"=>4, "verse_count"=>12},
      {"chapter_number"=>5, "verse_count"=>25},
      {"chapter_number"=>6, "verse_count"=>23},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>13},
      {"chapter_number"=>10, "verse_count"=>19},
      {"chapter_number"=>11, "verse_count"=>27},
      {"chapter_number"=>12, "verse_count"=>31},
      {"chapter_number"=>13, "verse_count"=>39},
      {"chapter_number"=>14, "verse_count"=>33},
      {"chapter_number"=>15, "verse_count"=>37},
      {"chapter_number"=>16, "verse_count"=>23},
      {"chapter_number"=>17, "verse_count"=>29},
      {"chapter_number"=>18, "verse_count"=>33},
      {"chapter_number"=>19, "verse_count"=>43},
      {"chapter_number"=>20, "verse_count"=>26},
      {"chapter_number"=>21, "verse_count"=>22},
      {"chapter_number"=>22, "verse_count"=>51},
      {"chapter_number"=>23, "verse_count"=>39},
      {"chapter_number"=>24, "verse_count"=>25}]},
  {"number"=>11,
    "abbr"=>"1KG",
    "name"=>"1 Kings",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>53},
      {"chapter_number"=>2, "verse_count"=>46},
      {"chapter_number"=>3, "verse_count"=>28},
      {"chapter_number"=>4, "verse_count"=>34},
      {"chapter_number"=>5, "verse_count"=>18},
      {"chapter_number"=>6, "verse_count"=>38},
      {"chapter_number"=>7, "verse_count"=>51},
      {"chapter_number"=>8, "verse_count"=>66},
      {"chapter_number"=>9, "verse_count"=>28},
      {"chapter_number"=>10, "verse_count"=>29},
      {"chapter_number"=>11, "verse_count"=>43},
      {"chapter_number"=>12, "verse_count"=>33},
      {"chapter_number"=>13, "verse_count"=>34},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>34},
      {"chapter_number"=>16, "verse_count"=>34},
      {"chapter_number"=>17, "verse_count"=>24},
      {"chapter_number"=>18, "verse_count"=>46},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>43},
      {"chapter_number"=>21, "verse_count"=>29},
      {"chapter_number"=>22, "verse_count"=>53}]},
  {"number"=>12,
    "abbr"=>"2KG",
    "name"=>"2 Kings",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>27},
      {"chapter_number"=>4, "verse_count"=>44},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>33},
      {"chapter_number"=>7, "verse_count"=>20},
      {"chapter_number"=>8, "verse_count"=>29},
      {"chapter_number"=>9, "verse_count"=>37},
      {"chapter_number"=>10, "verse_count"=>36},
      {"chapter_number"=>11, "verse_count"=>21},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>29},
      {"chapter_number"=>15, "verse_count"=>38},
      {"chapter_number"=>16, "verse_count"=>20},
      {"chapter_number"=>17, "verse_count"=>41},
      {"chapter_number"=>18, "verse_count"=>37},
      {"chapter_number"=>19, "verse_count"=>37},
      {"chapter_number"=>20, "verse_count"=>21},
      {"chapter_number"=>21, "verse_count"=>26},
      {"chapter_number"=>22, "verse_count"=>20},
      {"chapter_number"=>23, "verse_count"=>37},
      {"chapter_number"=>24, "verse_count"=>20},
      {"chapter_number"=>25, "verse_count"=>30}]},
  {"number"=>13,
    "abbr"=>"1KR",
    "name"=>"1 Chronicles",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>54},
      {"chapter_number"=>2, "verse_count"=>55},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>43},
      {"chapter_number"=>5, "verse_count"=>26},
      {"chapter_number"=>6, "verse_count"=>81},
      {"chapter_number"=>7, "verse_count"=>40},
      {"chapter_number"=>8, "verse_count"=>40},
      {"chapter_number"=>9, "verse_count"=>44},
      {"chapter_number"=>10, "verse_count"=>14},
      {"chapter_number"=>11, "verse_count"=>47},
      {"chapter_number"=>12, "verse_count"=>40},
      {"chapter_number"=>13, "verse_count"=>14},
      {"chapter_number"=>14, "verse_count"=>17},
      {"chapter_number"=>15, "verse_count"=>29},
      {"chapter_number"=>16, "verse_count"=>43},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>17},
      {"chapter_number"=>19, "verse_count"=>19},
      {"chapter_number"=>20, "verse_count"=>8},
      {"chapter_number"=>21, "verse_count"=>30},
      {"chapter_number"=>22, "verse_count"=>19},
      {"chapter_number"=>23, "verse_count"=>32},
      {"chapter_number"=>24, "verse_count"=>31},
      {"chapter_number"=>25, "verse_count"=>31},
      {"chapter_number"=>26, "verse_count"=>32},
      {"chapter_number"=>27, "verse_count"=>34},
      {"chapter_number"=>28, "verse_count"=>21},
      {"chapter_number"=>29, "verse_count"=>30}]},
  {"number"=>14,
    "abbr"=>"2KR",
    "name"=>"2 Chronicles",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>18},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>42},
      {"chapter_number"=>7, "verse_count"=>22},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>31},
      {"chapter_number"=>10, "verse_count"=>19},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>16},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>15},
      {"chapter_number"=>15, "verse_count"=>19},
      {"chapter_number"=>16, "verse_count"=>14},
      {"chapter_number"=>17, "verse_count"=>19},
      {"chapter_number"=>18, "verse_count"=>34},
      {"chapter_number"=>19, "verse_count"=>11},
      {"chapter_number"=>20, "verse_count"=>37},
      {"chapter_number"=>21, "verse_count"=>20},
      {"chapter_number"=>22, "verse_count"=>12},
      {"chapter_number"=>23, "verse_count"=>21},
      {"chapter_number"=>24, "verse_count"=>27},
      {"chapter_number"=>25, "verse_count"=>28},
      {"chapter_number"=>26, "verse_count"=>23},
      {"chapter_number"=>27, "verse_count"=>9},
      {"chapter_number"=>28, "verse_count"=>27},
      {"chapter_number"=>29, "verse_count"=>36},
      {"chapter_number"=>30, "verse_count"=>27},
      {"chapter_number"=>31, "verse_count"=>21},
      {"chapter_number"=>32, "verse_count"=>33},
      {"chapter_number"=>33, "verse_count"=>25},
      {"chapter_number"=>34, "verse_count"=>33},
      {"chapter_number"=>35, "verse_count"=>27},
      {"chapter_number"=>36, "verse_count"=>23}]},
  {"number"=>15,
    "abbr"=>"EZR",
    "name"=>"Ezra",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>70},
      {"chapter_number"=>3, "verse_count"=>13},
      {"chapter_number"=>4, "verse_count"=>24},
      {"chapter_number"=>5, "verse_count"=>17},
      {"chapter_number"=>6, "verse_count"=>22},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>15},
      {"chapter_number"=>10, "verse_count"=>44}]},
  {"number"=>16,
    "abbr"=>"NEH",
    "name"=>"Nehemiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>32},
      {"chapter_number"=>4, "verse_count"=>23},
      {"chapter_number"=>5, "verse_count"=>19},
      {"chapter_number"=>6, "verse_count"=>19},
      {"chapter_number"=>7, "verse_count"=>73},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>38},
      {"chapter_number"=>10, "verse_count"=>39},
      {"chapter_number"=>11, "verse_count"=>36},
      {"chapter_number"=>12, "verse_count"=>47},
      {"chapter_number"=>13, "verse_count"=>31}]},
  {"number"=>17,
    "abbr"=>"EST",
    "name"=>"Esther",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>15},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>10},
      {"chapter_number"=>8, "verse_count"=>17},
      {"chapter_number"=>9, "verse_count"=>32},
      {"chapter_number"=>10, "verse_count"=>3}]},
  {"number"=>18,
    "abbr"=>"JOB",
    "name"=>"Job",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>21},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>35},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>20},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>28},
      {"chapter_number"=>14, "verse_count"=>22},
      {"chapter_number"=>15, "verse_count"=>35},
      {"chapter_number"=>16, "verse_count"=>22},
      {"chapter_number"=>17, "verse_count"=>16},
      {"chapter_number"=>18, "verse_count"=>21},
      {"chapter_number"=>19, "verse_count"=>29},
      {"chapter_number"=>20, "verse_count"=>29},
      {"chapter_number"=>21, "verse_count"=>34},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>17},
      {"chapter_number"=>24, "verse_count"=>25},
      {"chapter_number"=>25, "verse_count"=>6},
      {"chapter_number"=>26, "verse_count"=>14},
      {"chapter_number"=>27, "verse_count"=>23},
      {"chapter_number"=>28, "verse_count"=>28},
      {"chapter_number"=>29, "verse_count"=>25},
      {"chapter_number"=>30, "verse_count"=>31},
      {"chapter_number"=>31, "verse_count"=>40},
      {"chapter_number"=>32, "verse_count"=>22},
      {"chapter_number"=>33, "verse_count"=>33},
      {"chapter_number"=>34, "verse_count"=>37},
      {"chapter_number"=>35, "verse_count"=>16},
      {"chapter_number"=>36, "verse_count"=>33},
      {"chapter_number"=>37, "verse_count"=>24},
      {"chapter_number"=>38, "verse_count"=>41},
      {"chapter_number"=>39, "verse_count"=>30},
      {"chapter_number"=>40, "verse_count"=>24},
      {"chapter_number"=>41, "verse_count"=>34},
      {"chapter_number"=>42, "verse_count"=>17}]},
  {"number"=>19,
    "abbr"=>"PSA",
    "name"=>"Psalms",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>6},
      {"chapter_number"=>2, "verse_count"=>12},
      {"chapter_number"=>3, "verse_count"=>8},
      {"chapter_number"=>4, "verse_count"=>8},
      {"chapter_number"=>5, "verse_count"=>12},
      {"chapter_number"=>6, "verse_count"=>10},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>9},
      {"chapter_number"=>9, "verse_count"=>20},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>7},
      {"chapter_number"=>12, "verse_count"=>8},
      {"chapter_number"=>13, "verse_count"=>6},
      {"chapter_number"=>14, "verse_count"=>7},
      {"chapter_number"=>15, "verse_count"=>5},
      {"chapter_number"=>16, "verse_count"=>11},
      {"chapter_number"=>17, "verse_count"=>15},
      {"chapter_number"=>18, "verse_count"=>50},
      {"chapter_number"=>19, "verse_count"=>14},
      {"chapter_number"=>20, "verse_count"=>9},
      {"chapter_number"=>21, "verse_count"=>13},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>6},
      {"chapter_number"=>24, "verse_count"=>10},
      {"chapter_number"=>25, "verse_count"=>22},
      {"chapter_number"=>26, "verse_count"=>12},
      {"chapter_number"=>27, "verse_count"=>14},
      {"chapter_number"=>28, "verse_count"=>9},
      {"chapter_number"=>29, "verse_count"=>11},
      {"chapter_number"=>30, "verse_count"=>12},
      {"chapter_number"=>31, "verse_count"=>24},
      {"chapter_number"=>32, "verse_count"=>11},
      {"chapter_number"=>33, "verse_count"=>22},
      {"chapter_number"=>34, "verse_count"=>22},
      {"chapter_number"=>35, "verse_count"=>28},
      {"chapter_number"=>36, "verse_count"=>12},
      {"chapter_number"=>37, "verse_count"=>40},
      {"chapter_number"=>38, "verse_count"=>22},
      {"chapter_number"=>39, "verse_count"=>13},
      {"chapter_number"=>40, "verse_count"=>17},
      {"chapter_number"=>41, "verse_count"=>13},
      {"chapter_number"=>42, "verse_count"=>11},
      {"chapter_number"=>43, "verse_count"=>5},
      {"chapter_number"=>44, "verse_count"=>26},
      {"chapter_number"=>45, "verse_count"=>17},
      {"chapter_number"=>46, "verse_count"=>11},
      {"chapter_number"=>47, "verse_count"=>9},
      {"chapter_number"=>48, "verse_count"=>14},
      {"chapter_number"=>49, "verse_count"=>20},
      {"chapter_number"=>50, "verse_count"=>23},
      {"chapter_number"=>51, "verse_count"=>19},
      {"chapter_number"=>52, "verse_count"=>9},
      {"chapter_number"=>53, "verse_count"=>6},
      {"chapter_number"=>54, "verse_count"=>7},
      {"chapter_number"=>55, "verse_count"=>23},
      {"chapter_number"=>56, "verse_count"=>13},
      {"chapter_number"=>57, "verse_count"=>11},
      {"chapter_number"=>58, "verse_count"=>11},
      {"chapter_number"=>59, "verse_count"=>17},
      {"chapter_number"=>60, "verse_count"=>12},
      {"chapter_number"=>61, "verse_count"=>8},
      {"chapter_number"=>62, "verse_count"=>12},
      {"chapter_number"=>63, "verse_count"=>11},
      {"chapter_number"=>64, "verse_count"=>10},
      {"chapter_number"=>65, "verse_count"=>13},
      {"chapter_number"=>66, "verse_count"=>20},
      {"chapter_number"=>67, "verse_count"=>7},
      {"chapter_number"=>68, "verse_count"=>35},
      {"chapter_number"=>69, "verse_count"=>36},
      {"chapter_number"=>70, "verse_count"=>5},
      {"chapter_number"=>71, "verse_count"=>24},
      {"chapter_number"=>72, "verse_count"=>20},
      {"chapter_number"=>73, "verse_count"=>28},
      {"chapter_number"=>74, "verse_count"=>23},
      {"chapter_number"=>75, "verse_count"=>10},
      {"chapter_number"=>76, "verse_count"=>12},
      {"chapter_number"=>77, "verse_count"=>20},
      {"chapter_number"=>78, "verse_count"=>72},
      {"chapter_number"=>79, "verse_count"=>13},
      {"chapter_number"=>80, "verse_count"=>19},
      {"chapter_number"=>81, "verse_count"=>16},
      {"chapter_number"=>82, "verse_count"=>8},
      {"chapter_number"=>83, "verse_count"=>18},
      {"chapter_number"=>84, "verse_count"=>12},
      {"chapter_number"=>85, "verse_count"=>13},
      {"chapter_number"=>86, "verse_count"=>17},
      {"chapter_number"=>87, "verse_count"=>7},
      {"chapter_number"=>88, "verse_count"=>18},
      {"chapter_number"=>89, "verse_count"=>52},
      {"chapter_number"=>90, "verse_count"=>17},
      {"chapter_number"=>91, "verse_count"=>16},
      {"chapter_number"=>92, "verse_count"=>15},
      {"chapter_number"=>93, "verse_count"=>5},
      {"chapter_number"=>94, "verse_count"=>23},
      {"chapter_number"=>95, "verse_count"=>11},
      {"chapter_number"=>96, "verse_count"=>13},
      {"chapter_number"=>97, "verse_count"=>12},
      {"chapter_number"=>98, "verse_count"=>9},
      {"chapter_number"=>99, "verse_count"=>9},
      {"chapter_number"=>100, "verse_count"=>5},
      {"chapter_number"=>101, "verse_count"=>8},
      {"chapter_number"=>102, "verse_count"=>28},
      {"chapter_number"=>103, "verse_count"=>22},
      {"chapter_number"=>104, "verse_count"=>35},
      {"chapter_number"=>105, "verse_count"=>45},
      {"chapter_number"=>106, "verse_count"=>48},
      {"chapter_number"=>107, "verse_count"=>43},
      {"chapter_number"=>108, "verse_count"=>13},
      {"chapter_number"=>109, "verse_count"=>31},
      {"chapter_number"=>110, "verse_count"=>7},
      {"chapter_number"=>111, "verse_count"=>10},
      {"chapter_number"=>112, "verse_count"=>10},
      {"chapter_number"=>113, "verse_count"=>9},
      {"chapter_number"=>114, "verse_count"=>8},
      {"chapter_number"=>115, "verse_count"=>18},
      {"chapter_number"=>116, "verse_count"=>19},
      {"chapter_number"=>117, "verse_count"=>2},
      {"chapter_number"=>118, "verse_count"=>29},
      {"chapter_number"=>119, "verse_count"=>176},
      {"chapter_number"=>120, "verse_count"=>7},
      {"chapter_number"=>121, "verse_count"=>8},
      {"chapter_number"=>122, "verse_count"=>9},
      {"chapter_number"=>123, "verse_count"=>4},
      {"chapter_number"=>124, "verse_count"=>8},
      {"chapter_number"=>125, "verse_count"=>5},
      {"chapter_number"=>126, "verse_count"=>6},
      {"chapter_number"=>127, "verse_count"=>5},
      {"chapter_number"=>128, "verse_count"=>6},
      {"chapter_number"=>129, "verse_count"=>8},
      {"chapter_number"=>130, "verse_count"=>8},
      {"chapter_number"=>131, "verse_count"=>3},
      {"chapter_number"=>132, "verse_count"=>18},
      {"chapter_number"=>133, "verse_count"=>3},
      {"chapter_number"=>134, "verse_count"=>3},
      {"chapter_number"=>135, "verse_count"=>21},
      {"chapter_number"=>136, "verse_count"=>26},
      {"chapter_number"=>137, "verse_count"=>9},
      {"chapter_number"=>138, "verse_count"=>8},
      {"chapter_number"=>139, "verse_count"=>24},
      {"chapter_number"=>140, "verse_count"=>13},
      {"chapter_number"=>141, "verse_count"=>10},
      {"chapter_number"=>142, "verse_count"=>7},
      {"chapter_number"=>143, "verse_count"=>12},
      {"chapter_number"=>144, "verse_count"=>15},
      {"chapter_number"=>145, "verse_count"=>21},
      {"chapter_number"=>146, "verse_count"=>10},
      {"chapter_number"=>147, "verse_count"=>20},
      {"chapter_number"=>148, "verse_count"=>14},
      {"chapter_number"=>149, "verse_count"=>9},
      {"chapter_number"=>150, "verse_count"=>6}]},
  {"number"=>20,
    "abbr"=>"PRO",
    "name"=>"Proverbs",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>33},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>35},
      {"chapter_number"=>4, "verse_count"=>27},
      {"chapter_number"=>5, "verse_count"=>23},
      {"chapter_number"=>6, "verse_count"=>35},
      {"chapter_number"=>7, "verse_count"=>27},
      {"chapter_number"=>8, "verse_count"=>36},
      {"chapter_number"=>9, "verse_count"=>18},
      {"chapter_number"=>10, "verse_count"=>32},
      {"chapter_number"=>11, "verse_count"=>31},
      {"chapter_number"=>12, "verse_count"=>28},
      {"chapter_number"=>13, "verse_count"=>25},
      {"chapter_number"=>14, "verse_count"=>35},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>33},
      {"chapter_number"=>17, "verse_count"=>28},
      {"chapter_number"=>18, "verse_count"=>24},
      {"chapter_number"=>19, "verse_count"=>29},
      {"chapter_number"=>20, "verse_count"=>30},
      {"chapter_number"=>21, "verse_count"=>31},
      {"chapter_number"=>22, "verse_count"=>29},
      {"chapter_number"=>23, "verse_count"=>35},
      {"chapter_number"=>24, "verse_count"=>34},
      {"chapter_number"=>25, "verse_count"=>28},
      {"chapter_number"=>26, "verse_count"=>28},
      {"chapter_number"=>27, "verse_count"=>27},
      {"chapter_number"=>28, "verse_count"=>28},
      {"chapter_number"=>29, "verse_count"=>27},
      {"chapter_number"=>30, "verse_count"=>33},
      {"chapter_number"=>31, "verse_count"=>31}]},
  {"number"=>21,
    "abbr"=>"ECC",
    "name"=>"Ecclesiastes",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>20},
      {"chapter_number"=>6, "verse_count"=>12},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>17},
      {"chapter_number"=>9, "verse_count"=>18},
      {"chapter_number"=>10, "verse_count"=>20},
      {"chapter_number"=>11, "verse_count"=>10},
      {"chapter_number"=>12, "verse_count"=>14}]},
  {"number"=>22,
    "abbr"=>"SO",
    "name"=>"Song",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>11},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>16},
      {"chapter_number"=>6, "verse_count"=>13},
      {"chapter_number"=>7, "verse_count"=>13},
      {"chapter_number"=>8, "verse_count"=>14}]},
  {"number"=>23,
    "abbr"=>"ISA",
    "name"=>"Isaiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>6},
      {"chapter_number"=>5, "verse_count"=>30},
      {"chapter_number"=>6, "verse_count"=>13},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>21},
      {"chapter_number"=>10, "verse_count"=>34},
      {"chapter_number"=>11, "verse_count"=>16},
      {"chapter_number"=>12, "verse_count"=>6},
      {"chapter_number"=>13, "verse_count"=>22},
      {"chapter_number"=>14, "verse_count"=>32},
      {"chapter_number"=>15, "verse_count"=>9},
      {"chapter_number"=>16, "verse_count"=>14},
      {"chapter_number"=>17, "verse_count"=>14},
      {"chapter_number"=>18, "verse_count"=>7},
      {"chapter_number"=>19, "verse_count"=>25},
      {"chapter_number"=>20, "verse_count"=>6},
      {"chapter_number"=>21, "verse_count"=>17},
      {"chapter_number"=>22, "verse_count"=>25},
      {"chapter_number"=>23, "verse_count"=>18},
      {"chapter_number"=>24, "verse_count"=>23},
      {"chapter_number"=>25, "verse_count"=>12},
      {"chapter_number"=>26, "verse_count"=>21},
      {"chapter_number"=>27, "verse_count"=>13},
      {"chapter_number"=>28, "verse_count"=>29},
      {"chapter_number"=>29, "verse_count"=>24},
      {"chapter_number"=>30, "verse_count"=>33},
      {"chapter_number"=>31, "verse_count"=>9},
      {"chapter_number"=>32, "verse_count"=>20},
      {"chapter_number"=>33, "verse_count"=>24},
      {"chapter_number"=>34, "verse_count"=>17},
      {"chapter_number"=>35, "verse_count"=>10},
      {"chapter_number"=>36, "verse_count"=>22},
      {"chapter_number"=>37, "verse_count"=>38},
      {"chapter_number"=>38, "verse_count"=>22},
      {"chapter_number"=>39, "verse_count"=>8},
      {"chapter_number"=>40, "verse_count"=>31},
      {"chapter_number"=>41, "verse_count"=>29},
      {"chapter_number"=>42, "verse_count"=>25},
      {"chapter_number"=>43, "verse_count"=>28},
      {"chapter_number"=>44, "verse_count"=>28},
      {"chapter_number"=>45, "verse_count"=>25},
      {"chapter_number"=>46, "verse_count"=>13},
      {"chapter_number"=>47, "verse_count"=>15},
      {"chapter_number"=>48, "verse_count"=>22},
      {"chapter_number"=>49, "verse_count"=>26},
      {"chapter_number"=>50, "verse_count"=>11},
      {"chapter_number"=>51, "verse_count"=>23},
      {"chapter_number"=>52, "verse_count"=>15},
      {"chapter_number"=>53, "verse_count"=>12},
      {"chapter_number"=>54, "verse_count"=>17},
      {"chapter_number"=>55, "verse_count"=>13},
      {"chapter_number"=>56, "verse_count"=>12},
      {"chapter_number"=>57, "verse_count"=>21},
      {"chapter_number"=>58, "verse_count"=>14},
      {"chapter_number"=>59, "verse_count"=>21},
      {"chapter_number"=>60, "verse_count"=>22},
      {"chapter_number"=>61, "verse_count"=>11},
      {"chapter_number"=>62, "verse_count"=>12},
      {"chapter_number"=>63, "verse_count"=>19},
      {"chapter_number"=>64, "verse_count"=>12},
      {"chapter_number"=>65, "verse_count"=>25},
      {"chapter_number"=>66, "verse_count"=>24}]},
  {"number"=>24,
    "abbr"=>"JER",
    "name"=>"Jeremiah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>19},
      {"chapter_number"=>2, "verse_count"=>37},
      {"chapter_number"=>3, "verse_count"=>25},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>30},
      {"chapter_number"=>7, "verse_count"=>34},
      {"chapter_number"=>8, "verse_count"=>22},
      {"chapter_number"=>9, "verse_count"=>26},
      {"chapter_number"=>10, "verse_count"=>25},
      {"chapter_number"=>11, "verse_count"=>23},
      {"chapter_number"=>12, "verse_count"=>17},
      {"chapter_number"=>13, "verse_count"=>27},
      {"chapter_number"=>14, "verse_count"=>22},
      {"chapter_number"=>15, "verse_count"=>21},
      {"chapter_number"=>16, "verse_count"=>21},
      {"chapter_number"=>17, "verse_count"=>27},
      {"chapter_number"=>18, "verse_count"=>23},
      {"chapter_number"=>19, "verse_count"=>15},
      {"chapter_number"=>20, "verse_count"=>18},
      {"chapter_number"=>21, "verse_count"=>14},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>40},
      {"chapter_number"=>24, "verse_count"=>10},
      {"chapter_number"=>25, "verse_count"=>38},
      {"chapter_number"=>26, "verse_count"=>24},
      {"chapter_number"=>27, "verse_count"=>22},
      {"chapter_number"=>28, "verse_count"=>17},
      {"chapter_number"=>29, "verse_count"=>32},
      {"chapter_number"=>30, "verse_count"=>24},
      {"chapter_number"=>31, "verse_count"=>40},
      {"chapter_number"=>32, "verse_count"=>44},
      {"chapter_number"=>33, "verse_count"=>26},
      {"chapter_number"=>34, "verse_count"=>22},
      {"chapter_number"=>35, "verse_count"=>19},
      {"chapter_number"=>36, "verse_count"=>32},
      {"chapter_number"=>37, "verse_count"=>21},
      {"chapter_number"=>38, "verse_count"=>28},
      {"chapter_number"=>39, "verse_count"=>18},
      {"chapter_number"=>40, "verse_count"=>16},
      {"chapter_number"=>41, "verse_count"=>18},
      {"chapter_number"=>42, "verse_count"=>22},
      {"chapter_number"=>43, "verse_count"=>13},
      {"chapter_number"=>44, "verse_count"=>30},
      {"chapter_number"=>45, "verse_count"=>5},
      {"chapter_number"=>46, "verse_count"=>28},
      {"chapter_number"=>47, "verse_count"=>7},
      {"chapter_number"=>48, "verse_count"=>47},
      {"chapter_number"=>49, "verse_count"=>39},
      {"chapter_number"=>50, "verse_count"=>46},
      {"chapter_number"=>51, "verse_count"=>64},
      {"chapter_number"=>52, "verse_count"=>34}]},
  {"number"=>25,
    "abbr"=>"LAM",
    "name"=>"Lamentations",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>22},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>66},
      {"chapter_number"=>4, "verse_count"=>22},
      {"chapter_number"=>5, "verse_count"=>22}]},
  {"number"=>26,
    "abbr"=>"EZE",
    "name"=>"Ezekiel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>28},
      {"chapter_number"=>2, "verse_count"=>10},
      {"chapter_number"=>3, "verse_count"=>27},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>17},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>27},
      {"chapter_number"=>8, "verse_count"=>18},
      {"chapter_number"=>9, "verse_count"=>11},
      {"chapter_number"=>10, "verse_count"=>22},
      {"chapter_number"=>11, "verse_count"=>25},
      {"chapter_number"=>12, "verse_count"=>28},
      {"chapter_number"=>13, "verse_count"=>23},
      {"chapter_number"=>14, "verse_count"=>23},
      {"chapter_number"=>15, "verse_count"=>8},
      {"chapter_number"=>16, "verse_count"=>63},
      {"chapter_number"=>17, "verse_count"=>24},
      {"chapter_number"=>18, "verse_count"=>32},
      {"chapter_number"=>19, "verse_count"=>14},
      {"chapter_number"=>20, "verse_count"=>49},
      {"chapter_number"=>21, "verse_count"=>32},
      {"chapter_number"=>22, "verse_count"=>31},
      {"chapter_number"=>23, "verse_count"=>49},
      {"chapter_number"=>24, "verse_count"=>27},
      {"chapter_number"=>25, "verse_count"=>17},
      {"chapter_number"=>26, "verse_count"=>21},
      {"chapter_number"=>27, "verse_count"=>36},
      {"chapter_number"=>28, "verse_count"=>26},
      {"chapter_number"=>29, "verse_count"=>21},
      {"chapter_number"=>30, "verse_count"=>26},
      {"chapter_number"=>31, "verse_count"=>18},
      {"chapter_number"=>32, "verse_count"=>32},
      {"chapter_number"=>33, "verse_count"=>33},
      {"chapter_number"=>34, "verse_count"=>31},
      {"chapter_number"=>35, "verse_count"=>15},
      {"chapter_number"=>36, "verse_count"=>38},
      {"chapter_number"=>37, "verse_count"=>28},
      {"chapter_number"=>38, "verse_count"=>23},
      {"chapter_number"=>39, "verse_count"=>29},
      {"chapter_number"=>40, "verse_count"=>49},
      {"chapter_number"=>41, "verse_count"=>26},
      {"chapter_number"=>42, "verse_count"=>20},
      {"chapter_number"=>43, "verse_count"=>27},
      {"chapter_number"=>44, "verse_count"=>31},
      {"chapter_number"=>45, "verse_count"=>25},
      {"chapter_number"=>46, "verse_count"=>24},
      {"chapter_number"=>47, "verse_count"=>23},
      {"chapter_number"=>48, "verse_count"=>35}]},
  {"number"=>27,
    "abbr"=>"DAN",
    "name"=>"Daniel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>49},
      {"chapter_number"=>3, "verse_count"=>30},
      {"chapter_number"=>4, "verse_count"=>37},
      {"chapter_number"=>5, "verse_count"=>31},
      {"chapter_number"=>6, "verse_count"=>28},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>27},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>21},
      {"chapter_number"=>11, "verse_count"=>45},
      {"chapter_number"=>12, "verse_count"=>13}]},
  {"number"=>28,
    "abbr"=>"HOS",
    "name"=>"Hosea",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>11},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>5},
      {"chapter_number"=>4, "verse_count"=>19},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>11},
      {"chapter_number"=>7, "verse_count"=>16},
      {"chapter_number"=>8, "verse_count"=>14},
      {"chapter_number"=>9, "verse_count"=>17},
      {"chapter_number"=>10, "verse_count"=>15},
      {"chapter_number"=>11, "verse_count"=>12},
      {"chapter_number"=>12, "verse_count"=>14},
      {"chapter_number"=>13, "verse_count"=>16},
      {"chapter_number"=>14, "verse_count"=>9}]},
  {"number"=>29,
    "abbr"=>"JOE",
    "name"=>"Joel",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>32},
      {"chapter_number"=>3, "verse_count"=>21}]},
  {"number"=>30,
    "abbr"=>"AMO",
    "name"=>"Amos",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>15},
      {"chapter_number"=>4, "verse_count"=>13},
      {"chapter_number"=>5, "verse_count"=>27},
      {"chapter_number"=>6, "verse_count"=>14},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>14},
      {"chapter_number"=>9, "verse_count"=>15}]},
  {"number"=>31,
    "abbr"=>"OBA",
    "name"=>"Obadiah",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>21}]},
  {"number"=>32,
    "abbr"=>"JON",
    "name"=>"Jonah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>10},
      {"chapter_number"=>3, "verse_count"=>10},
      {"chapter_number"=>4, "verse_count"=>11}]},
  {"number"=>33,
    "abbr"=>"MIC",
    "name"=>"Micah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>16},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>12},
      {"chapter_number"=>4, "verse_count"=>13},
      {"chapter_number"=>5, "verse_count"=>15},
      {"chapter_number"=>6, "verse_count"=>16},
      {"chapter_number"=>7, "verse_count"=>20}]},
  {"number"=>34,
    "abbr"=>"NAH",
    "name"=>"Nahum",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>19}]},
  {"number"=>35,
    "abbr"=>"HAB",
    "name"=>"Habakkuk",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>17},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>19}]},
  {"number"=>36,
    "abbr"=>"ZEP",
    "name"=>"Zephaniah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>20}]},
  {"number"=>37,
    "abbr"=>"HAG",
    "name"=>"Haggai",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>15}, 
      {"chapter_number"=>2, "verse_count"=>23}]},
  {"number"=>38,
    "abbr"=>"ZEC",
    "name"=>"Zechariah",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>13},
      {"chapter_number"=>3, "verse_count"=>10},
      {"chapter_number"=>4, "verse_count"=>14},
      {"chapter_number"=>5, "verse_count"=>11},
      {"chapter_number"=>6, "verse_count"=>15},
      {"chapter_number"=>7, "verse_count"=>14},
      {"chapter_number"=>8, "verse_count"=>23},
      {"chapter_number"=>9, "verse_count"=>17},
      {"chapter_number"=>10, "verse_count"=>12},
      {"chapter_number"=>11, "verse_count"=>17},
      {"chapter_number"=>12, "verse_count"=>14},
      {"chapter_number"=>13, "verse_count"=>9},
      {"chapter_number"=>14, "verse_count"=>21}]},
  {"number"=>39,
    "abbr"=>"MAL",
    "name"=>"Malachi",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>14},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>6}]},
  {"number"=>40,
    "abbr"=>"MAT",
    "name"=>"Matthew",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>25},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>25},
      {"chapter_number"=>5, "verse_count"=>48},
      {"chapter_number"=>6, "verse_count"=>34},
      {"chapter_number"=>7, "verse_count"=>29},
      {"chapter_number"=>8, "verse_count"=>34},
      {"chapter_number"=>9, "verse_count"=>38},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>30},
      {"chapter_number"=>12, "verse_count"=>49},
      {"chapter_number"=>13, "verse_count"=>58},
      {"chapter_number"=>14, "verse_count"=>36},
      {"chapter_number"=>15, "verse_count"=>39},
      {"chapter_number"=>16, "verse_count"=>28},
      {"chapter_number"=>17, "verse_count"=>26},
      {"chapter_number"=>18, "verse_count"=>34},
      {"chapter_number"=>19, "verse_count"=>30},
      {"chapter_number"=>20, "verse_count"=>34},
      {"chapter_number"=>21, "verse_count"=>46},
      {"chapter_number"=>22, "verse_count"=>46},
      {"chapter_number"=>23, "verse_count"=>38},
      {"chapter_number"=>24, "verse_count"=>51},
      {"chapter_number"=>25, "verse_count"=>46},
      {"chapter_number"=>26, "verse_count"=>75},
      {"chapter_number"=>27, "verse_count"=>66},
      {"chapter_number"=>28, "verse_count"=>20}]},
  {"number"=>41,
    "abbr"=>"MAR",
    "name"=>"Mark",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>45},
      {"chapter_number"=>2, "verse_count"=>28},
      {"chapter_number"=>3, "verse_count"=>35},
      {"chapter_number"=>4, "verse_count"=>41},
      {"chapter_number"=>5, "verse_count"=>43},
      {"chapter_number"=>6, "verse_count"=>56},
      {"chapter_number"=>7, "verse_count"=>36},
      {"chapter_number"=>8, "verse_count"=>38},
      {"chapter_number"=>9, "verse_count"=>48},
      {"chapter_number"=>10, "verse_count"=>52},
      {"chapter_number"=>11, "verse_count"=>32},
      {"chapter_number"=>12, "verse_count"=>44},
      {"chapter_number"=>13, "verse_count"=>37},
      {"chapter_number"=>14, "verse_count"=>72},
      {"chapter_number"=>15, "verse_count"=>46},
      {"chapter_number"=>16, "verse_count"=>20}]},
  {"number"=>42,
    "abbr"=>"LUK",
    "name"=>"Luke",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>80},
      {"chapter_number"=>2, "verse_count"=>52},
      {"chapter_number"=>3, "verse_count"=>38},
      {"chapter_number"=>4, "verse_count"=>44},
      {"chapter_number"=>5, "verse_count"=>39},
      {"chapter_number"=>6, "verse_count"=>49},
      {"chapter_number"=>7, "verse_count"=>50},
      {"chapter_number"=>8, "verse_count"=>56},
      {"chapter_number"=>9, "verse_count"=>62},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>54},
      {"chapter_number"=>12, "verse_count"=>59},
      {"chapter_number"=>13, "verse_count"=>35},
      {"chapter_number"=>14, "verse_count"=>35},
      {"chapter_number"=>15, "verse_count"=>32},
      {"chapter_number"=>16, "verse_count"=>31},
      {"chapter_number"=>17, "verse_count"=>36},
      {"chapter_number"=>18, "verse_count"=>43},
      {"chapter_number"=>19, "verse_count"=>48},
      {"chapter_number"=>20, "verse_count"=>47},
      {"chapter_number"=>21, "verse_count"=>38},
      {"chapter_number"=>22, "verse_count"=>71},
      {"chapter_number"=>23, "verse_count"=>55},
      {"chapter_number"=>24, "verse_count"=>53}]},
  {"number"=>43,
    "abbr"=>"JOH",
    "name"=>"John",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>51},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>36},
      {"chapter_number"=>4, "verse_count"=>54},
      {"chapter_number"=>5, "verse_count"=>46},
      {"chapter_number"=>6, "verse_count"=>71},
      {"chapter_number"=>7, "verse_count"=>53},
      {"chapter_number"=>8, "verse_count"=>59},
      {"chapter_number"=>9, "verse_count"=>41},
      {"chapter_number"=>10, "verse_count"=>42},
      {"chapter_number"=>11, "verse_count"=>57},
      {"chapter_number"=>12, "verse_count"=>50},
      {"chapter_number"=>13, "verse_count"=>38},
      {"chapter_number"=>14, "verse_count"=>31},
      {"chapter_number"=>15, "verse_count"=>27},
      {"chapter_number"=>16, "verse_count"=>33},
      {"chapter_number"=>17, "verse_count"=>26},
      {"chapter_number"=>18, "verse_count"=>40},
      {"chapter_number"=>19, "verse_count"=>42},
      {"chapter_number"=>20, "verse_count"=>31},
      {"chapter_number"=>21, "verse_count"=>25}]},
  {"number"=>44,
    "abbr"=>"ACT",
    "name"=>"Acts",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>26},
      {"chapter_number"=>2, "verse_count"=>47},
      {"chapter_number"=>3, "verse_count"=>26},
      {"chapter_number"=>4, "verse_count"=>37},
      {"chapter_number"=>5, "verse_count"=>42},
      {"chapter_number"=>6, "verse_count"=>15},
      {"chapter_number"=>7, "verse_count"=>60},
      {"chapter_number"=>8, "verse_count"=>39},
      {"chapter_number"=>9, "verse_count"=>43},
      {"chapter_number"=>10, "verse_count"=>48},
      {"chapter_number"=>11, "verse_count"=>30},
      {"chapter_number"=>12, "verse_count"=>25},
      {"chapter_number"=>13, "verse_count"=>52},
      {"chapter_number"=>14, "verse_count"=>28},
      {"chapter_number"=>15, "verse_count"=>40},
      {"chapter_number"=>16, "verse_count"=>40},
      {"chapter_number"=>17, "verse_count"=>34},
      {"chapter_number"=>18, "verse_count"=>28},
      {"chapter_number"=>19, "verse_count"=>41},
      {"chapter_number"=>20, "verse_count"=>38},
      {"chapter_number"=>21, "verse_count"=>40},
      {"chapter_number"=>22, "verse_count"=>30},
      {"chapter_number"=>23, "verse_count"=>35},
      {"chapter_number"=>24, "verse_count"=>26},
      {"chapter_number"=>25, "verse_count"=>27},
      {"chapter_number"=>26, "verse_count"=>32},
      {"chapter_number"=>27, "verse_count"=>44},
      {"chapter_number"=>28, "verse_count"=>30}]},
  {"number"=>45,
    "abbr"=>"ROM",
    "name"=>"Romans",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>32},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>31},
      {"chapter_number"=>4, "verse_count"=>25},
      {"chapter_number"=>5, "verse_count"=>21},
      {"chapter_number"=>6, "verse_count"=>23},
      {"chapter_number"=>7, "verse_count"=>25},
      {"chapter_number"=>8, "verse_count"=>39},
      {"chapter_number"=>9, "verse_count"=>33},
      {"chapter_number"=>10, "verse_count"=>21},
      {"chapter_number"=>11, "verse_count"=>36},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>14},
      {"chapter_number"=>14, "verse_count"=>23},
      {"chapter_number"=>15, "verse_count"=>33},
      {"chapter_number"=>16, "verse_count"=>26}]},
  {"number"=>46,
    "abbr"=>"1CO",
    "name"=>"1 Corinthians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>31},
      {"chapter_number"=>2, "verse_count"=>16},
      {"chapter_number"=>3, "verse_count"=>23},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>13},
      {"chapter_number"=>6, "verse_count"=>20},
      {"chapter_number"=>7, "verse_count"=>40},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>27},
      {"chapter_number"=>10, "verse_count"=>33},
      {"chapter_number"=>11, "verse_count"=>34},
      {"chapter_number"=>12, "verse_count"=>31},
      {"chapter_number"=>13, "verse_count"=>13},
      {"chapter_number"=>14, "verse_count"=>40},
      {"chapter_number"=>15, "verse_count"=>58},
      {"chapter_number"=>16, "verse_count"=>24}]},
  {"number"=>47,
    "abbr"=>"2CO",
    "name"=>"2 Corinthians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>24},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>18},
      {"chapter_number"=>5, "verse_count"=>21},
      {"chapter_number"=>6, "verse_count"=>18},
      {"chapter_number"=>7, "verse_count"=>16},
      {"chapter_number"=>8, "verse_count"=>24},
      {"chapter_number"=>9, "verse_count"=>15},
      {"chapter_number"=>10, "verse_count"=>18},
      {"chapter_number"=>11, "verse_count"=>33},
      {"chapter_number"=>12, "verse_count"=>21},
      {"chapter_number"=>13, "verse_count"=>14}]},
  {"number"=>48,
    "abbr"=>"GAL",
    "name"=>"Galatians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>24},
      {"chapter_number"=>2, "verse_count"=>21},
      {"chapter_number"=>3, "verse_count"=>29},
      {"chapter_number"=>4, "verse_count"=>31},
      {"chapter_number"=>5, "verse_count"=>26},
      {"chapter_number"=>6, "verse_count"=>18}]},
  {"number"=>49,
    "abbr"=>"EPH",
    "name"=>"Ephesians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>23},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>32},
      {"chapter_number"=>5, "verse_count"=>33},
      {"chapter_number"=>6, "verse_count"=>24}]},
  {"number"=>50,
    "abbr"=>"PHI",
    "name"=>"Philippians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>30},
      {"chapter_number"=>2, "verse_count"=>30},
      {"chapter_number"=>3, "verse_count"=>21},
      {"chapter_number"=>4, "verse_count"=>23}]},
  {"number"=>51,
    "abbr"=>"COL",
    "name"=>"Colossians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>29},
      {"chapter_number"=>2, "verse_count"=>23},
      {"chapter_number"=>3, "verse_count"=>25},
      {"chapter_number"=>4, "verse_count"=>18}]},
  {"number"=>52,
    "abbr"=>"1TH",
    "name"=>"1 Thessalonians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>10},
      {"chapter_number"=>2, "verse_count"=>20},
      {"chapter_number"=>3, "verse_count"=>13},
      {"chapter_number"=>4, "verse_count"=>18},
      {"chapter_number"=>5, "verse_count"=>28}]},
  {"number"=>53,
    "abbr"=>"2TH",
    "name"=>"2 Thessalonians",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>12},
      {"chapter_number"=>2, "verse_count"=>17},
      {"chapter_number"=>3, "verse_count"=>18}]},
  {"number"=>54,
    "abbr"=>"1TI",
    "name"=>"1 Timothy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>16},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>25},
      {"chapter_number"=>6, "verse_count"=>21}]},
  {"number"=>55,
    "abbr"=>"2TI",
    "name"=>"2 Timothy",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>18},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>17},
      {"chapter_number"=>4, "verse_count"=>22}]},
  {"number"=>56,
    "abbr"=>"TIT",
    "name"=>"Titus",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>16},
      {"chapter_number"=>2, "verse_count"=>15},
      {"chapter_number"=>3, "verse_count"=>15}]},
  {"number"=>57,
    "abbr"=>"PHM",
    "name"=>"Philemon",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>25}]},
  {"number"=>58,
    "abbr"=>"HEB",
    "name"=>"Hebrews",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>14},
      {"chapter_number"=>2, "verse_count"=>18},
      {"chapter_number"=>3, "verse_count"=>19},
      {"chapter_number"=>4, "verse_count"=>16},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>20},
      {"chapter_number"=>7, "verse_count"=>28},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>28},
      {"chapter_number"=>10, "verse_count"=>39},
      {"chapter_number"=>11, "verse_count"=>40},
      {"chapter_number"=>12, "verse_count"=>29},
      {"chapter_number"=>13, "verse_count"=>25}]},
  {"number"=>59,
    "abbr"=>"JAM",
    "name"=>"James",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>27},
      {"chapter_number"=>2, "verse_count"=>26},
      {"chapter_number"=>3, "verse_count"=>18},
      {"chapter_number"=>4, "verse_count"=>17},
      {"chapter_number"=>5, "verse_count"=>20}]},
  {"number"=>60,
    "abbr"=>"1PE",
    "name"=>"1 Peter",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>25},
      {"chapter_number"=>2, "verse_count"=>25},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>19},
      {"chapter_number"=>5, "verse_count"=>14}]},
  {"number"=>61,
    "abbr"=>"2PE",
    "name"=>"2 Peter",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>21},
      {"chapter_number"=>2, "verse_count"=>22},
      {"chapter_number"=>3, "verse_count"=>18}]},
  {"number"=>62,
    "abbr"=>"1JO",
    "name"=>"1 John",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>10},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>24},
      {"chapter_number"=>4, "verse_count"=>21},
      {"chapter_number"=>5, "verse_count"=>21}]},
  {"number"=>63,
    "abbr"=>"2JO",
    "name"=>"2 John",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>13}]},
  {"number"=>64,
    "abbr"=>"3JO",
    "name"=>"3 John",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>15}]},
  {"number"=>65,
    "abbr"=>"JUD",
    "name"=>"Jude",
    "chapters"=>[{"chapter_number"=>1, "verse_count"=>25}]},
  {"number"=>66,
    "abbr"=>"REV",
    "name"=>"Revelation",
    "chapters"=>
    [ {"chapter_number"=>1, "verse_count"=>20},
      {"chapter_number"=>2, "verse_count"=>29},
      {"chapter_number"=>3, "verse_count"=>22},
      {"chapter_number"=>4, "verse_count"=>11},
      {"chapter_number"=>5, "verse_count"=>14},
      {"chapter_number"=>6, "verse_count"=>17},
      {"chapter_number"=>7, "verse_count"=>17},
      {"chapter_number"=>8, "verse_count"=>13},
      {"chapter_number"=>9, "verse_count"=>21},
      {"chapter_number"=>10, "verse_count"=>11},
      {"chapter_number"=>11, "verse_count"=>19},
      {"chapter_number"=>12, "verse_count"=>17},
      {"chapter_number"=>13, "verse_count"=>18},
      {"chapter_number"=>14, "verse_count"=>20},
      {"chapter_number"=>15, "verse_count"=>8},
      {"chapter_number"=>16, "verse_count"=>21},
      {"chapter_number"=>17, "verse_count"=>18},
      {"chapter_number"=>18, "verse_count"=>24},
      {"chapter_number"=>19, "verse_count"=>21},
      {"chapter_number"=>20, "verse_count"=>15},
      {"chapter_number"=>21, "verse_count"=>27},
      {"chapter_number"=>22, "verse_count"=>21}]}]
end
