SCRIPTURE_META = [{"id"=>1,
    "abbrev"=>"GEN",
    "name"=>"Genesis",
    "chapters"=>
    [{"id"=>1, "verse_count"=>31},
      {"id"=>2, "verse_count"=>25},
      {"id"=>3, "verse_count"=>24},
      {"id"=>4, "verse_count"=>26},
      {"id"=>5, "verse_count"=>32},
      {"id"=>6, "verse_count"=>22},
      {"id"=>7, "verse_count"=>24},
      {"id"=>8, "verse_count"=>22},
      {"id"=>9, "verse_count"=>29},
      {"id"=>10, "verse_count"=>32},
      {"id"=>11, "verse_count"=>32},
      {"id"=>12, "verse_count"=>20},
      {"id"=>13, "verse_count"=>18},
      {"id"=>14, "verse_count"=>24},
      {"id"=>15, "verse_count"=>21},
      {"id"=>16, "verse_count"=>16},
      {"id"=>17, "verse_count"=>27},
      {"id"=>18, "verse_count"=>33},
      {"id"=>19, "verse_count"=>38},
      {"id"=>20, "verse_count"=>18},
      {"id"=>21, "verse_count"=>34},
      {"id"=>22, "verse_count"=>24},
      {"id"=>23, "verse_count"=>20},
      {"id"=>24, "verse_count"=>67},
      {"id"=>25, "verse_count"=>34},
      {"id"=>26, "verse_count"=>35},
      {"id"=>27, "verse_count"=>46},
      {"id"=>28, "verse_count"=>22},
      {"id"=>29, "verse_count"=>35},
      {"id"=>30, "verse_count"=>43},
      {"id"=>31, "verse_count"=>55},
      {"id"=>32, "verse_count"=>32},
      {"id"=>33, "verse_count"=>20},
      {"id"=>34, "verse_count"=>31},
      {"id"=>35, "verse_count"=>29},
      {"id"=>36, "verse_count"=>43},
      {"id"=>37, "verse_count"=>36},
      {"id"=>38, "verse_count"=>30},
      {"id"=>39, "verse_count"=>23},
      {"id"=>40, "verse_count"=>23},
      {"id"=>41, "verse_count"=>57},
      {"id"=>42, "verse_count"=>38},
      {"id"=>43, "verse_count"=>34},
      {"id"=>44, "verse_count"=>34},
      {"id"=>45, "verse_count"=>28},
      {"id"=>46, "verse_count"=>34},
      {"id"=>47, "verse_count"=>31},
      {"id"=>48, "verse_count"=>22},
      {"id"=>49, "verse_count"=>33},
      {"id"=>50, "verse_count"=>26}]},
  {"id"=>2,
    "abbrev"=>"EXO",
    "name"=>"Exodus",
    "chapters"=>
    [{"id"=>1, "verse_count"=>22},
      {"id"=>2, "verse_count"=>25},
      {"id"=>3, "verse_count"=>22},
      {"id"=>4, "verse_count"=>31},
      {"id"=>5, "verse_count"=>23},
      {"id"=>6, "verse_count"=>30},
      {"id"=>7, "verse_count"=>25},
      {"id"=>8, "verse_count"=>32},
      {"id"=>9, "verse_count"=>35},
      {"id"=>10, "verse_count"=>29},
      {"id"=>11, "verse_count"=>10},
      {"id"=>12, "verse_count"=>51},
      {"id"=>13, "verse_count"=>22},
      {"id"=>14, "verse_count"=>31},
      {"id"=>15, "verse_count"=>27},
      {"id"=>16, "verse_count"=>36},
      {"id"=>17, "verse_count"=>16},
      {"id"=>18, "verse_count"=>27},
      {"id"=>19, "verse_count"=>25},
      {"id"=>20, "verse_count"=>26},
      {"id"=>21, "verse_count"=>36},
      {"id"=>22, "verse_count"=>31},
      {"id"=>23, "verse_count"=>33},
      {"id"=>24, "verse_count"=>18},
      {"id"=>25, "verse_count"=>40},
      {"id"=>26, "verse_count"=>37},
      {"id"=>27, "verse_count"=>21},
      {"id"=>28, "verse_count"=>43},
      {"id"=>29, "verse_count"=>46},
      {"id"=>30, "verse_count"=>38},
      {"id"=>31, "verse_count"=>18},
      {"id"=>32, "verse_count"=>35},
      {"id"=>33, "verse_count"=>23},
      {"id"=>34, "verse_count"=>35},
      {"id"=>35, "verse_count"=>35},
      {"id"=>36, "verse_count"=>38},
      {"id"=>37, "verse_count"=>29},
      {"id"=>38, "verse_count"=>31},
      {"id"=>39, "verse_count"=>43},
      {"id"=>40, "verse_count"=>38}]},
  {"id"=>3,
    "abbrev"=>"LEV",
    "name"=>"Leviticus",
    "chapters"=>
    [{"id"=>1, "verse_count"=>17},
      {"id"=>2, "verse_count"=>16},
      {"id"=>3, "verse_count"=>17},
      {"id"=>4, "verse_count"=>35},
      {"id"=>5, "verse_count"=>19},
      {"id"=>6, "verse_count"=>30},
      {"id"=>7, "verse_count"=>38},
      {"id"=>8, "verse_count"=>36},
      {"id"=>9, "verse_count"=>24},
      {"id"=>10, "verse_count"=>20},
      {"id"=>11, "verse_count"=>47},
      {"id"=>12, "verse_count"=>8},
      {"id"=>13, "verse_count"=>59},
      {"id"=>14, "verse_count"=>57},
      {"id"=>15, "verse_count"=>33},
      {"id"=>16, "verse_count"=>34},
      {"id"=>17, "verse_count"=>16},
      {"id"=>18, "verse_count"=>30},
      {"id"=>19, "verse_count"=>37},
      {"id"=>20, "verse_count"=>27},
      {"id"=>21, "verse_count"=>24},
      {"id"=>22, "verse_count"=>33},
      {"id"=>23, "verse_count"=>44},
      {"id"=>24, "verse_count"=>23},
      {"id"=>25, "verse_count"=>55},
      {"id"=>26, "verse_count"=>46},
      {"id"=>27, "verse_count"=>34}]},
  {"id"=>4,
    "abbrev"=>"NUM",
    "name"=>"Numbers",
    "chapters"=>
    [{"id"=>1, "verse_count"=>54},
      {"id"=>2, "verse_count"=>34},
      {"id"=>3, "verse_count"=>51},
      {"id"=>4, "verse_count"=>49},
      {"id"=>5, "verse_count"=>31},
      {"id"=>6, "verse_count"=>27},
      {"id"=>7, "verse_count"=>89},
      {"id"=>8, "verse_count"=>26},
      {"id"=>9, "verse_count"=>23},
      {"id"=>10, "verse_count"=>36},
      {"id"=>11, "verse_count"=>35},
      {"id"=>12, "verse_count"=>16},
      {"id"=>13, "verse_count"=>33},
      {"id"=>14, "verse_count"=>45},
      {"id"=>15, "verse_count"=>41},
      {"id"=>16, "verse_count"=>50},
      {"id"=>17, "verse_count"=>13},
      {"id"=>18, "verse_count"=>32},
      {"id"=>19, "verse_count"=>22},
      {"id"=>20, "verse_count"=>29},
      {"id"=>21, "verse_count"=>35},
      {"id"=>22, "verse_count"=>41},
      {"id"=>23, "verse_count"=>30},
      {"id"=>24, "verse_count"=>25},
      {"id"=>25, "verse_count"=>18},
      {"id"=>26, "verse_count"=>65},
      {"id"=>27, "verse_count"=>23},
      {"id"=>28, "verse_count"=>31},
      {"id"=>29, "verse_count"=>40},
      {"id"=>30, "verse_count"=>16},
      {"id"=>31, "verse_count"=>54},
      {"id"=>32, "verse_count"=>42},
      {"id"=>33, "verse_count"=>56},
      {"id"=>34, "verse_count"=>29},
      {"id"=>35, "verse_count"=>34},
      {"id"=>36, "verse_count"=>13}]},
  {"id"=>5,
    "abbrev"=>"DEU",
    "name"=>"Deuteronomy",
    "chapters"=>
    [{"id"=>1, "verse_count"=>46},
      {"id"=>2, "verse_count"=>37},
      {"id"=>3, "verse_count"=>29},
      {"id"=>4, "verse_count"=>49},
      {"id"=>5, "verse_count"=>33},
      {"id"=>6, "verse_count"=>25},
      {"id"=>7, "verse_count"=>26},
      {"id"=>8, "verse_count"=>20},
      {"id"=>9, "verse_count"=>29},
      {"id"=>10, "verse_count"=>22},
      {"id"=>11, "verse_count"=>32},
      {"id"=>12, "verse_count"=>32},
      {"id"=>13, "verse_count"=>18},
      {"id"=>14, "verse_count"=>29},
      {"id"=>15, "verse_count"=>23},
      {"id"=>16, "verse_count"=>22},
      {"id"=>17, "verse_count"=>20},
      {"id"=>18, "verse_count"=>22},
      {"id"=>19, "verse_count"=>21},
      {"id"=>20, "verse_count"=>20},
      {"id"=>21, "verse_count"=>23},
      {"id"=>22, "verse_count"=>30},
      {"id"=>23, "verse_count"=>25},
      {"id"=>24, "verse_count"=>22},
      {"id"=>25, "verse_count"=>19},
      {"id"=>26, "verse_count"=>19},
      {"id"=>27, "verse_count"=>26},
      {"id"=>28, "verse_count"=>68},
      {"id"=>29, "verse_count"=>29},
      {"id"=>30, "verse_count"=>20},
      {"id"=>31, "verse_count"=>30},
      {"id"=>32, "verse_count"=>52},
      {"id"=>33, "verse_count"=>29},
      {"id"=>34, "verse_count"=>12}]},
  {"id"=>6,
    "abbrev"=>"JOS",
    "name"=>"Joshua",
    "chapters"=>
    [{"id"=>1, "verse_count"=>18},
      {"id"=>2, "verse_count"=>24},
      {"id"=>3, "verse_count"=>17},
      {"id"=>4, "verse_count"=>24},
      {"id"=>5, "verse_count"=>15},
      {"id"=>6, "verse_count"=>27},
      {"id"=>7, "verse_count"=>26},
      {"id"=>8, "verse_count"=>35},
      {"id"=>9, "verse_count"=>27},
      {"id"=>10, "verse_count"=>43},
      {"id"=>11, "verse_count"=>23},
      {"id"=>12, "verse_count"=>24},
      {"id"=>13, "verse_count"=>33},
      {"id"=>14, "verse_count"=>15},
      {"id"=>15, "verse_count"=>63},
      {"id"=>16, "verse_count"=>10},
      {"id"=>17, "verse_count"=>18},
      {"id"=>18, "verse_count"=>28},
      {"id"=>19, "verse_count"=>51},
      {"id"=>20, "verse_count"=>9},
      {"id"=>21, "verse_count"=>45},
      {"id"=>22, "verse_count"=>34},
      {"id"=>23, "verse_count"=>16},
      {"id"=>24, "verse_count"=>33}]},
  {"id"=>7,
    "abbrev"=>"JDG",
    "name"=>"Judges",
    "chapters"=>
    [{"id"=>1, "verse_count"=>36},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>31},
      {"id"=>4, "verse_count"=>24},
      {"id"=>5, "verse_count"=>31},
      {"id"=>6, "verse_count"=>40},
      {"id"=>7, "verse_count"=>25},
      {"id"=>8, "verse_count"=>35},
      {"id"=>9, "verse_count"=>57},
      {"id"=>10, "verse_count"=>18},
      {"id"=>11, "verse_count"=>40},
      {"id"=>12, "verse_count"=>15},
      {"id"=>13, "verse_count"=>25},
      {"id"=>14, "verse_count"=>20},
      {"id"=>15, "verse_count"=>20},
      {"id"=>16, "verse_count"=>31},
      {"id"=>17, "verse_count"=>13},
      {"id"=>18, "verse_count"=>31},
      {"id"=>19, "verse_count"=>30},
      {"id"=>20, "verse_count"=>48},
      {"id"=>21, "verse_count"=>25}]},
  {"id"=>8,
    "abbrev"=>"RUT",
    "name"=>"Ruth",
    "chapters"=>
    [{"id"=>1, "verse_count"=>22},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>18},
      {"id"=>4, "verse_count"=>22}]},
  {"id"=>9,
    "abbrev"=>"1SA",
    "name"=>"1 Samuel",
    "chapters"=>
    [{"id"=>1, "verse_count"=>28},
      {"id"=>2, "verse_count"=>36},
      {"id"=>3, "verse_count"=>21},
      {"id"=>4, "verse_count"=>22},
      {"id"=>5, "verse_count"=>12},
      {"id"=>6, "verse_count"=>21},
      {"id"=>7, "verse_count"=>17},
      {"id"=>8, "verse_count"=>22},
      {"id"=>9, "verse_count"=>27},
      {"id"=>10, "verse_count"=>27},
      {"id"=>11, "verse_count"=>15},
      {"id"=>12, "verse_count"=>25},
      {"id"=>13, "verse_count"=>23},
      {"id"=>14, "verse_count"=>52},
      {"id"=>15, "verse_count"=>35},
      {"id"=>16, "verse_count"=>23},
      {"id"=>17, "verse_count"=>58},
      {"id"=>18, "verse_count"=>30},
      {"id"=>19, "verse_count"=>24},
      {"id"=>20, "verse_count"=>42},
      {"id"=>21, "verse_count"=>15},
      {"id"=>22, "verse_count"=>23},
      {"id"=>23, "verse_count"=>29},
      {"id"=>24, "verse_count"=>22},
      {"id"=>25, "verse_count"=>44},
      {"id"=>26, "verse_count"=>25},
      {"id"=>27, "verse_count"=>12},
      {"id"=>28, "verse_count"=>25},
      {"id"=>29, "verse_count"=>11},
      {"id"=>30, "verse_count"=>31},
      {"id"=>31, "verse_count"=>13}]},
  {"id"=>10,
    "abbrev"=>"2SA",
    "name"=>"2 Samuel",
    "chapters"=>
    [{"id"=>1, "verse_count"=>27},
      {"id"=>2, "verse_count"=>32},
      {"id"=>3, "verse_count"=>39},
      {"id"=>4, "verse_count"=>12},
      {"id"=>5, "verse_count"=>25},
      {"id"=>6, "verse_count"=>23},
      {"id"=>7, "verse_count"=>29},
      {"id"=>8, "verse_count"=>18},
      {"id"=>9, "verse_count"=>13},
      {"id"=>10, "verse_count"=>19},
      {"id"=>11, "verse_count"=>27},
      {"id"=>12, "verse_count"=>31},
      {"id"=>13, "verse_count"=>39},
      {"id"=>14, "verse_count"=>33},
      {"id"=>15, "verse_count"=>37},
      {"id"=>16, "verse_count"=>23},
      {"id"=>17, "verse_count"=>29},
      {"id"=>18, "verse_count"=>33},
      {"id"=>19, "verse_count"=>43},
      {"id"=>20, "verse_count"=>26},
      {"id"=>21, "verse_count"=>22},
      {"id"=>22, "verse_count"=>51},
      {"id"=>23, "verse_count"=>39},
      {"id"=>24, "verse_count"=>25}]},
  {"id"=>11,
    "abbrev"=>"1KG",
    "name"=>"1 Kings",
    "chapters"=>
    [{"id"=>1, "verse_count"=>53},
      {"id"=>2, "verse_count"=>46},
      {"id"=>3, "verse_count"=>28},
      {"id"=>4, "verse_count"=>34},
      {"id"=>5, "verse_count"=>18},
      {"id"=>6, "verse_count"=>38},
      {"id"=>7, "verse_count"=>51},
      {"id"=>8, "verse_count"=>66},
      {"id"=>9, "verse_count"=>28},
      {"id"=>10, "verse_count"=>29},
      {"id"=>11, "verse_count"=>43},
      {"id"=>12, "verse_count"=>33},
      {"id"=>13, "verse_count"=>34},
      {"id"=>14, "verse_count"=>31},
      {"id"=>15, "verse_count"=>34},
      {"id"=>16, "verse_count"=>34},
      {"id"=>17, "verse_count"=>24},
      {"id"=>18, "verse_count"=>46},
      {"id"=>19, "verse_count"=>21},
      {"id"=>20, "verse_count"=>43},
      {"id"=>21, "verse_count"=>29},
      {"id"=>22, "verse_count"=>53}]},
  {"id"=>12,
    "abbrev"=>"2KG",
    "name"=>"2 Kings",
    "chapters"=>
    [{"id"=>1, "verse_count"=>18},
      {"id"=>2, "verse_count"=>25},
      {"id"=>3, "verse_count"=>27},
      {"id"=>4, "verse_count"=>44},
      {"id"=>5, "verse_count"=>27},
      {"id"=>6, "verse_count"=>33},
      {"id"=>7, "verse_count"=>20},
      {"id"=>8, "verse_count"=>29},
      {"id"=>9, "verse_count"=>37},
      {"id"=>10, "verse_count"=>36},
      {"id"=>11, "verse_count"=>21},
      {"id"=>12, "verse_count"=>21},
      {"id"=>13, "verse_count"=>25},
      {"id"=>14, "verse_count"=>29},
      {"id"=>15, "verse_count"=>38},
      {"id"=>16, "verse_count"=>20},
      {"id"=>17, "verse_count"=>41},
      {"id"=>18, "verse_count"=>37},
      {"id"=>19, "verse_count"=>37},
      {"id"=>20, "verse_count"=>21},
      {"id"=>21, "verse_count"=>26},
      {"id"=>22, "verse_count"=>20},
      {"id"=>23, "verse_count"=>37},
      {"id"=>24, "verse_count"=>20},
      {"id"=>25, "verse_count"=>30}]},
  {"id"=>13,
    "abbrev"=>"1KR",
    "name"=>"1 Chronicles",
    "chapters"=>
    [{"id"=>1, "verse_count"=>54},
      {"id"=>2, "verse_count"=>55},
      {"id"=>3, "verse_count"=>24},
      {"id"=>4, "verse_count"=>43},
      {"id"=>5, "verse_count"=>26},
      {"id"=>6, "verse_count"=>81},
      {"id"=>7, "verse_count"=>40},
      {"id"=>8, "verse_count"=>40},
      {"id"=>9, "verse_count"=>44},
      {"id"=>10, "verse_count"=>14},
      {"id"=>11, "verse_count"=>47},
      {"id"=>12, "verse_count"=>40},
      {"id"=>13, "verse_count"=>14},
      {"id"=>14, "verse_count"=>17},
      {"id"=>15, "verse_count"=>29},
      {"id"=>16, "verse_count"=>43},
      {"id"=>17, "verse_count"=>27},
      {"id"=>18, "verse_count"=>17},
      {"id"=>19, "verse_count"=>19},
      {"id"=>20, "verse_count"=>8},
      {"id"=>21, "verse_count"=>30},
      {"id"=>22, "verse_count"=>19},
      {"id"=>23, "verse_count"=>32},
      {"id"=>24, "verse_count"=>31},
      {"id"=>25, "verse_count"=>31},
      {"id"=>26, "verse_count"=>32},
      {"id"=>27, "verse_count"=>34},
      {"id"=>28, "verse_count"=>21},
      {"id"=>29, "verse_count"=>30}]},
  {"id"=>14,
    "abbrev"=>"2KR",
    "name"=>"2 Chronicles",
    "chapters"=>
    [{"id"=>1, "verse_count"=>17},
      {"id"=>2, "verse_count"=>18},
      {"id"=>3, "verse_count"=>17},
      {"id"=>4, "verse_count"=>22},
      {"id"=>5, "verse_count"=>14},
      {"id"=>6, "verse_count"=>42},
      {"id"=>7, "verse_count"=>22},
      {"id"=>8, "verse_count"=>18},
      {"id"=>9, "verse_count"=>31},
      {"id"=>10, "verse_count"=>19},
      {"id"=>11, "verse_count"=>23},
      {"id"=>12, "verse_count"=>16},
      {"id"=>13, "verse_count"=>22},
      {"id"=>14, "verse_count"=>15},
      {"id"=>15, "verse_count"=>19},
      {"id"=>16, "verse_count"=>14},
      {"id"=>17, "verse_count"=>19},
      {"id"=>18, "verse_count"=>34},
      {"id"=>19, "verse_count"=>11},
      {"id"=>20, "verse_count"=>37},
      {"id"=>21, "verse_count"=>20},
      {"id"=>22, "verse_count"=>12},
      {"id"=>23, "verse_count"=>21},
      {"id"=>24, "verse_count"=>27},
      {"id"=>25, "verse_count"=>28},
      {"id"=>26, "verse_count"=>23},
      {"id"=>27, "verse_count"=>9},
      {"id"=>28, "verse_count"=>27},
      {"id"=>29, "verse_count"=>36},
      {"id"=>30, "verse_count"=>27},
      {"id"=>31, "verse_count"=>21},
      {"id"=>32, "verse_count"=>33},
      {"id"=>33, "verse_count"=>25},
      {"id"=>34, "verse_count"=>33},
      {"id"=>35, "verse_count"=>27},
      {"id"=>36, "verse_count"=>23}]},
  {"id"=>15,
    "abbrev"=>"EZR",
    "name"=>"Ezra",
    "chapters"=>
    [{"id"=>1, "verse_count"=>11},
      {"id"=>2, "verse_count"=>70},
      {"id"=>3, "verse_count"=>13},
      {"id"=>4, "verse_count"=>24},
      {"id"=>5, "verse_count"=>17},
      {"id"=>6, "verse_count"=>22},
      {"id"=>7, "verse_count"=>28},
      {"id"=>8, "verse_count"=>36},
      {"id"=>9, "verse_count"=>15},
      {"id"=>10, "verse_count"=>44}]},
  {"id"=>16,
    "abbrev"=>"NEH",
    "name"=>"Nehemiah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>11},
      {"id"=>2, "verse_count"=>20},
      {"id"=>3, "verse_count"=>32},
      {"id"=>4, "verse_count"=>23},
      {"id"=>5, "verse_count"=>19},
      {"id"=>6, "verse_count"=>19},
      {"id"=>7, "verse_count"=>73},
      {"id"=>8, "verse_count"=>18},
      {"id"=>9, "verse_count"=>38},
      {"id"=>10, "verse_count"=>39},
      {"id"=>11, "verse_count"=>36},
      {"id"=>12, "verse_count"=>47},
      {"id"=>13, "verse_count"=>31}]},
  {"id"=>17,
    "abbrev"=>"EST",
    "name"=>"Esther",
    "chapters"=>
    [{"id"=>1, "verse_count"=>22},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>15},
      {"id"=>4, "verse_count"=>17},
      {"id"=>5, "verse_count"=>14},
      {"id"=>6, "verse_count"=>14},
      {"id"=>7, "verse_count"=>10},
      {"id"=>8, "verse_count"=>17},
      {"id"=>9, "verse_count"=>32},
      {"id"=>10, "verse_count"=>3}]},
  {"id"=>18,
    "abbrev"=>"JOB",
    "name"=>"Job",
    "chapters"=>
    [{"id"=>1, "verse_count"=>22},
      {"id"=>2, "verse_count"=>13},
      {"id"=>3, "verse_count"=>26},
      {"id"=>4, "verse_count"=>21},
      {"id"=>5, "verse_count"=>27},
      {"id"=>6, "verse_count"=>30},
      {"id"=>7, "verse_count"=>21},
      {"id"=>8, "verse_count"=>22},
      {"id"=>9, "verse_count"=>35},
      {"id"=>10, "verse_count"=>22},
      {"id"=>11, "verse_count"=>20},
      {"id"=>12, "verse_count"=>25},
      {"id"=>13, "verse_count"=>28},
      {"id"=>14, "verse_count"=>22},
      {"id"=>15, "verse_count"=>35},
      {"id"=>16, "verse_count"=>22},
      {"id"=>17, "verse_count"=>16},
      {"id"=>18, "verse_count"=>21},
      {"id"=>19, "verse_count"=>29},
      {"id"=>20, "verse_count"=>29},
      {"id"=>21, "verse_count"=>34},
      {"id"=>22, "verse_count"=>30},
      {"id"=>23, "verse_count"=>17},
      {"id"=>24, "verse_count"=>25},
      {"id"=>25, "verse_count"=>6},
      {"id"=>26, "verse_count"=>14},
      {"id"=>27, "verse_count"=>23},
      {"id"=>28, "verse_count"=>28},
      {"id"=>29, "verse_count"=>25},
      {"id"=>30, "verse_count"=>31},
      {"id"=>31, "verse_count"=>40},
      {"id"=>32, "verse_count"=>22},
      {"id"=>33, "verse_count"=>33},
      {"id"=>34, "verse_count"=>37},
      {"id"=>35, "verse_count"=>16},
      {"id"=>36, "verse_count"=>33},
      {"id"=>37, "verse_count"=>24},
      {"id"=>38, "verse_count"=>41},
      {"id"=>39, "verse_count"=>30},
      {"id"=>40, "verse_count"=>24},
      {"id"=>41, "verse_count"=>34},
      {"id"=>42, "verse_count"=>17}]},
  {"id"=>19,
    "abbrev"=>"PSA",
    "name"=>"Psalms",
    "chapters"=>
    [{"id"=>1, "verse_count"=>6},
      {"id"=>2, "verse_count"=>12},
      {"id"=>3, "verse_count"=>8},
      {"id"=>4, "verse_count"=>8},
      {"id"=>5, "verse_count"=>12},
      {"id"=>6, "verse_count"=>10},
      {"id"=>7, "verse_count"=>17},
      {"id"=>8, "verse_count"=>9},
      {"id"=>9, "verse_count"=>20},
      {"id"=>10, "verse_count"=>18},
      {"id"=>11, "verse_count"=>7},
      {"id"=>12, "verse_count"=>8},
      {"id"=>13, "verse_count"=>6},
      {"id"=>14, "verse_count"=>7},
      {"id"=>15, "verse_count"=>5},
      {"id"=>16, "verse_count"=>11},
      {"id"=>17, "verse_count"=>15},
      {"id"=>18, "verse_count"=>50},
      {"id"=>19, "verse_count"=>14},
      {"id"=>20, "verse_count"=>9},
      {"id"=>21, "verse_count"=>13},
      {"id"=>22, "verse_count"=>31},
      {"id"=>23, "verse_count"=>6},
      {"id"=>24, "verse_count"=>10},
      {"id"=>25, "verse_count"=>22},
      {"id"=>26, "verse_count"=>12},
      {"id"=>27, "verse_count"=>14},
      {"id"=>28, "verse_count"=>9},
      {"id"=>29, "verse_count"=>11},
      {"id"=>30, "verse_count"=>12},
      {"id"=>31, "verse_count"=>24},
      {"id"=>32, "verse_count"=>11},
      {"id"=>33, "verse_count"=>22},
      {"id"=>34, "verse_count"=>22},
      {"id"=>35, "verse_count"=>28},
      {"id"=>36, "verse_count"=>12},
      {"id"=>37, "verse_count"=>40},
      {"id"=>38, "verse_count"=>22},
      {"id"=>39, "verse_count"=>13},
      {"id"=>40, "verse_count"=>17},
      {"id"=>41, "verse_count"=>13},
      {"id"=>42, "verse_count"=>11},
      {"id"=>43, "verse_count"=>5},
      {"id"=>44, "verse_count"=>26},
      {"id"=>45, "verse_count"=>17},
      {"id"=>46, "verse_count"=>11},
      {"id"=>47, "verse_count"=>9},
      {"id"=>48, "verse_count"=>14},
      {"id"=>49, "verse_count"=>20},
      {"id"=>50, "verse_count"=>23},
      {"id"=>51, "verse_count"=>19},
      {"id"=>52, "verse_count"=>9},
      {"id"=>53, "verse_count"=>6},
      {"id"=>54, "verse_count"=>7},
      {"id"=>55, "verse_count"=>23},
      {"id"=>56, "verse_count"=>13},
      {"id"=>57, "verse_count"=>11},
      {"id"=>58, "verse_count"=>11},
      {"id"=>59, "verse_count"=>17},
      {"id"=>60, "verse_count"=>12},
      {"id"=>61, "verse_count"=>8},
      {"id"=>62, "verse_count"=>12},
      {"id"=>63, "verse_count"=>11},
      {"id"=>64, "verse_count"=>10},
      {"id"=>65, "verse_count"=>13},
      {"id"=>66, "verse_count"=>20},
      {"id"=>67, "verse_count"=>7},
      {"id"=>68, "verse_count"=>35},
      {"id"=>69, "verse_count"=>36},
      {"id"=>70, "verse_count"=>5},
      {"id"=>71, "verse_count"=>24},
      {"id"=>72, "verse_count"=>20},
      {"id"=>73, "verse_count"=>28},
      {"id"=>74, "verse_count"=>23},
      {"id"=>75, "verse_count"=>10},
      {"id"=>76, "verse_count"=>12},
      {"id"=>77, "verse_count"=>20},
      {"id"=>78, "verse_count"=>72},
      {"id"=>79, "verse_count"=>13},
      {"id"=>80, "verse_count"=>19},
      {"id"=>81, "verse_count"=>16},
      {"id"=>82, "verse_count"=>8},
      {"id"=>83, "verse_count"=>18},
      {"id"=>84, "verse_count"=>12},
      {"id"=>85, "verse_count"=>13},
      {"id"=>86, "verse_count"=>17},
      {"id"=>87, "verse_count"=>7},
      {"id"=>88, "verse_count"=>18},
      {"id"=>89, "verse_count"=>52},
      {"id"=>90, "verse_count"=>17},
      {"id"=>91, "verse_count"=>16},
      {"id"=>92, "verse_count"=>15},
      {"id"=>93, "verse_count"=>5},
      {"id"=>94, "verse_count"=>23},
      {"id"=>95, "verse_count"=>11},
      {"id"=>96, "verse_count"=>13},
      {"id"=>97, "verse_count"=>12},
      {"id"=>98, "verse_count"=>9},
      {"id"=>99, "verse_count"=>9},
      {"id"=>100, "verse_count"=>5},
      {"id"=>101, "verse_count"=>8},
      {"id"=>102, "verse_count"=>28},
      {"id"=>103, "verse_count"=>22},
      {"id"=>104, "verse_count"=>35},
      {"id"=>105, "verse_count"=>45},
      {"id"=>106, "verse_count"=>48},
      {"id"=>107, "verse_count"=>43},
      {"id"=>108, "verse_count"=>13},
      {"id"=>109, "verse_count"=>31},
      {"id"=>110, "verse_count"=>7},
      {"id"=>111, "verse_count"=>10},
      {"id"=>112, "verse_count"=>10},
      {"id"=>113, "verse_count"=>9},
      {"id"=>114, "verse_count"=>8},
      {"id"=>115, "verse_count"=>18},
      {"id"=>116, "verse_count"=>19},
      {"id"=>117, "verse_count"=>2},
      {"id"=>118, "verse_count"=>29},
      {"id"=>119, "verse_count"=>176},
      {"id"=>120, "verse_count"=>7},
      {"id"=>121, "verse_count"=>8},
      {"id"=>122, "verse_count"=>9},
      {"id"=>123, "verse_count"=>4},
      {"id"=>124, "verse_count"=>8},
      {"id"=>125, "verse_count"=>5},
      {"id"=>126, "verse_count"=>6},
      {"id"=>127, "verse_count"=>5},
      {"id"=>128, "verse_count"=>6},
      {"id"=>129, "verse_count"=>8},
      {"id"=>130, "verse_count"=>8},
      {"id"=>131, "verse_count"=>3},
      {"id"=>132, "verse_count"=>18},
      {"id"=>133, "verse_count"=>3},
      {"id"=>134, "verse_count"=>3},
      {"id"=>135, "verse_count"=>21},
      {"id"=>136, "verse_count"=>26},
      {"id"=>137, "verse_count"=>9},
      {"id"=>138, "verse_count"=>8},
      {"id"=>139, "verse_count"=>24},
      {"id"=>140, "verse_count"=>13},
      {"id"=>141, "verse_count"=>10},
      {"id"=>142, "verse_count"=>7},
      {"id"=>143, "verse_count"=>12},
      {"id"=>144, "verse_count"=>15},
      {"id"=>145, "verse_count"=>21},
      {"id"=>146, "verse_count"=>10},
      {"id"=>147, "verse_count"=>20},
      {"id"=>148, "verse_count"=>14},
      {"id"=>149, "verse_count"=>9},
      {"id"=>150, "verse_count"=>6}]},
  {"id"=>20,
    "abbrev"=>"PRO",
    "name"=>"Proverbs",
    "chapters"=>
    [{"id"=>1, "verse_count"=>33},
      {"id"=>2, "verse_count"=>22},
      {"id"=>3, "verse_count"=>35},
      {"id"=>4, "verse_count"=>27},
      {"id"=>5, "verse_count"=>23},
      {"id"=>6, "verse_count"=>35},
      {"id"=>7, "verse_count"=>27},
      {"id"=>8, "verse_count"=>36},
      {"id"=>9, "verse_count"=>18},
      {"id"=>10, "verse_count"=>32},
      {"id"=>11, "verse_count"=>31},
      {"id"=>12, "verse_count"=>28},
      {"id"=>13, "verse_count"=>25},
      {"id"=>14, "verse_count"=>35},
      {"id"=>15, "verse_count"=>33},
      {"id"=>16, "verse_count"=>33},
      {"id"=>17, "verse_count"=>28},
      {"id"=>18, "verse_count"=>24},
      {"id"=>19, "verse_count"=>29},
      {"id"=>20, "verse_count"=>30},
      {"id"=>21, "verse_count"=>31},
      {"id"=>22, "verse_count"=>29},
      {"id"=>23, "verse_count"=>35},
      {"id"=>24, "verse_count"=>34},
      {"id"=>25, "verse_count"=>28},
      {"id"=>26, "verse_count"=>28},
      {"id"=>27, "verse_count"=>27},
      {"id"=>28, "verse_count"=>28},
      {"id"=>29, "verse_count"=>27},
      {"id"=>30, "verse_count"=>33},
      {"id"=>31, "verse_count"=>31}]},
  {"id"=>21,
    "abbrev"=>"ECC",
    "name"=>"Ecclesiastes",
    "chapters"=>
    [{"id"=>1, "verse_count"=>18},
      {"id"=>2, "verse_count"=>26},
      {"id"=>3, "verse_count"=>22},
      {"id"=>4, "verse_count"=>16},
      {"id"=>5, "verse_count"=>20},
      {"id"=>6, "verse_count"=>12},
      {"id"=>7, "verse_count"=>29},
      {"id"=>8, "verse_count"=>17},
      {"id"=>9, "verse_count"=>18},
      {"id"=>10, "verse_count"=>20},
      {"id"=>11, "verse_count"=>10},
      {"id"=>12, "verse_count"=>14}]},
  {"id"=>22,
    "abbrev"=>"SO",
    "name"=>"Song",
    "chapters"=>
    [{"id"=>1, "verse_count"=>17},
      {"id"=>2, "verse_count"=>17},
      {"id"=>3, "verse_count"=>11},
      {"id"=>4, "verse_count"=>16},
      {"id"=>5, "verse_count"=>16},
      {"id"=>6, "verse_count"=>13},
      {"id"=>7, "verse_count"=>13},
      {"id"=>8, "verse_count"=>14}]},
  {"id"=>23,
    "abbrev"=>"ISA",
    "name"=>"Isaiah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>31},
      {"id"=>2, "verse_count"=>22},
      {"id"=>3, "verse_count"=>26},
      {"id"=>4, "verse_count"=>6},
      {"id"=>5, "verse_count"=>30},
      {"id"=>6, "verse_count"=>13},
      {"id"=>7, "verse_count"=>25},
      {"id"=>8, "verse_count"=>22},
      {"id"=>9, "verse_count"=>21},
      {"id"=>10, "verse_count"=>34},
      {"id"=>11, "verse_count"=>16},
      {"id"=>12, "verse_count"=>6},
      {"id"=>13, "verse_count"=>22},
      {"id"=>14, "verse_count"=>32},
      {"id"=>15, "verse_count"=>9},
      {"id"=>16, "verse_count"=>14},
      {"id"=>17, "verse_count"=>14},
      {"id"=>18, "verse_count"=>7},
      {"id"=>19, "verse_count"=>25},
      {"id"=>20, "verse_count"=>6},
      {"id"=>21, "verse_count"=>17},
      {"id"=>22, "verse_count"=>25},
      {"id"=>23, "verse_count"=>18},
      {"id"=>24, "verse_count"=>23},
      {"id"=>25, "verse_count"=>12},
      {"id"=>26, "verse_count"=>21},
      {"id"=>27, "verse_count"=>13},
      {"id"=>28, "verse_count"=>29},
      {"id"=>29, "verse_count"=>24},
      {"id"=>30, "verse_count"=>33},
      {"id"=>31, "verse_count"=>9},
      {"id"=>32, "verse_count"=>20},
      {"id"=>33, "verse_count"=>24},
      {"id"=>34, "verse_count"=>17},
      {"id"=>35, "verse_count"=>10},
      {"id"=>36, "verse_count"=>22},
      {"id"=>37, "verse_count"=>38},
      {"id"=>38, "verse_count"=>22},
      {"id"=>39, "verse_count"=>8},
      {"id"=>40, "verse_count"=>31},
      {"id"=>41, "verse_count"=>29},
      {"id"=>42, "verse_count"=>25},
      {"id"=>43, "verse_count"=>28},
      {"id"=>44, "verse_count"=>28},
      {"id"=>45, "verse_count"=>25},
      {"id"=>46, "verse_count"=>13},
      {"id"=>47, "verse_count"=>15},
      {"id"=>48, "verse_count"=>22},
      {"id"=>49, "verse_count"=>26},
      {"id"=>50, "verse_count"=>11},
      {"id"=>51, "verse_count"=>23},
      {"id"=>52, "verse_count"=>15},
      {"id"=>53, "verse_count"=>12},
      {"id"=>54, "verse_count"=>17},
      {"id"=>55, "verse_count"=>13},
      {"id"=>56, "verse_count"=>12},
      {"id"=>57, "verse_count"=>21},
      {"id"=>58, "verse_count"=>14},
      {"id"=>59, "verse_count"=>21},
      {"id"=>60, "verse_count"=>22},
      {"id"=>61, "verse_count"=>11},
      {"id"=>62, "verse_count"=>12},
      {"id"=>63, "verse_count"=>19},
      {"id"=>64, "verse_count"=>12},
      {"id"=>65, "verse_count"=>25},
      {"id"=>66, "verse_count"=>24}]},
  {"id"=>24,
    "abbrev"=>"JER",
    "name"=>"Jeremiah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>19},
      {"id"=>2, "verse_count"=>37},
      {"id"=>3, "verse_count"=>25},
      {"id"=>4, "verse_count"=>31},
      {"id"=>5, "verse_count"=>31},
      {"id"=>6, "verse_count"=>30},
      {"id"=>7, "verse_count"=>34},
      {"id"=>8, "verse_count"=>22},
      {"id"=>9, "verse_count"=>26},
      {"id"=>10, "verse_count"=>25},
      {"id"=>11, "verse_count"=>23},
      {"id"=>12, "verse_count"=>17},
      {"id"=>13, "verse_count"=>27},
      {"id"=>14, "verse_count"=>22},
      {"id"=>15, "verse_count"=>21},
      {"id"=>16, "verse_count"=>21},
      {"id"=>17, "verse_count"=>27},
      {"id"=>18, "verse_count"=>23},
      {"id"=>19, "verse_count"=>15},
      {"id"=>20, "verse_count"=>18},
      {"id"=>21, "verse_count"=>14},
      {"id"=>22, "verse_count"=>30},
      {"id"=>23, "verse_count"=>40},
      {"id"=>24, "verse_count"=>10},
      {"id"=>25, "verse_count"=>38},
      {"id"=>26, "verse_count"=>24},
      {"id"=>27, "verse_count"=>22},
      {"id"=>28, "verse_count"=>17},
      {"id"=>29, "verse_count"=>32},
      {"id"=>30, "verse_count"=>24},
      {"id"=>31, "verse_count"=>40},
      {"id"=>32, "verse_count"=>44},
      {"id"=>33, "verse_count"=>26},
      {"id"=>34, "verse_count"=>22},
      {"id"=>35, "verse_count"=>19},
      {"id"=>36, "verse_count"=>32},
      {"id"=>37, "verse_count"=>21},
      {"id"=>38, "verse_count"=>28},
      {"id"=>39, "verse_count"=>18},
      {"id"=>40, "verse_count"=>16},
      {"id"=>41, "verse_count"=>18},
      {"id"=>42, "verse_count"=>22},
      {"id"=>43, "verse_count"=>13},
      {"id"=>44, "verse_count"=>30},
      {"id"=>45, "verse_count"=>5},
      {"id"=>46, "verse_count"=>28},
      {"id"=>47, "verse_count"=>7},
      {"id"=>48, "verse_count"=>47},
      {"id"=>49, "verse_count"=>39},
      {"id"=>50, "verse_count"=>46},
      {"id"=>51, "verse_count"=>64},
      {"id"=>52, "verse_count"=>34}]},
  {"id"=>25,
    "abbrev"=>"LAM",
    "name"=>"Lamentations",
    "chapters"=>
    [{"id"=>1, "verse_count"=>22},
      {"id"=>2, "verse_count"=>22},
      {"id"=>3, "verse_count"=>66},
      {"id"=>4, "verse_count"=>22},
      {"id"=>5, "verse_count"=>22}]},
  {"id"=>26,
    "abbrev"=>"EZE",
    "name"=>"Ezekiel",
    "chapters"=>
    [{"id"=>1, "verse_count"=>28},
      {"id"=>2, "verse_count"=>10},
      {"id"=>3, "verse_count"=>27},
      {"id"=>4, "verse_count"=>17},
      {"id"=>5, "verse_count"=>17},
      {"id"=>6, "verse_count"=>14},
      {"id"=>7, "verse_count"=>27},
      {"id"=>8, "verse_count"=>18},
      {"id"=>9, "verse_count"=>11},
      {"id"=>10, "verse_count"=>22},
      {"id"=>11, "verse_count"=>25},
      {"id"=>12, "verse_count"=>28},
      {"id"=>13, "verse_count"=>23},
      {"id"=>14, "verse_count"=>23},
      {"id"=>15, "verse_count"=>8},
      {"id"=>16, "verse_count"=>63},
      {"id"=>17, "verse_count"=>24},
      {"id"=>18, "verse_count"=>32},
      {"id"=>19, "verse_count"=>14},
      {"id"=>20, "verse_count"=>49},
      {"id"=>21, "verse_count"=>32},
      {"id"=>22, "verse_count"=>31},
      {"id"=>23, "verse_count"=>49},
      {"id"=>24, "verse_count"=>27},
      {"id"=>25, "verse_count"=>17},
      {"id"=>26, "verse_count"=>21},
      {"id"=>27, "verse_count"=>36},
      {"id"=>28, "verse_count"=>26},
      {"id"=>29, "verse_count"=>21},
      {"id"=>30, "verse_count"=>26},
      {"id"=>31, "verse_count"=>18},
      {"id"=>32, "verse_count"=>32},
      {"id"=>33, "verse_count"=>33},
      {"id"=>34, "verse_count"=>31},
      {"id"=>35, "verse_count"=>15},
      {"id"=>36, "verse_count"=>38},
      {"id"=>37, "verse_count"=>28},
      {"id"=>38, "verse_count"=>23},
      {"id"=>39, "verse_count"=>29},
      {"id"=>40, "verse_count"=>49},
      {"id"=>41, "verse_count"=>26},
      {"id"=>42, "verse_count"=>20},
      {"id"=>43, "verse_count"=>27},
      {"id"=>44, "verse_count"=>31},
      {"id"=>45, "verse_count"=>25},
      {"id"=>46, "verse_count"=>24},
      {"id"=>47, "verse_count"=>23},
      {"id"=>48, "verse_count"=>35}]},
  {"id"=>27,
    "abbrev"=>"DAN",
    "name"=>"Daniel",
    "chapters"=>
    [{"id"=>1, "verse_count"=>21},
      {"id"=>2, "verse_count"=>49},
      {"id"=>3, "verse_count"=>30},
      {"id"=>4, "verse_count"=>37},
      {"id"=>5, "verse_count"=>31},
      {"id"=>6, "verse_count"=>28},
      {"id"=>7, "verse_count"=>28},
      {"id"=>8, "verse_count"=>27},
      {"id"=>9, "verse_count"=>27},
      {"id"=>10, "verse_count"=>21},
      {"id"=>11, "verse_count"=>45},
      {"id"=>12, "verse_count"=>13}]},
  {"id"=>28,
    "abbrev"=>"HOS",
    "name"=>"Hosea",
    "chapters"=>
    [{"id"=>1, "verse_count"=>11},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>5},
      {"id"=>4, "verse_count"=>19},
      {"id"=>5, "verse_count"=>15},
      {"id"=>6, "verse_count"=>11},
      {"id"=>7, "verse_count"=>16},
      {"id"=>8, "verse_count"=>14},
      {"id"=>9, "verse_count"=>17},
      {"id"=>10, "verse_count"=>15},
      {"id"=>11, "verse_count"=>12},
      {"id"=>12, "verse_count"=>14},
      {"id"=>13, "verse_count"=>16},
      {"id"=>14, "verse_count"=>9}]},
  {"id"=>29,
    "abbrev"=>"JOE",
    "name"=>"Joel",
    "chapters"=>
    [{"id"=>1, "verse_count"=>20},
      {"id"=>2, "verse_count"=>32},
      {"id"=>3, "verse_count"=>21}]},
  {"id"=>30,
    "abbrev"=>"AMO",
    "name"=>"Amos",
    "chapters"=>
    [{"id"=>1, "verse_count"=>15},
      {"id"=>2, "verse_count"=>16},
      {"id"=>3, "verse_count"=>15},
      {"id"=>4, "verse_count"=>13},
      {"id"=>5, "verse_count"=>27},
      {"id"=>6, "verse_count"=>14},
      {"id"=>7, "verse_count"=>17},
      {"id"=>8, "verse_count"=>14},
      {"id"=>9, "verse_count"=>15}]},
  {"id"=>31,
    "abbrev"=>"OBA",
    "name"=>"Obadiah",
    "chapters"=>[{"id"=>1, "verse_count"=>21}]},
  {"id"=>32,
    "abbrev"=>"JON",
    "name"=>"Jonah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>17},
      {"id"=>2, "verse_count"=>10},
      {"id"=>3, "verse_count"=>10},
      {"id"=>4, "verse_count"=>11}]},
  {"id"=>33,
    "abbrev"=>"MIC",
    "name"=>"Micah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>16},
      {"id"=>2, "verse_count"=>13},
      {"id"=>3, "verse_count"=>12},
      {"id"=>4, "verse_count"=>13},
      {"id"=>5, "verse_count"=>15},
      {"id"=>6, "verse_count"=>16},
      {"id"=>7, "verse_count"=>20}]},
  {"id"=>34,
    "abbrev"=>"NAH",
    "name"=>"Nahum",
    "chapters"=>
    [{"id"=>1, "verse_count"=>15},
      {"id"=>2, "verse_count"=>13},
      {"id"=>3, "verse_count"=>19}]},
  {"id"=>35,
    "abbrev"=>"HAB",
    "name"=>"Habakkuk",
    "chapters"=>
    [{"id"=>1, "verse_count"=>17},
      {"id"=>2, "verse_count"=>20},
      {"id"=>3, "verse_count"=>19}]},
  {"id"=>36,
    "abbrev"=>"ZEP",
    "name"=>"Zephaniah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>18},
      {"id"=>2, "verse_count"=>15},
      {"id"=>3, "verse_count"=>20}]},
  {"id"=>37,
    "abbrev"=>"HAG",
    "name"=>"Haggai",
    "chapters"=>
    [{"id"=>1, "verse_count"=>15}, {"id"=>2, "verse_count"=>23}]},
  {"id"=>38,
    "abbrev"=>"ZEC",
    "name"=>"Zechariah",
    "chapters"=>
    [{"id"=>1, "verse_count"=>21},
      {"id"=>2, "verse_count"=>13},
      {"id"=>3, "verse_count"=>10},
      {"id"=>4, "verse_count"=>14},
      {"id"=>5, "verse_count"=>11},
      {"id"=>6, "verse_count"=>15},
      {"id"=>7, "verse_count"=>14},
      {"id"=>8, "verse_count"=>23},
      {"id"=>9, "verse_count"=>17},
      {"id"=>10, "verse_count"=>12},
      {"id"=>11, "verse_count"=>17},
      {"id"=>12, "verse_count"=>14},
      {"id"=>13, "verse_count"=>9},
      {"id"=>14, "verse_count"=>21}]},
  {"id"=>39,
    "abbrev"=>"MAL",
    "name"=>"Malachi",
    "chapters"=>
    [{"id"=>1, "verse_count"=>14},
      {"id"=>2, "verse_count"=>17},
      {"id"=>3, "verse_count"=>18},
      {"id"=>4, "verse_count"=>6}]},
  {"id"=>40,
    "abbrev"=>"MAT",
    "name"=>"Matthew",
    "chapters"=>
    [{"id"=>1, "verse_count"=>25},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>17},
      {"id"=>4, "verse_count"=>25},
      {"id"=>5, "verse_count"=>48},
      {"id"=>6, "verse_count"=>34},
      {"id"=>7, "verse_count"=>29},
      {"id"=>8, "verse_count"=>34},
      {"id"=>9, "verse_count"=>38},
      {"id"=>10, "verse_count"=>42},
      {"id"=>11, "verse_count"=>30},
      {"id"=>12, "verse_count"=>49},
      {"id"=>13, "verse_count"=>58},
      {"id"=>14, "verse_count"=>36},
      {"id"=>15, "verse_count"=>39},
      {"id"=>16, "verse_count"=>28},
      {"id"=>17, "verse_count"=>26},
      {"id"=>18, "verse_count"=>34},
      {"id"=>19, "verse_count"=>30},
      {"id"=>20, "verse_count"=>34},
      {"id"=>21, "verse_count"=>46},
      {"id"=>22, "verse_count"=>46},
      {"id"=>23, "verse_count"=>38},
      {"id"=>24, "verse_count"=>51},
      {"id"=>25, "verse_count"=>46},
      {"id"=>26, "verse_count"=>75},
      {"id"=>27, "verse_count"=>66},
      {"id"=>28, "verse_count"=>20}]},
  {"id"=>41,
    "abbrev"=>"MAR",
    "name"=>"Mark",
    "chapters"=>
    [{"id"=>1, "verse_count"=>45},
      {"id"=>2, "verse_count"=>28},
      {"id"=>3, "verse_count"=>35},
      {"id"=>4, "verse_count"=>41},
      {"id"=>5, "verse_count"=>43},
      {"id"=>6, "verse_count"=>56},
      {"id"=>7, "verse_count"=>36},
      {"id"=>8, "verse_count"=>38},
      {"id"=>9, "verse_count"=>48},
      {"id"=>10, "verse_count"=>52},
      {"id"=>11, "verse_count"=>32},
      {"id"=>12, "verse_count"=>44},
      {"id"=>13, "verse_count"=>37},
      {"id"=>14, "verse_count"=>72},
      {"id"=>15, "verse_count"=>46},
      {"id"=>16, "verse_count"=>20}]},
  {"id"=>42,
    "abbrev"=>"LUK",
    "name"=>"Luke",
    "chapters"=>
    [{"id"=>1, "verse_count"=>80},
      {"id"=>2, "verse_count"=>52},
      {"id"=>3, "verse_count"=>38},
      {"id"=>4, "verse_count"=>44},
      {"id"=>5, "verse_count"=>39},
      {"id"=>6, "verse_count"=>49},
      {"id"=>7, "verse_count"=>50},
      {"id"=>8, "verse_count"=>56},
      {"id"=>9, "verse_count"=>62},
      {"id"=>10, "verse_count"=>42},
      {"id"=>11, "verse_count"=>54},
      {"id"=>12, "verse_count"=>59},
      {"id"=>13, "verse_count"=>35},
      {"id"=>14, "verse_count"=>35},
      {"id"=>15, "verse_count"=>32},
      {"id"=>16, "verse_count"=>31},
      {"id"=>17, "verse_count"=>36},
      {"id"=>18, "verse_count"=>43},
      {"id"=>19, "verse_count"=>48},
      {"id"=>20, "verse_count"=>47},
      {"id"=>21, "verse_count"=>38},
      {"id"=>22, "verse_count"=>71},
      {"id"=>23, "verse_count"=>55},
      {"id"=>24, "verse_count"=>53}]},
  {"id"=>43,
    "abbrev"=>"JOH",
    "name"=>"John",
    "chapters"=>
    [{"id"=>1, "verse_count"=>51},
      {"id"=>2, "verse_count"=>25},
      {"id"=>3, "verse_count"=>36},
      {"id"=>4, "verse_count"=>54},
      {"id"=>5, "verse_count"=>46},
      {"id"=>6, "verse_count"=>71},
      {"id"=>7, "verse_count"=>53},
      {"id"=>8, "verse_count"=>59},
      {"id"=>9, "verse_count"=>41},
      {"id"=>10, "verse_count"=>42},
      {"id"=>11, "verse_count"=>57},
      {"id"=>12, "verse_count"=>50},
      {"id"=>13, "verse_count"=>38},
      {"id"=>14, "verse_count"=>31},
      {"id"=>15, "verse_count"=>27},
      {"id"=>16, "verse_count"=>33},
      {"id"=>17, "verse_count"=>26},
      {"id"=>18, "verse_count"=>40},
      {"id"=>19, "verse_count"=>42},
      {"id"=>20, "verse_count"=>31},
      {"id"=>21, "verse_count"=>25}]},
  {"id"=>44,
    "abbrev"=>"ACT",
    "name"=>"Acts",
    "chapters"=>
    [{"id"=>1, "verse_count"=>26},
      {"id"=>2, "verse_count"=>47},
      {"id"=>3, "verse_count"=>26},
      {"id"=>4, "verse_count"=>37},
      {"id"=>5, "verse_count"=>42},
      {"id"=>6, "verse_count"=>15},
      {"id"=>7, "verse_count"=>60},
      {"id"=>8, "verse_count"=>39},
      {"id"=>9, "verse_count"=>43},
      {"id"=>10, "verse_count"=>48},
      {"id"=>11, "verse_count"=>30},
      {"id"=>12, "verse_count"=>25},
      {"id"=>13, "verse_count"=>52},
      {"id"=>14, "verse_count"=>28},
      {"id"=>15, "verse_count"=>40},
      {"id"=>16, "verse_count"=>40},
      {"id"=>17, "verse_count"=>34},
      {"id"=>18, "verse_count"=>28},
      {"id"=>19, "verse_count"=>41},
      {"id"=>20, "verse_count"=>38},
      {"id"=>21, "verse_count"=>40},
      {"id"=>22, "verse_count"=>30},
      {"id"=>23, "verse_count"=>35},
      {"id"=>24, "verse_count"=>26},
      {"id"=>25, "verse_count"=>27},
      {"id"=>26, "verse_count"=>32},
      {"id"=>27, "verse_count"=>44},
      {"id"=>28, "verse_count"=>30}]},
  {"id"=>45,
    "abbrev"=>"ROM",
    "name"=>"Romans",
    "chapters"=>
    [{"id"=>1, "verse_count"=>32},
      {"id"=>2, "verse_count"=>29},
      {"id"=>3, "verse_count"=>31},
      {"id"=>4, "verse_count"=>25},
      {"id"=>5, "verse_count"=>21},
      {"id"=>6, "verse_count"=>23},
      {"id"=>7, "verse_count"=>25},
      {"id"=>8, "verse_count"=>39},
      {"id"=>9, "verse_count"=>33},
      {"id"=>10, "verse_count"=>21},
      {"id"=>11, "verse_count"=>36},
      {"id"=>12, "verse_count"=>21},
      {"id"=>13, "verse_count"=>14},
      {"id"=>14, "verse_count"=>23},
      {"id"=>15, "verse_count"=>33},
      {"id"=>16, "verse_count"=>26}]},
  {"id"=>46,
    "abbrev"=>"1CO",
    "name"=>"1 Corinthians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>31},
      {"id"=>2, "verse_count"=>16},
      {"id"=>3, "verse_count"=>23},
      {"id"=>4, "verse_count"=>21},
      {"id"=>5, "verse_count"=>13},
      {"id"=>6, "verse_count"=>20},
      {"id"=>7, "verse_count"=>40},
      {"id"=>8, "verse_count"=>13},
      {"id"=>9, "verse_count"=>27},
      {"id"=>10, "verse_count"=>33},
      {"id"=>11, "verse_count"=>34},
      {"id"=>12, "verse_count"=>31},
      {"id"=>13, "verse_count"=>13},
      {"id"=>14, "verse_count"=>40},
      {"id"=>15, "verse_count"=>58},
      {"id"=>16, "verse_count"=>24}]},
  {"id"=>47,
    "abbrev"=>"2CO",
    "name"=>"2 Corinthians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>24},
      {"id"=>2, "verse_count"=>17},
      {"id"=>3, "verse_count"=>18},
      {"id"=>4, "verse_count"=>18},
      {"id"=>5, "verse_count"=>21},
      {"id"=>6, "verse_count"=>18},
      {"id"=>7, "verse_count"=>16},
      {"id"=>8, "verse_count"=>24},
      {"id"=>9, "verse_count"=>15},
      {"id"=>10, "verse_count"=>18},
      {"id"=>11, "verse_count"=>33},
      {"id"=>12, "verse_count"=>21},
      {"id"=>13, "verse_count"=>14}]},
  {"id"=>48,
    "abbrev"=>"GAL",
    "name"=>"Galatians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>24},
      {"id"=>2, "verse_count"=>21},
      {"id"=>3, "verse_count"=>29},
      {"id"=>4, "verse_count"=>31},
      {"id"=>5, "verse_count"=>26},
      {"id"=>6, "verse_count"=>18}]},
  {"id"=>49,
    "abbrev"=>"EPH",
    "name"=>"Ephesians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>23},
      {"id"=>2, "verse_count"=>22},
      {"id"=>3, "verse_count"=>21},
      {"id"=>4, "verse_count"=>32},
      {"id"=>5, "verse_count"=>33},
      {"id"=>6, "verse_count"=>24}]},
  {"id"=>50,
    "abbrev"=>"PHI",
    "name"=>"Philippians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>30},
      {"id"=>2, "verse_count"=>30},
      {"id"=>3, "verse_count"=>21},
      {"id"=>4, "verse_count"=>23}]},
  {"id"=>51,
    "abbrev"=>"COL",
    "name"=>"Colossians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>29},
      {"id"=>2, "verse_count"=>23},
      {"id"=>3, "verse_count"=>25},
      {"id"=>4, "verse_count"=>18}]},
  {"id"=>52,
    "abbrev"=>"1TH",
    "name"=>"1 Thessalonians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>10},
      {"id"=>2, "verse_count"=>20},
      {"id"=>3, "verse_count"=>13},
      {"id"=>4, "verse_count"=>18},
      {"id"=>5, "verse_count"=>28}]},
  {"id"=>53,
    "abbrev"=>"2TH",
    "name"=>"2 Thessalonians",
    "chapters"=>
    [{"id"=>1, "verse_count"=>12},
      {"id"=>2, "verse_count"=>17},
      {"id"=>3, "verse_count"=>18}]},
  {"id"=>54,
    "abbrev"=>"1TI",
    "name"=>"1 Timothy",
    "chapters"=>
    [{"id"=>1, "verse_count"=>20},
      {"id"=>2, "verse_count"=>15},
      {"id"=>3, "verse_count"=>16},
      {"id"=>4, "verse_count"=>16},
      {"id"=>5, "verse_count"=>25},
      {"id"=>6, "verse_count"=>21}]},
  {"id"=>55,
    "abbrev"=>"2TI",
    "name"=>"2 Timothy",
    "chapters"=>
    [{"id"=>1, "verse_count"=>18},
      {"id"=>2, "verse_count"=>26},
      {"id"=>3, "verse_count"=>17},
      {"id"=>4, "verse_count"=>22}]},
  {"id"=>56,
    "abbrev"=>"TIT",
    "name"=>"Titus",
    "chapters"=>
    [{"id"=>1, "verse_count"=>16},
      {"id"=>2, "verse_count"=>15},
      {"id"=>3, "verse_count"=>15}]},
  {"id"=>57,
    "abbrev"=>"PHM",
    "name"=>"Philemon",
    "chapters"=>[{"id"=>1, "verse_count"=>25}]},
  {"id"=>58,
    "abbrev"=>"HEB",
    "name"=>"Hebrews",
    "chapters"=>
    [{"id"=>1, "verse_count"=>14},
      {"id"=>2, "verse_count"=>18},
      {"id"=>3, "verse_count"=>19},
      {"id"=>4, "verse_count"=>16},
      {"id"=>5, "verse_count"=>14},
      {"id"=>6, "verse_count"=>20},
      {"id"=>7, "verse_count"=>28},
      {"id"=>8, "verse_count"=>13},
      {"id"=>9, "verse_count"=>28},
      {"id"=>10, "verse_count"=>39},
      {"id"=>11, "verse_count"=>40},
      {"id"=>12, "verse_count"=>29},
      {"id"=>13, "verse_count"=>25}]},
  {"id"=>59,
    "abbrev"=>"JAM",
    "name"=>"James",
    "chapters"=>
    [{"id"=>1, "verse_count"=>27},
      {"id"=>2, "verse_count"=>26},
      {"id"=>3, "verse_count"=>18},
      {"id"=>4, "verse_count"=>17},
      {"id"=>5, "verse_count"=>20}]},
  {"id"=>60,
    "abbrev"=>"1PE",
    "name"=>"1 Peter",
    "chapters"=>
    [{"id"=>1, "verse_count"=>25},
      {"id"=>2, "verse_count"=>25},
      {"id"=>3, "verse_count"=>22},
      {"id"=>4, "verse_count"=>19},
      {"id"=>5, "verse_count"=>14}]},
  {"id"=>61,
    "abbrev"=>"2PE",
    "name"=>"2 Peter",
    "chapters"=>
    [{"id"=>1, "verse_count"=>21},
      {"id"=>2, "verse_count"=>22},
      {"id"=>3, "verse_count"=>18}]},
  {"id"=>62,
    "abbrev"=>"1JO",
    "name"=>"1 John",
    "chapters"=>
    [{"id"=>1, "verse_count"=>10},
      {"id"=>2, "verse_count"=>29},
      {"id"=>3, "verse_count"=>24},
      {"id"=>4, "verse_count"=>21},
      {"id"=>5, "verse_count"=>21}]},
  {"id"=>63,
    "abbrev"=>"2JO",
    "name"=>"2 John",
    "chapters"=>[{"id"=>1, "verse_count"=>13}]},
  {"id"=>64,
    "abbrev"=>"3JO",
    "name"=>"3 John",
    "chapters"=>[{"id"=>1, "verse_count"=>15}]},
  {"id"=>65,
    "abbrev"=>"JUD",
    "name"=>"Jude",
    "chapters"=>[{"id"=>1, "verse_count"=>25}]},
  {"id"=>66,
    "abbrev"=>"REV",
    "name"=>"Revelation",
    "chapters"=>
    [{"id"=>1, "verse_count"=>20},
      {"id"=>2, "verse_count"=>29},
      {"id"=>3, "verse_count"=>22},
      {"id"=>4, "verse_count"=>11},
      {"id"=>5, "verse_count"=>14},
      {"id"=>6, "verse_count"=>17},
      {"id"=>7, "verse_count"=>17},
      {"id"=>8, "verse_count"=>13},
      {"id"=>9, "verse_count"=>21},
      {"id"=>10, "verse_count"=>11},
      {"id"=>11, "verse_count"=>19},
      {"id"=>12, "verse_count"=>17},
      {"id"=>13, "verse_count"=>18},
      {"id"=>14, "verse_count"=>20},
      {"id"=>15, "verse_count"=>8},
      {"id"=>16, "verse_count"=>21},
      {"id"=>17, "verse_count"=>18},
      {"id"=>18, "verse_count"=>24},
      {"id"=>19, "verse_count"=>21},
      {"id"=>20, "verse_count"=>15},
      {"id"=>21, "verse_count"=>27},
      {"id"=>22, "verse_count"=>21}]}]

