module Scripturable
SCRIPTURE_BOOKS_META = [ 
  { "number"=>1,
    "abbr"=>"GEN",
    "name"=>"Genesis",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>31},
      {"number"=>2, "verse_count"=>25},
      {"number"=>3, "verse_count"=>24},
      {"number"=>4, "verse_count"=>26},
      {"number"=>5, "verse_count"=>32},
      {"number"=>6, "verse_count"=>22},
      {"number"=>7, "verse_count"=>24},
      {"number"=>8, "verse_count"=>22},
      {"number"=>9, "verse_count"=>29},
      {"number"=>10, "verse_count"=>32},
      {"number"=>11, "verse_count"=>32},
      {"number"=>12, "verse_count"=>20},
      {"number"=>13, "verse_count"=>18},
      {"number"=>14, "verse_count"=>24},
      {"number"=>15, "verse_count"=>21},
      {"number"=>16, "verse_count"=>16},
      {"number"=>17, "verse_count"=>27},
      {"number"=>18, "verse_count"=>33},
      {"number"=>19, "verse_count"=>38},
      {"number"=>20, "verse_count"=>18},
      {"number"=>21, "verse_count"=>34},
      {"number"=>22, "verse_count"=>24},
      {"number"=>23, "verse_count"=>20},
      {"number"=>24, "verse_count"=>67},
      {"number"=>25, "verse_count"=>34},
      {"number"=>26, "verse_count"=>35},
      {"number"=>27, "verse_count"=>46},
      {"number"=>28, "verse_count"=>22},
      {"number"=>29, "verse_count"=>35},
      {"number"=>30, "verse_count"=>43},
      {"number"=>31, "verse_count"=>55},
      {"number"=>32, "verse_count"=>32},
      {"number"=>33, "verse_count"=>20},
      {"number"=>34, "verse_count"=>31},
      {"number"=>35, "verse_count"=>29},
      {"number"=>36, "verse_count"=>43},
      {"number"=>37, "verse_count"=>36},
      {"number"=>38, "verse_count"=>30},
      {"number"=>39, "verse_count"=>23},
      {"number"=>40, "verse_count"=>23},
      {"number"=>41, "verse_count"=>57},
      {"number"=>42, "verse_count"=>38},
      {"number"=>43, "verse_count"=>34},
      {"number"=>44, "verse_count"=>34},
      {"number"=>45, "verse_count"=>28},
      {"number"=>46, "verse_count"=>34},
      {"number"=>47, "verse_count"=>31},
      {"number"=>48, "verse_count"=>22},
      {"number"=>49, "verse_count"=>33},
      {"number"=>50, "verse_count"=>26}]},
  {"number"=>2,
    "abbr"=>"EXO",
    "name"=>"Exodus",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>22},
      {"number"=>2, "verse_count"=>25},
      {"number"=>3, "verse_count"=>22},
      {"number"=>4, "verse_count"=>31},
      {"number"=>5, "verse_count"=>23},
      {"number"=>6, "verse_count"=>30},
      {"number"=>7, "verse_count"=>25},
      {"number"=>8, "verse_count"=>32},
      {"number"=>9, "verse_count"=>35},
      {"number"=>10, "verse_count"=>29},
      {"number"=>11, "verse_count"=>10},
      {"number"=>12, "verse_count"=>51},
      {"number"=>13, "verse_count"=>22},
      {"number"=>14, "verse_count"=>31},
      {"number"=>15, "verse_count"=>27},
      {"number"=>16, "verse_count"=>36},
      {"number"=>17, "verse_count"=>16},
      {"number"=>18, "verse_count"=>27},
      {"number"=>19, "verse_count"=>25},
      {"number"=>20, "verse_count"=>26},
      {"number"=>21, "verse_count"=>36},
      {"number"=>22, "verse_count"=>31},
      {"number"=>23, "verse_count"=>33},
      {"number"=>24, "verse_count"=>18},
      {"number"=>25, "verse_count"=>40},
      {"number"=>26, "verse_count"=>37},
      {"number"=>27, "verse_count"=>21},
      {"number"=>28, "verse_count"=>43},
      {"number"=>29, "verse_count"=>46},
      {"number"=>30, "verse_count"=>38},
      {"number"=>31, "verse_count"=>18},
      {"number"=>32, "verse_count"=>35},
      {"number"=>33, "verse_count"=>23},
      {"number"=>34, "verse_count"=>35},
      {"number"=>35, "verse_count"=>35},
      {"number"=>36, "verse_count"=>38},
      {"number"=>37, "verse_count"=>29},
      {"number"=>38, "verse_count"=>31},
      {"number"=>39, "verse_count"=>43},
      {"number"=>40, "verse_count"=>38}]},
  {"number"=>3,
    "abbr"=>"LEV",
    "name"=>"Leviticus",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>17},
      {"number"=>2, "verse_count"=>16},
      {"number"=>3, "verse_count"=>17},
      {"number"=>4, "verse_count"=>35},
      {"number"=>5, "verse_count"=>19},
      {"number"=>6, "verse_count"=>30},
      {"number"=>7, "verse_count"=>38},
      {"number"=>8, "verse_count"=>36},
      {"number"=>9, "verse_count"=>24},
      {"number"=>10, "verse_count"=>20},
      {"number"=>11, "verse_count"=>47},
      {"number"=>12, "verse_count"=>8},
      {"number"=>13, "verse_count"=>59},
      {"number"=>14, "verse_count"=>57},
      {"number"=>15, "verse_count"=>33},
      {"number"=>16, "verse_count"=>34},
      {"number"=>17, "verse_count"=>16},
      {"number"=>18, "verse_count"=>30},
      {"number"=>19, "verse_count"=>37},
      {"number"=>20, "verse_count"=>27},
      {"number"=>21, "verse_count"=>24},
      {"number"=>22, "verse_count"=>33},
      {"number"=>23, "verse_count"=>44},
      {"number"=>24, "verse_count"=>23},
      {"number"=>25, "verse_count"=>55},
      {"number"=>26, "verse_count"=>46},
      {"number"=>27, "verse_count"=>34}]},
  {"number"=>4,
    "abbr"=>"NUM",
    "name"=>"Numbers",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>54},
      {"number"=>2, "verse_count"=>34},
      {"number"=>3, "verse_count"=>51},
      {"number"=>4, "verse_count"=>49},
      {"number"=>5, "verse_count"=>31},
      {"number"=>6, "verse_count"=>27},
      {"number"=>7, "verse_count"=>89},
      {"number"=>8, "verse_count"=>26},
      {"number"=>9, "verse_count"=>23},
      {"number"=>10, "verse_count"=>36},
      {"number"=>11, "verse_count"=>35},
      {"number"=>12, "verse_count"=>16},
      {"number"=>13, "verse_count"=>33},
      {"number"=>14, "verse_count"=>45},
      {"number"=>15, "verse_count"=>41},
      {"number"=>16, "verse_count"=>50},
      {"number"=>17, "verse_count"=>13},
      {"number"=>18, "verse_count"=>32},
      {"number"=>19, "verse_count"=>22},
      {"number"=>20, "verse_count"=>29},
      {"number"=>21, "verse_count"=>35},
      {"number"=>22, "verse_count"=>41},
      {"number"=>23, "verse_count"=>30},
      {"number"=>24, "verse_count"=>25},
      {"number"=>25, "verse_count"=>18},
      {"number"=>26, "verse_count"=>65},
      {"number"=>27, "verse_count"=>23},
      {"number"=>28, "verse_count"=>31},
      {"number"=>29, "verse_count"=>40},
      {"number"=>30, "verse_count"=>16},
      {"number"=>31, "verse_count"=>54},
      {"number"=>32, "verse_count"=>42},
      {"number"=>33, "verse_count"=>56},
      {"number"=>34, "verse_count"=>29},
      {"number"=>35, "verse_count"=>34},
      {"number"=>36, "verse_count"=>13}]},
  {"number"=>5,
    "abbr"=>"DEU",
    "name"=>"Deuteronomy",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>46},
      {"number"=>2, "verse_count"=>37},
      {"number"=>3, "verse_count"=>29},
      {"number"=>4, "verse_count"=>49},
      {"number"=>5, "verse_count"=>33},
      {"number"=>6, "verse_count"=>25},
      {"number"=>7, "verse_count"=>26},
      {"number"=>8, "verse_count"=>20},
      {"number"=>9, "verse_count"=>29},
      {"number"=>10, "verse_count"=>22},
      {"number"=>11, "verse_count"=>32},
      {"number"=>12, "verse_count"=>32},
      {"number"=>13, "verse_count"=>18},
      {"number"=>14, "verse_count"=>29},
      {"number"=>15, "verse_count"=>23},
      {"number"=>16, "verse_count"=>22},
      {"number"=>17, "verse_count"=>20},
      {"number"=>18, "verse_count"=>22},
      {"number"=>19, "verse_count"=>21},
      {"number"=>20, "verse_count"=>20},
      {"number"=>21, "verse_count"=>23},
      {"number"=>22, "verse_count"=>30},
      {"number"=>23, "verse_count"=>25},
      {"number"=>24, "verse_count"=>22},
      {"number"=>25, "verse_count"=>19},
      {"number"=>26, "verse_count"=>19},
      {"number"=>27, "verse_count"=>26},
      {"number"=>28, "verse_count"=>68},
      {"number"=>29, "verse_count"=>29},
      {"number"=>30, "verse_count"=>20},
      {"number"=>31, "verse_count"=>30},
      {"number"=>32, "verse_count"=>52},
      {"number"=>33, "verse_count"=>29},
      {"number"=>34, "verse_count"=>12}]},
  {"number"=>6,
    "abbr"=>"JOS",
    "name"=>"Joshua",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>18},
      {"number"=>2, "verse_count"=>24},
      {"number"=>3, "verse_count"=>17},
      {"number"=>4, "verse_count"=>24},
      {"number"=>5, "verse_count"=>15},
      {"number"=>6, "verse_count"=>27},
      {"number"=>7, "verse_count"=>26},
      {"number"=>8, "verse_count"=>35},
      {"number"=>9, "verse_count"=>27},
      {"number"=>10, "verse_count"=>43},
      {"number"=>11, "verse_count"=>23},
      {"number"=>12, "verse_count"=>24},
      {"number"=>13, "verse_count"=>33},
      {"number"=>14, "verse_count"=>15},
      {"number"=>15, "verse_count"=>63},
      {"number"=>16, "verse_count"=>10},
      {"number"=>17, "verse_count"=>18},
      {"number"=>18, "verse_count"=>28},
      {"number"=>19, "verse_count"=>51},
      {"number"=>20, "verse_count"=>9},
      {"number"=>21, "verse_count"=>45},
      {"number"=>22, "verse_count"=>34},
      {"number"=>23, "verse_count"=>16},
      {"number"=>24, "verse_count"=>33}]},
  {"number"=>7,
    "abbr"=>"JDG",
    "name"=>"Judges",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>36},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>31},
      {"number"=>4, "verse_count"=>24},
      {"number"=>5, "verse_count"=>31},
      {"number"=>6, "verse_count"=>40},
      {"number"=>7, "verse_count"=>25},
      {"number"=>8, "verse_count"=>35},
      {"number"=>9, "verse_count"=>57},
      {"number"=>10, "verse_count"=>18},
      {"number"=>11, "verse_count"=>40},
      {"number"=>12, "verse_count"=>15},
      {"number"=>13, "verse_count"=>25},
      {"number"=>14, "verse_count"=>20},
      {"number"=>15, "verse_count"=>20},
      {"number"=>16, "verse_count"=>31},
      {"number"=>17, "verse_count"=>13},
      {"number"=>18, "verse_count"=>31},
      {"number"=>19, "verse_count"=>30},
      {"number"=>20, "verse_count"=>48},
      {"number"=>21, "verse_count"=>25}]},
  {"number"=>8,
    "abbr"=>"RUT",
    "name"=>"Ruth",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>22},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>18},
      {"number"=>4, "verse_count"=>22}]},
  {"number"=>9,
    "abbr"=>"1SA",
    "name"=>"1 Samuel",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>28},
      {"number"=>2, "verse_count"=>36},
      {"number"=>3, "verse_count"=>21},
      {"number"=>4, "verse_count"=>22},
      {"number"=>5, "verse_count"=>12},
      {"number"=>6, "verse_count"=>21},
      {"number"=>7, "verse_count"=>17},
      {"number"=>8, "verse_count"=>22},
      {"number"=>9, "verse_count"=>27},
      {"number"=>10, "verse_count"=>27},
      {"number"=>11, "verse_count"=>15},
      {"number"=>12, "verse_count"=>25},
      {"number"=>13, "verse_count"=>23},
      {"number"=>14, "verse_count"=>52},
      {"number"=>15, "verse_count"=>35},
      {"number"=>16, "verse_count"=>23},
      {"number"=>17, "verse_count"=>58},
      {"number"=>18, "verse_count"=>30},
      {"number"=>19, "verse_count"=>24},
      {"number"=>20, "verse_count"=>42},
      {"number"=>21, "verse_count"=>15},
      {"number"=>22, "verse_count"=>23},
      {"number"=>23, "verse_count"=>29},
      {"number"=>24, "verse_count"=>22},
      {"number"=>25, "verse_count"=>44},
      {"number"=>26, "verse_count"=>25},
      {"number"=>27, "verse_count"=>12},
      {"number"=>28, "verse_count"=>25},
      {"number"=>29, "verse_count"=>11},
      {"number"=>30, "verse_count"=>31},
      {"number"=>31, "verse_count"=>13}]},
  {"number"=>10,
    "abbr"=>"2SA",
    "name"=>"2 Samuel",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>27},
      {"number"=>2, "verse_count"=>32},
      {"number"=>3, "verse_count"=>39},
      {"number"=>4, "verse_count"=>12},
      {"number"=>5, "verse_count"=>25},
      {"number"=>6, "verse_count"=>23},
      {"number"=>7, "verse_count"=>29},
      {"number"=>8, "verse_count"=>18},
      {"number"=>9, "verse_count"=>13},
      {"number"=>10, "verse_count"=>19},
      {"number"=>11, "verse_count"=>27},
      {"number"=>12, "verse_count"=>31},
      {"number"=>13, "verse_count"=>39},
      {"number"=>14, "verse_count"=>33},
      {"number"=>15, "verse_count"=>37},
      {"number"=>16, "verse_count"=>23},
      {"number"=>17, "verse_count"=>29},
      {"number"=>18, "verse_count"=>33},
      {"number"=>19, "verse_count"=>43},
      {"number"=>20, "verse_count"=>26},
      {"number"=>21, "verse_count"=>22},
      {"number"=>22, "verse_count"=>51},
      {"number"=>23, "verse_count"=>39},
      {"number"=>24, "verse_count"=>25}]},
  {"number"=>11,
    "abbr"=>"1KG",
    "name"=>"1 Kings",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>53},
      {"number"=>2, "verse_count"=>46},
      {"number"=>3, "verse_count"=>28},
      {"number"=>4, "verse_count"=>34},
      {"number"=>5, "verse_count"=>18},
      {"number"=>6, "verse_count"=>38},
      {"number"=>7, "verse_count"=>51},
      {"number"=>8, "verse_count"=>66},
      {"number"=>9, "verse_count"=>28},
      {"number"=>10, "verse_count"=>29},
      {"number"=>11, "verse_count"=>43},
      {"number"=>12, "verse_count"=>33},
      {"number"=>13, "verse_count"=>34},
      {"number"=>14, "verse_count"=>31},
      {"number"=>15, "verse_count"=>34},
      {"number"=>16, "verse_count"=>34},
      {"number"=>17, "verse_count"=>24},
      {"number"=>18, "verse_count"=>46},
      {"number"=>19, "verse_count"=>21},
      {"number"=>20, "verse_count"=>43},
      {"number"=>21, "verse_count"=>29},
      {"number"=>22, "verse_count"=>53}]},
  {"number"=>12,
    "abbr"=>"2KG",
    "name"=>"2 Kings",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>18},
      {"number"=>2, "verse_count"=>25},
      {"number"=>3, "verse_count"=>27},
      {"number"=>4, "verse_count"=>44},
      {"number"=>5, "verse_count"=>27},
      {"number"=>6, "verse_count"=>33},
      {"number"=>7, "verse_count"=>20},
      {"number"=>8, "verse_count"=>29},
      {"number"=>9, "verse_count"=>37},
      {"number"=>10, "verse_count"=>36},
      {"number"=>11, "verse_count"=>21},
      {"number"=>12, "verse_count"=>21},
      {"number"=>13, "verse_count"=>25},
      {"number"=>14, "verse_count"=>29},
      {"number"=>15, "verse_count"=>38},
      {"number"=>16, "verse_count"=>20},
      {"number"=>17, "verse_count"=>41},
      {"number"=>18, "verse_count"=>37},
      {"number"=>19, "verse_count"=>37},
      {"number"=>20, "verse_count"=>21},
      {"number"=>21, "verse_count"=>26},
      {"number"=>22, "verse_count"=>20},
      {"number"=>23, "verse_count"=>37},
      {"number"=>24, "verse_count"=>20},
      {"number"=>25, "verse_count"=>30}]},
  {"number"=>13,
    "abbr"=>"1KR",
    "name"=>"1 Chronicles",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>54},
      {"number"=>2, "verse_count"=>55},
      {"number"=>3, "verse_count"=>24},
      {"number"=>4, "verse_count"=>43},
      {"number"=>5, "verse_count"=>26},
      {"number"=>6, "verse_count"=>81},
      {"number"=>7, "verse_count"=>40},
      {"number"=>8, "verse_count"=>40},
      {"number"=>9, "verse_count"=>44},
      {"number"=>10, "verse_count"=>14},
      {"number"=>11, "verse_count"=>47},
      {"number"=>12, "verse_count"=>40},
      {"number"=>13, "verse_count"=>14},
      {"number"=>14, "verse_count"=>17},
      {"number"=>15, "verse_count"=>29},
      {"number"=>16, "verse_count"=>43},
      {"number"=>17, "verse_count"=>27},
      {"number"=>18, "verse_count"=>17},
      {"number"=>19, "verse_count"=>19},
      {"number"=>20, "verse_count"=>8},
      {"number"=>21, "verse_count"=>30},
      {"number"=>22, "verse_count"=>19},
      {"number"=>23, "verse_count"=>32},
      {"number"=>24, "verse_count"=>31},
      {"number"=>25, "verse_count"=>31},
      {"number"=>26, "verse_count"=>32},
      {"number"=>27, "verse_count"=>34},
      {"number"=>28, "verse_count"=>21},
      {"number"=>29, "verse_count"=>30}]},
  {"number"=>14,
    "abbr"=>"2KR",
    "name"=>"2 Chronicles",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>17},
      {"number"=>2, "verse_count"=>18},
      {"number"=>3, "verse_count"=>17},
      {"number"=>4, "verse_count"=>22},
      {"number"=>5, "verse_count"=>14},
      {"number"=>6, "verse_count"=>42},
      {"number"=>7, "verse_count"=>22},
      {"number"=>8, "verse_count"=>18},
      {"number"=>9, "verse_count"=>31},
      {"number"=>10, "verse_count"=>19},
      {"number"=>11, "verse_count"=>23},
      {"number"=>12, "verse_count"=>16},
      {"number"=>13, "verse_count"=>22},
      {"number"=>14, "verse_count"=>15},
      {"number"=>15, "verse_count"=>19},
      {"number"=>16, "verse_count"=>14},
      {"number"=>17, "verse_count"=>19},
      {"number"=>18, "verse_count"=>34},
      {"number"=>19, "verse_count"=>11},
      {"number"=>20, "verse_count"=>37},
      {"number"=>21, "verse_count"=>20},
      {"number"=>22, "verse_count"=>12},
      {"number"=>23, "verse_count"=>21},
      {"number"=>24, "verse_count"=>27},
      {"number"=>25, "verse_count"=>28},
      {"number"=>26, "verse_count"=>23},
      {"number"=>27, "verse_count"=>9},
      {"number"=>28, "verse_count"=>27},
      {"number"=>29, "verse_count"=>36},
      {"number"=>30, "verse_count"=>27},
      {"number"=>31, "verse_count"=>21},
      {"number"=>32, "verse_count"=>33},
      {"number"=>33, "verse_count"=>25},
      {"number"=>34, "verse_count"=>33},
      {"number"=>35, "verse_count"=>27},
      {"number"=>36, "verse_count"=>23}]},
  {"number"=>15,
    "abbr"=>"EZR",
    "name"=>"Ezra",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>11},
      {"number"=>2, "verse_count"=>70},
      {"number"=>3, "verse_count"=>13},
      {"number"=>4, "verse_count"=>24},
      {"number"=>5, "verse_count"=>17},
      {"number"=>6, "verse_count"=>22},
      {"number"=>7, "verse_count"=>28},
      {"number"=>8, "verse_count"=>36},
      {"number"=>9, "verse_count"=>15},
      {"number"=>10, "verse_count"=>44}]},
  {"number"=>16,
    "abbr"=>"NEH",
    "name"=>"Nehemiah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>11},
      {"number"=>2, "verse_count"=>20},
      {"number"=>3, "verse_count"=>32},
      {"number"=>4, "verse_count"=>23},
      {"number"=>5, "verse_count"=>19},
      {"number"=>6, "verse_count"=>19},
      {"number"=>7, "verse_count"=>73},
      {"number"=>8, "verse_count"=>18},
      {"number"=>9, "verse_count"=>38},
      {"number"=>10, "verse_count"=>39},
      {"number"=>11, "verse_count"=>36},
      {"number"=>12, "verse_count"=>47},
      {"number"=>13, "verse_count"=>31}]},
  {"number"=>17,
    "abbr"=>"EST",
    "name"=>"Esther",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>22},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>15},
      {"number"=>4, "verse_count"=>17},
      {"number"=>5, "verse_count"=>14},
      {"number"=>6, "verse_count"=>14},
      {"number"=>7, "verse_count"=>10},
      {"number"=>8, "verse_count"=>17},
      {"number"=>9, "verse_count"=>32},
      {"number"=>10, "verse_count"=>3}]},
  {"number"=>18,
    "abbr"=>"JOB",
    "name"=>"Job",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>22},
      {"number"=>2, "verse_count"=>13},
      {"number"=>3, "verse_count"=>26},
      {"number"=>4, "verse_count"=>21},
      {"number"=>5, "verse_count"=>27},
      {"number"=>6, "verse_count"=>30},
      {"number"=>7, "verse_count"=>21},
      {"number"=>8, "verse_count"=>22},
      {"number"=>9, "verse_count"=>35},
      {"number"=>10, "verse_count"=>22},
      {"number"=>11, "verse_count"=>20},
      {"number"=>12, "verse_count"=>25},
      {"number"=>13, "verse_count"=>28},
      {"number"=>14, "verse_count"=>22},
      {"number"=>15, "verse_count"=>35},
      {"number"=>16, "verse_count"=>22},
      {"number"=>17, "verse_count"=>16},
      {"number"=>18, "verse_count"=>21},
      {"number"=>19, "verse_count"=>29},
      {"number"=>20, "verse_count"=>29},
      {"number"=>21, "verse_count"=>34},
      {"number"=>22, "verse_count"=>30},
      {"number"=>23, "verse_count"=>17},
      {"number"=>24, "verse_count"=>25},
      {"number"=>25, "verse_count"=>6},
      {"number"=>26, "verse_count"=>14},
      {"number"=>27, "verse_count"=>23},
      {"number"=>28, "verse_count"=>28},
      {"number"=>29, "verse_count"=>25},
      {"number"=>30, "verse_count"=>31},
      {"number"=>31, "verse_count"=>40},
      {"number"=>32, "verse_count"=>22},
      {"number"=>33, "verse_count"=>33},
      {"number"=>34, "verse_count"=>37},
      {"number"=>35, "verse_count"=>16},
      {"number"=>36, "verse_count"=>33},
      {"number"=>37, "verse_count"=>24},
      {"number"=>38, "verse_count"=>41},
      {"number"=>39, "verse_count"=>30},
      {"number"=>40, "verse_count"=>24},
      {"number"=>41, "verse_count"=>34},
      {"number"=>42, "verse_count"=>17}]},
  {"number"=>19,
    "abbr"=>"PSA",
    "name"=>"Psalms",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>6},
      {"number"=>2, "verse_count"=>12},
      {"number"=>3, "verse_count"=>8},
      {"number"=>4, "verse_count"=>8},
      {"number"=>5, "verse_count"=>12},
      {"number"=>6, "verse_count"=>10},
      {"number"=>7, "verse_count"=>17},
      {"number"=>8, "verse_count"=>9},
      {"number"=>9, "verse_count"=>20},
      {"number"=>10, "verse_count"=>18},
      {"number"=>11, "verse_count"=>7},
      {"number"=>12, "verse_count"=>8},
      {"number"=>13, "verse_count"=>6},
      {"number"=>14, "verse_count"=>7},
      {"number"=>15, "verse_count"=>5},
      {"number"=>16, "verse_count"=>11},
      {"number"=>17, "verse_count"=>15},
      {"number"=>18, "verse_count"=>50},
      {"number"=>19, "verse_count"=>14},
      {"number"=>20, "verse_count"=>9},
      {"number"=>21, "verse_count"=>13},
      {"number"=>22, "verse_count"=>31},
      {"number"=>23, "verse_count"=>6},
      {"number"=>24, "verse_count"=>10},
      {"number"=>25, "verse_count"=>22},
      {"number"=>26, "verse_count"=>12},
      {"number"=>27, "verse_count"=>14},
      {"number"=>28, "verse_count"=>9},
      {"number"=>29, "verse_count"=>11},
      {"number"=>30, "verse_count"=>12},
      {"number"=>31, "verse_count"=>24},
      {"number"=>32, "verse_count"=>11},
      {"number"=>33, "verse_count"=>22},
      {"number"=>34, "verse_count"=>22},
      {"number"=>35, "verse_count"=>28},
      {"number"=>36, "verse_count"=>12},
      {"number"=>37, "verse_count"=>40},
      {"number"=>38, "verse_count"=>22},
      {"number"=>39, "verse_count"=>13},
      {"number"=>40, "verse_count"=>17},
      {"number"=>41, "verse_count"=>13},
      {"number"=>42, "verse_count"=>11},
      {"number"=>43, "verse_count"=>5},
      {"number"=>44, "verse_count"=>26},
      {"number"=>45, "verse_count"=>17},
      {"number"=>46, "verse_count"=>11},
      {"number"=>47, "verse_count"=>9},
      {"number"=>48, "verse_count"=>14},
      {"number"=>49, "verse_count"=>20},
      {"number"=>50, "verse_count"=>23},
      {"number"=>51, "verse_count"=>19},
      {"number"=>52, "verse_count"=>9},
      {"number"=>53, "verse_count"=>6},
      {"number"=>54, "verse_count"=>7},
      {"number"=>55, "verse_count"=>23},
      {"number"=>56, "verse_count"=>13},
      {"number"=>57, "verse_count"=>11},
      {"number"=>58, "verse_count"=>11},
      {"number"=>59, "verse_count"=>17},
      {"number"=>60, "verse_count"=>12},
      {"number"=>61, "verse_count"=>8},
      {"number"=>62, "verse_count"=>12},
      {"number"=>63, "verse_count"=>11},
      {"number"=>64, "verse_count"=>10},
      {"number"=>65, "verse_count"=>13},
      {"number"=>66, "verse_count"=>20},
      {"number"=>67, "verse_count"=>7},
      {"number"=>68, "verse_count"=>35},
      {"number"=>69, "verse_count"=>36},
      {"number"=>70, "verse_count"=>5},
      {"number"=>71, "verse_count"=>24},
      {"number"=>72, "verse_count"=>20},
      {"number"=>73, "verse_count"=>28},
      {"number"=>74, "verse_count"=>23},
      {"number"=>75, "verse_count"=>10},
      {"number"=>76, "verse_count"=>12},
      {"number"=>77, "verse_count"=>20},
      {"number"=>78, "verse_count"=>72},
      {"number"=>79, "verse_count"=>13},
      {"number"=>80, "verse_count"=>19},
      {"number"=>81, "verse_count"=>16},
      {"number"=>82, "verse_count"=>8},
      {"number"=>83, "verse_count"=>18},
      {"number"=>84, "verse_count"=>12},
      {"number"=>85, "verse_count"=>13},
      {"number"=>86, "verse_count"=>17},
      {"number"=>87, "verse_count"=>7},
      {"number"=>88, "verse_count"=>18},
      {"number"=>89, "verse_count"=>52},
      {"number"=>90, "verse_count"=>17},
      {"number"=>91, "verse_count"=>16},
      {"number"=>92, "verse_count"=>15},
      {"number"=>93, "verse_count"=>5},
      {"number"=>94, "verse_count"=>23},
      {"number"=>95, "verse_count"=>11},
      {"number"=>96, "verse_count"=>13},
      {"number"=>97, "verse_count"=>12},
      {"number"=>98, "verse_count"=>9},
      {"number"=>99, "verse_count"=>9},
      {"number"=>100, "verse_count"=>5},
      {"number"=>101, "verse_count"=>8},
      {"number"=>102, "verse_count"=>28},
      {"number"=>103, "verse_count"=>22},
      {"number"=>104, "verse_count"=>35},
      {"number"=>105, "verse_count"=>45},
      {"number"=>106, "verse_count"=>48},
      {"number"=>107, "verse_count"=>43},
      {"number"=>108, "verse_count"=>13},
      {"number"=>109, "verse_count"=>31},
      {"number"=>110, "verse_count"=>7},
      {"number"=>111, "verse_count"=>10},
      {"number"=>112, "verse_count"=>10},
      {"number"=>113, "verse_count"=>9},
      {"number"=>114, "verse_count"=>8},
      {"number"=>115, "verse_count"=>18},
      {"number"=>116, "verse_count"=>19},
      {"number"=>117, "verse_count"=>2},
      {"number"=>118, "verse_count"=>29},
      {"number"=>119, "verse_count"=>176},
      {"number"=>120, "verse_count"=>7},
      {"number"=>121, "verse_count"=>8},
      {"number"=>122, "verse_count"=>9},
      {"number"=>123, "verse_count"=>4},
      {"number"=>124, "verse_count"=>8},
      {"number"=>125, "verse_count"=>5},
      {"number"=>126, "verse_count"=>6},
      {"number"=>127, "verse_count"=>5},
      {"number"=>128, "verse_count"=>6},
      {"number"=>129, "verse_count"=>8},
      {"number"=>130, "verse_count"=>8},
      {"number"=>131, "verse_count"=>3},
      {"number"=>132, "verse_count"=>18},
      {"number"=>133, "verse_count"=>3},
      {"number"=>134, "verse_count"=>3},
      {"number"=>135, "verse_count"=>21},
      {"number"=>136, "verse_count"=>26},
      {"number"=>137, "verse_count"=>9},
      {"number"=>138, "verse_count"=>8},
      {"number"=>139, "verse_count"=>24},
      {"number"=>140, "verse_count"=>13},
      {"number"=>141, "verse_count"=>10},
      {"number"=>142, "verse_count"=>7},
      {"number"=>143, "verse_count"=>12},
      {"number"=>144, "verse_count"=>15},
      {"number"=>145, "verse_count"=>21},
      {"number"=>146, "verse_count"=>10},
      {"number"=>147, "verse_count"=>20},
      {"number"=>148, "verse_count"=>14},
      {"number"=>149, "verse_count"=>9},
      {"number"=>150, "verse_count"=>6}]},
  {"number"=>20,
    "abbr"=>"PRO",
    "name"=>"Proverbs",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>33},
      {"number"=>2, "verse_count"=>22},
      {"number"=>3, "verse_count"=>35},
      {"number"=>4, "verse_count"=>27},
      {"number"=>5, "verse_count"=>23},
      {"number"=>6, "verse_count"=>35},
      {"number"=>7, "verse_count"=>27},
      {"number"=>8, "verse_count"=>36},
      {"number"=>9, "verse_count"=>18},
      {"number"=>10, "verse_count"=>32},
      {"number"=>11, "verse_count"=>31},
      {"number"=>12, "verse_count"=>28},
      {"number"=>13, "verse_count"=>25},
      {"number"=>14, "verse_count"=>35},
      {"number"=>15, "verse_count"=>33},
      {"number"=>16, "verse_count"=>33},
      {"number"=>17, "verse_count"=>28},
      {"number"=>18, "verse_count"=>24},
      {"number"=>19, "verse_count"=>29},
      {"number"=>20, "verse_count"=>30},
      {"number"=>21, "verse_count"=>31},
      {"number"=>22, "verse_count"=>29},
      {"number"=>23, "verse_count"=>35},
      {"number"=>24, "verse_count"=>34},
      {"number"=>25, "verse_count"=>28},
      {"number"=>26, "verse_count"=>28},
      {"number"=>27, "verse_count"=>27},
      {"number"=>28, "verse_count"=>28},
      {"number"=>29, "verse_count"=>27},
      {"number"=>30, "verse_count"=>33},
      {"number"=>31, "verse_count"=>31}]},
  {"number"=>21,
    "abbr"=>"ECC",
    "name"=>"Ecclesiastes",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>18},
      {"number"=>2, "verse_count"=>26},
      {"number"=>3, "verse_count"=>22},
      {"number"=>4, "verse_count"=>16},
      {"number"=>5, "verse_count"=>20},
      {"number"=>6, "verse_count"=>12},
      {"number"=>7, "verse_count"=>29},
      {"number"=>8, "verse_count"=>17},
      {"number"=>9, "verse_count"=>18},
      {"number"=>10, "verse_count"=>20},
      {"number"=>11, "verse_count"=>10},
      {"number"=>12, "verse_count"=>14}]},
  {"number"=>22,
    "abbr"=>"SO",
    "name"=>"Song",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>17},
      {"number"=>2, "verse_count"=>17},
      {"number"=>3, "verse_count"=>11},
      {"number"=>4, "verse_count"=>16},
      {"number"=>5, "verse_count"=>16},
      {"number"=>6, "verse_count"=>13},
      {"number"=>7, "verse_count"=>13},
      {"number"=>8, "verse_count"=>14}]},
  {"number"=>23,
    "abbr"=>"ISA",
    "name"=>"Isaiah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>31},
      {"number"=>2, "verse_count"=>22},
      {"number"=>3, "verse_count"=>26},
      {"number"=>4, "verse_count"=>6},
      {"number"=>5, "verse_count"=>30},
      {"number"=>6, "verse_count"=>13},
      {"number"=>7, "verse_count"=>25},
      {"number"=>8, "verse_count"=>22},
      {"number"=>9, "verse_count"=>21},
      {"number"=>10, "verse_count"=>34},
      {"number"=>11, "verse_count"=>16},
      {"number"=>12, "verse_count"=>6},
      {"number"=>13, "verse_count"=>22},
      {"number"=>14, "verse_count"=>32},
      {"number"=>15, "verse_count"=>9},
      {"number"=>16, "verse_count"=>14},
      {"number"=>17, "verse_count"=>14},
      {"number"=>18, "verse_count"=>7},
      {"number"=>19, "verse_count"=>25},
      {"number"=>20, "verse_count"=>6},
      {"number"=>21, "verse_count"=>17},
      {"number"=>22, "verse_count"=>25},
      {"number"=>23, "verse_count"=>18},
      {"number"=>24, "verse_count"=>23},
      {"number"=>25, "verse_count"=>12},
      {"number"=>26, "verse_count"=>21},
      {"number"=>27, "verse_count"=>13},
      {"number"=>28, "verse_count"=>29},
      {"number"=>29, "verse_count"=>24},
      {"number"=>30, "verse_count"=>33},
      {"number"=>31, "verse_count"=>9},
      {"number"=>32, "verse_count"=>20},
      {"number"=>33, "verse_count"=>24},
      {"number"=>34, "verse_count"=>17},
      {"number"=>35, "verse_count"=>10},
      {"number"=>36, "verse_count"=>22},
      {"number"=>37, "verse_count"=>38},
      {"number"=>38, "verse_count"=>22},
      {"number"=>39, "verse_count"=>8},
      {"number"=>40, "verse_count"=>31},
      {"number"=>41, "verse_count"=>29},
      {"number"=>42, "verse_count"=>25},
      {"number"=>43, "verse_count"=>28},
      {"number"=>44, "verse_count"=>28},
      {"number"=>45, "verse_count"=>25},
      {"number"=>46, "verse_count"=>13},
      {"number"=>47, "verse_count"=>15},
      {"number"=>48, "verse_count"=>22},
      {"number"=>49, "verse_count"=>26},
      {"number"=>50, "verse_count"=>11},
      {"number"=>51, "verse_count"=>23},
      {"number"=>52, "verse_count"=>15},
      {"number"=>53, "verse_count"=>12},
      {"number"=>54, "verse_count"=>17},
      {"number"=>55, "verse_count"=>13},
      {"number"=>56, "verse_count"=>12},
      {"number"=>57, "verse_count"=>21},
      {"number"=>58, "verse_count"=>14},
      {"number"=>59, "verse_count"=>21},
      {"number"=>60, "verse_count"=>22},
      {"number"=>61, "verse_count"=>11},
      {"number"=>62, "verse_count"=>12},
      {"number"=>63, "verse_count"=>19},
      {"number"=>64, "verse_count"=>12},
      {"number"=>65, "verse_count"=>25},
      {"number"=>66, "verse_count"=>24}]},
  {"number"=>24,
    "abbr"=>"JER",
    "name"=>"Jeremiah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>19},
      {"number"=>2, "verse_count"=>37},
      {"number"=>3, "verse_count"=>25},
      {"number"=>4, "verse_count"=>31},
      {"number"=>5, "verse_count"=>31},
      {"number"=>6, "verse_count"=>30},
      {"number"=>7, "verse_count"=>34},
      {"number"=>8, "verse_count"=>22},
      {"number"=>9, "verse_count"=>26},
      {"number"=>10, "verse_count"=>25},
      {"number"=>11, "verse_count"=>23},
      {"number"=>12, "verse_count"=>17},
      {"number"=>13, "verse_count"=>27},
      {"number"=>14, "verse_count"=>22},
      {"number"=>15, "verse_count"=>21},
      {"number"=>16, "verse_count"=>21},
      {"number"=>17, "verse_count"=>27},
      {"number"=>18, "verse_count"=>23},
      {"number"=>19, "verse_count"=>15},
      {"number"=>20, "verse_count"=>18},
      {"number"=>21, "verse_count"=>14},
      {"number"=>22, "verse_count"=>30},
      {"number"=>23, "verse_count"=>40},
      {"number"=>24, "verse_count"=>10},
      {"number"=>25, "verse_count"=>38},
      {"number"=>26, "verse_count"=>24},
      {"number"=>27, "verse_count"=>22},
      {"number"=>28, "verse_count"=>17},
      {"number"=>29, "verse_count"=>32},
      {"number"=>30, "verse_count"=>24},
      {"number"=>31, "verse_count"=>40},
      {"number"=>32, "verse_count"=>44},
      {"number"=>33, "verse_count"=>26},
      {"number"=>34, "verse_count"=>22},
      {"number"=>35, "verse_count"=>19},
      {"number"=>36, "verse_count"=>32},
      {"number"=>37, "verse_count"=>21},
      {"number"=>38, "verse_count"=>28},
      {"number"=>39, "verse_count"=>18},
      {"number"=>40, "verse_count"=>16},
      {"number"=>41, "verse_count"=>18},
      {"number"=>42, "verse_count"=>22},
      {"number"=>43, "verse_count"=>13},
      {"number"=>44, "verse_count"=>30},
      {"number"=>45, "verse_count"=>5},
      {"number"=>46, "verse_count"=>28},
      {"number"=>47, "verse_count"=>7},
      {"number"=>48, "verse_count"=>47},
      {"number"=>49, "verse_count"=>39},
      {"number"=>50, "verse_count"=>46},
      {"number"=>51, "verse_count"=>64},
      {"number"=>52, "verse_count"=>34}]},
  {"number"=>25,
    "abbr"=>"LAM",
    "name"=>"Lamentations",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>22},
      {"number"=>2, "verse_count"=>22},
      {"number"=>3, "verse_count"=>66},
      {"number"=>4, "verse_count"=>22},
      {"number"=>5, "verse_count"=>22}]},
  {"number"=>26,
    "abbr"=>"EZE",
    "name"=>"Ezekiel",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>28},
      {"number"=>2, "verse_count"=>10},
      {"number"=>3, "verse_count"=>27},
      {"number"=>4, "verse_count"=>17},
      {"number"=>5, "verse_count"=>17},
      {"number"=>6, "verse_count"=>14},
      {"number"=>7, "verse_count"=>27},
      {"number"=>8, "verse_count"=>18},
      {"number"=>9, "verse_count"=>11},
      {"number"=>10, "verse_count"=>22},
      {"number"=>11, "verse_count"=>25},
      {"number"=>12, "verse_count"=>28},
      {"number"=>13, "verse_count"=>23},
      {"number"=>14, "verse_count"=>23},
      {"number"=>15, "verse_count"=>8},
      {"number"=>16, "verse_count"=>63},
      {"number"=>17, "verse_count"=>24},
      {"number"=>18, "verse_count"=>32},
      {"number"=>19, "verse_count"=>14},
      {"number"=>20, "verse_count"=>49},
      {"number"=>21, "verse_count"=>32},
      {"number"=>22, "verse_count"=>31},
      {"number"=>23, "verse_count"=>49},
      {"number"=>24, "verse_count"=>27},
      {"number"=>25, "verse_count"=>17},
      {"number"=>26, "verse_count"=>21},
      {"number"=>27, "verse_count"=>36},
      {"number"=>28, "verse_count"=>26},
      {"number"=>29, "verse_count"=>21},
      {"number"=>30, "verse_count"=>26},
      {"number"=>31, "verse_count"=>18},
      {"number"=>32, "verse_count"=>32},
      {"number"=>33, "verse_count"=>33},
      {"number"=>34, "verse_count"=>31},
      {"number"=>35, "verse_count"=>15},
      {"number"=>36, "verse_count"=>38},
      {"number"=>37, "verse_count"=>28},
      {"number"=>38, "verse_count"=>23},
      {"number"=>39, "verse_count"=>29},
      {"number"=>40, "verse_count"=>49},
      {"number"=>41, "verse_count"=>26},
      {"number"=>42, "verse_count"=>20},
      {"number"=>43, "verse_count"=>27},
      {"number"=>44, "verse_count"=>31},
      {"number"=>45, "verse_count"=>25},
      {"number"=>46, "verse_count"=>24},
      {"number"=>47, "verse_count"=>23},
      {"number"=>48, "verse_count"=>35}]},
  {"number"=>27,
    "abbr"=>"DAN",
    "name"=>"Daniel",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>21},
      {"number"=>2, "verse_count"=>49},
      {"number"=>3, "verse_count"=>30},
      {"number"=>4, "verse_count"=>37},
      {"number"=>5, "verse_count"=>31},
      {"number"=>6, "verse_count"=>28},
      {"number"=>7, "verse_count"=>28},
      {"number"=>8, "verse_count"=>27},
      {"number"=>9, "verse_count"=>27},
      {"number"=>10, "verse_count"=>21},
      {"number"=>11, "verse_count"=>45},
      {"number"=>12, "verse_count"=>13}]},
  {"number"=>28,
    "abbr"=>"HOS",
    "name"=>"Hosea",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>11},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>5},
      {"number"=>4, "verse_count"=>19},
      {"number"=>5, "verse_count"=>15},
      {"number"=>6, "verse_count"=>11},
      {"number"=>7, "verse_count"=>16},
      {"number"=>8, "verse_count"=>14},
      {"number"=>9, "verse_count"=>17},
      {"number"=>10, "verse_count"=>15},
      {"number"=>11, "verse_count"=>12},
      {"number"=>12, "verse_count"=>14},
      {"number"=>13, "verse_count"=>16},
      {"number"=>14, "verse_count"=>9}]},
  {"number"=>29,
    "abbr"=>"JOE",
    "name"=>"Joel",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>20},
      {"number"=>2, "verse_count"=>32},
      {"number"=>3, "verse_count"=>21}]},
  {"number"=>30,
    "abbr"=>"AMO",
    "name"=>"Amos",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>15},
      {"number"=>2, "verse_count"=>16},
      {"number"=>3, "verse_count"=>15},
      {"number"=>4, "verse_count"=>13},
      {"number"=>5, "verse_count"=>27},
      {"number"=>6, "verse_count"=>14},
      {"number"=>7, "verse_count"=>17},
      {"number"=>8, "verse_count"=>14},
      {"number"=>9, "verse_count"=>15}]},
  {"number"=>31,
    "abbr"=>"OBA",
    "name"=>"Obadiah",
    "chapters"=>[{"number"=>1, "verse_count"=>21}]},
  {"number"=>32,
    "abbr"=>"JON",
    "name"=>"Jonah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>17},
      {"number"=>2, "verse_count"=>10},
      {"number"=>3, "verse_count"=>10},
      {"number"=>4, "verse_count"=>11}]},
  {"number"=>33,
    "abbr"=>"MIC",
    "name"=>"Micah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>16},
      {"number"=>2, "verse_count"=>13},
      {"number"=>3, "verse_count"=>12},
      {"number"=>4, "verse_count"=>13},
      {"number"=>5, "verse_count"=>15},
      {"number"=>6, "verse_count"=>16},
      {"number"=>7, "verse_count"=>20}]},
  {"number"=>34,
    "abbr"=>"NAH",
    "name"=>"Nahum",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>15},
      {"number"=>2, "verse_count"=>13},
      {"number"=>3, "verse_count"=>19}]},
  {"number"=>35,
    "abbr"=>"HAB",
    "name"=>"Habakkuk",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>17},
      {"number"=>2, "verse_count"=>20},
      {"number"=>3, "verse_count"=>19}]},
  {"number"=>36,
    "abbr"=>"ZEP",
    "name"=>"Zephaniah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>18},
      {"number"=>2, "verse_count"=>15},
      {"number"=>3, "verse_count"=>20}]},
  {"number"=>37,
    "abbr"=>"HAG",
    "name"=>"Haggai",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>15}, 
      {"number"=>2, "verse_count"=>23}]},
  {"number"=>38,
    "abbr"=>"ZEC",
    "name"=>"Zechariah",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>21},
      {"number"=>2, "verse_count"=>13},
      {"number"=>3, "verse_count"=>10},
      {"number"=>4, "verse_count"=>14},
      {"number"=>5, "verse_count"=>11},
      {"number"=>6, "verse_count"=>15},
      {"number"=>7, "verse_count"=>14},
      {"number"=>8, "verse_count"=>23},
      {"number"=>9, "verse_count"=>17},
      {"number"=>10, "verse_count"=>12},
      {"number"=>11, "verse_count"=>17},
      {"number"=>12, "verse_count"=>14},
      {"number"=>13, "verse_count"=>9},
      {"number"=>14, "verse_count"=>21}]},
  {"number"=>39,
    "abbr"=>"MAL",
    "name"=>"Malachi",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>14},
      {"number"=>2, "verse_count"=>17},
      {"number"=>3, "verse_count"=>18},
      {"number"=>4, "verse_count"=>6}]},
  {"number"=>40,
    "abbr"=>"MAT",
    "name"=>"Matthew",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>25},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>17},
      {"number"=>4, "verse_count"=>25},
      {"number"=>5, "verse_count"=>48},
      {"number"=>6, "verse_count"=>34},
      {"number"=>7, "verse_count"=>29},
      {"number"=>8, "verse_count"=>34},
      {"number"=>9, "verse_count"=>38},
      {"number"=>10, "verse_count"=>42},
      {"number"=>11, "verse_count"=>30},
      {"number"=>12, "verse_count"=>49},
      {"number"=>13, "verse_count"=>58},
      {"number"=>14, "verse_count"=>36},
      {"number"=>15, "verse_count"=>39},
      {"number"=>16, "verse_count"=>28},
      {"number"=>17, "verse_count"=>26},
      {"number"=>18, "verse_count"=>34},
      {"number"=>19, "verse_count"=>30},
      {"number"=>20, "verse_count"=>34},
      {"number"=>21, "verse_count"=>46},
      {"number"=>22, "verse_count"=>46},
      {"number"=>23, "verse_count"=>38},
      {"number"=>24, "verse_count"=>51},
      {"number"=>25, "verse_count"=>46},
      {"number"=>26, "verse_count"=>75},
      {"number"=>27, "verse_count"=>66},
      {"number"=>28, "verse_count"=>20}]},
  {"number"=>41,
    "abbr"=>"MAR",
    "name"=>"Mark",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>45},
      {"number"=>2, "verse_count"=>28},
      {"number"=>3, "verse_count"=>35},
      {"number"=>4, "verse_count"=>41},
      {"number"=>5, "verse_count"=>43},
      {"number"=>6, "verse_count"=>56},
      {"number"=>7, "verse_count"=>36},
      {"number"=>8, "verse_count"=>38},
      {"number"=>9, "verse_count"=>48},
      {"number"=>10, "verse_count"=>52},
      {"number"=>11, "verse_count"=>32},
      {"number"=>12, "verse_count"=>44},
      {"number"=>13, "verse_count"=>37},
      {"number"=>14, "verse_count"=>72},
      {"number"=>15, "verse_count"=>46},
      {"number"=>16, "verse_count"=>20}]},
  {"number"=>42,
    "abbr"=>"LUK",
    "name"=>"Luke",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>80},
      {"number"=>2, "verse_count"=>52},
      {"number"=>3, "verse_count"=>38},
      {"number"=>4, "verse_count"=>44},
      {"number"=>5, "verse_count"=>39},
      {"number"=>6, "verse_count"=>49},
      {"number"=>7, "verse_count"=>50},
      {"number"=>8, "verse_count"=>56},
      {"number"=>9, "verse_count"=>62},
      {"number"=>10, "verse_count"=>42},
      {"number"=>11, "verse_count"=>54},
      {"number"=>12, "verse_count"=>59},
      {"number"=>13, "verse_count"=>35},
      {"number"=>14, "verse_count"=>35},
      {"number"=>15, "verse_count"=>32},
      {"number"=>16, "verse_count"=>31},
      {"number"=>17, "verse_count"=>36},
      {"number"=>18, "verse_count"=>43},
      {"number"=>19, "verse_count"=>48},
      {"number"=>20, "verse_count"=>47},
      {"number"=>21, "verse_count"=>38},
      {"number"=>22, "verse_count"=>71},
      {"number"=>23, "verse_count"=>55},
      {"number"=>24, "verse_count"=>53}]},
  {"number"=>43,
    "abbr"=>"JOH",
    "name"=>"John",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>51},
      {"number"=>2, "verse_count"=>25},
      {"number"=>3, "verse_count"=>36},
      {"number"=>4, "verse_count"=>54},
      {"number"=>5, "verse_count"=>46},
      {"number"=>6, "verse_count"=>71},
      {"number"=>7, "verse_count"=>53},
      {"number"=>8, "verse_count"=>59},
      {"number"=>9, "verse_count"=>41},
      {"number"=>10, "verse_count"=>42},
      {"number"=>11, "verse_count"=>57},
      {"number"=>12, "verse_count"=>50},
      {"number"=>13, "verse_count"=>38},
      {"number"=>14, "verse_count"=>31},
      {"number"=>15, "verse_count"=>27},
      {"number"=>16, "verse_count"=>33},
      {"number"=>17, "verse_count"=>26},
      {"number"=>18, "verse_count"=>40},
      {"number"=>19, "verse_count"=>42},
      {"number"=>20, "verse_count"=>31},
      {"number"=>21, "verse_count"=>25}]},
  {"number"=>44,
    "abbr"=>"ACT",
    "name"=>"Acts",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>26},
      {"number"=>2, "verse_count"=>47},
      {"number"=>3, "verse_count"=>26},
      {"number"=>4, "verse_count"=>37},
      {"number"=>5, "verse_count"=>42},
      {"number"=>6, "verse_count"=>15},
      {"number"=>7, "verse_count"=>60},
      {"number"=>8, "verse_count"=>39},
      {"number"=>9, "verse_count"=>43},
      {"number"=>10, "verse_count"=>48},
      {"number"=>11, "verse_count"=>30},
      {"number"=>12, "verse_count"=>25},
      {"number"=>13, "verse_count"=>52},
      {"number"=>14, "verse_count"=>28},
      {"number"=>15, "verse_count"=>40},
      {"number"=>16, "verse_count"=>40},
      {"number"=>17, "verse_count"=>34},
      {"number"=>18, "verse_count"=>28},
      {"number"=>19, "verse_count"=>41},
      {"number"=>20, "verse_count"=>38},
      {"number"=>21, "verse_count"=>40},
      {"number"=>22, "verse_count"=>30},
      {"number"=>23, "verse_count"=>35},
      {"number"=>24, "verse_count"=>26},
      {"number"=>25, "verse_count"=>27},
      {"number"=>26, "verse_count"=>32},
      {"number"=>27, "verse_count"=>44},
      {"number"=>28, "verse_count"=>30}]},
  {"number"=>45,
    "abbr"=>"ROM",
    "name"=>"Romans",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>32},
      {"number"=>2, "verse_count"=>29},
      {"number"=>3, "verse_count"=>31},
      {"number"=>4, "verse_count"=>25},
      {"number"=>5, "verse_count"=>21},
      {"number"=>6, "verse_count"=>23},
      {"number"=>7, "verse_count"=>25},
      {"number"=>8, "verse_count"=>39},
      {"number"=>9, "verse_count"=>33},
      {"number"=>10, "verse_count"=>21},
      {"number"=>11, "verse_count"=>36},
      {"number"=>12, "verse_count"=>21},
      {"number"=>13, "verse_count"=>14},
      {"number"=>14, "verse_count"=>23},
      {"number"=>15, "verse_count"=>33},
      {"number"=>16, "verse_count"=>26}]},
  {"number"=>46,
    "abbr"=>"1CO",
    "name"=>"1 Corinthians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>31},
      {"number"=>2, "verse_count"=>16},
      {"number"=>3, "verse_count"=>23},
      {"number"=>4, "verse_count"=>21},
      {"number"=>5, "verse_count"=>13},
      {"number"=>6, "verse_count"=>20},
      {"number"=>7, "verse_count"=>40},
      {"number"=>8, "verse_count"=>13},
      {"number"=>9, "verse_count"=>27},
      {"number"=>10, "verse_count"=>33},
      {"number"=>11, "verse_count"=>34},
      {"number"=>12, "verse_count"=>31},
      {"number"=>13, "verse_count"=>13},
      {"number"=>14, "verse_count"=>40},
      {"number"=>15, "verse_count"=>58},
      {"number"=>16, "verse_count"=>24}]},
  {"number"=>47,
    "abbr"=>"2CO",
    "name"=>"2 Corinthians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>24},
      {"number"=>2, "verse_count"=>17},
      {"number"=>3, "verse_count"=>18},
      {"number"=>4, "verse_count"=>18},
      {"number"=>5, "verse_count"=>21},
      {"number"=>6, "verse_count"=>18},
      {"number"=>7, "verse_count"=>16},
      {"number"=>8, "verse_count"=>24},
      {"number"=>9, "verse_count"=>15},
      {"number"=>10, "verse_count"=>18},
      {"number"=>11, "verse_count"=>33},
      {"number"=>12, "verse_count"=>21},
      {"number"=>13, "verse_count"=>14}]},
  {"number"=>48,
    "abbr"=>"GAL",
    "name"=>"Galatians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>24},
      {"number"=>2, "verse_count"=>21},
      {"number"=>3, "verse_count"=>29},
      {"number"=>4, "verse_count"=>31},
      {"number"=>5, "verse_count"=>26},
      {"number"=>6, "verse_count"=>18}]},
  {"number"=>49,
    "abbr"=>"EPH",
    "name"=>"Ephesians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>23},
      {"number"=>2, "verse_count"=>22},
      {"number"=>3, "verse_count"=>21},
      {"number"=>4, "verse_count"=>32},
      {"number"=>5, "verse_count"=>33},
      {"number"=>6, "verse_count"=>24}]},
  {"number"=>50,
    "abbr"=>"PHI",
    "name"=>"Philippians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>30},
      {"number"=>2, "verse_count"=>30},
      {"number"=>3, "verse_count"=>21},
      {"number"=>4, "verse_count"=>23}]},
  {"number"=>51,
    "abbr"=>"COL",
    "name"=>"Colossians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>29},
      {"number"=>2, "verse_count"=>23},
      {"number"=>3, "verse_count"=>25},
      {"number"=>4, "verse_count"=>18}]},
  {"number"=>52,
    "abbr"=>"1TH",
    "name"=>"1 Thessalonians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>10},
      {"number"=>2, "verse_count"=>20},
      {"number"=>3, "verse_count"=>13},
      {"number"=>4, "verse_count"=>18},
      {"number"=>5, "verse_count"=>28}]},
  {"number"=>53,
    "abbr"=>"2TH",
    "name"=>"2 Thessalonians",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>12},
      {"number"=>2, "verse_count"=>17},
      {"number"=>3, "verse_count"=>18}]},
  {"number"=>54,
    "abbr"=>"1TI",
    "name"=>"1 Timothy",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>20},
      {"number"=>2, "verse_count"=>15},
      {"number"=>3, "verse_count"=>16},
      {"number"=>4, "verse_count"=>16},
      {"number"=>5, "verse_count"=>25},
      {"number"=>6, "verse_count"=>21}]},
  {"number"=>55,
    "abbr"=>"2TI",
    "name"=>"2 Timothy",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>18},
      {"number"=>2, "verse_count"=>26},
      {"number"=>3, "verse_count"=>17},
      {"number"=>4, "verse_count"=>22}]},
  {"number"=>56,
    "abbr"=>"TIT",
    "name"=>"Titus",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>16},
      {"number"=>2, "verse_count"=>15},
      {"number"=>3, "verse_count"=>15}]},
  {"number"=>57,
    "abbr"=>"PHM",
    "name"=>"Philemon",
    "chapters"=>[{"number"=>1, "verse_count"=>25}]},
  {"number"=>58,
    "abbr"=>"HEB",
    "name"=>"Hebrews",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>14},
      {"number"=>2, "verse_count"=>18},
      {"number"=>3, "verse_count"=>19},
      {"number"=>4, "verse_count"=>16},
      {"number"=>5, "verse_count"=>14},
      {"number"=>6, "verse_count"=>20},
      {"number"=>7, "verse_count"=>28},
      {"number"=>8, "verse_count"=>13},
      {"number"=>9, "verse_count"=>28},
      {"number"=>10, "verse_count"=>39},
      {"number"=>11, "verse_count"=>40},
      {"number"=>12, "verse_count"=>29},
      {"number"=>13, "verse_count"=>25}]},
  {"number"=>59,
    "abbr"=>"JAM",
    "name"=>"James",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>27},
      {"number"=>2, "verse_count"=>26},
      {"number"=>3, "verse_count"=>18},
      {"number"=>4, "verse_count"=>17},
      {"number"=>5, "verse_count"=>20}]},
  {"number"=>60,
    "abbr"=>"1PE",
    "name"=>"1 Peter",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>25},
      {"number"=>2, "verse_count"=>25},
      {"number"=>3, "verse_count"=>22},
      {"number"=>4, "verse_count"=>19},
      {"number"=>5, "verse_count"=>14}]},
  {"number"=>61,
    "abbr"=>"2PE",
    "name"=>"2 Peter",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>21},
      {"number"=>2, "verse_count"=>22},
      {"number"=>3, "verse_count"=>18}]},
  {"number"=>62,
    "abbr"=>"1JO",
    "name"=>"1 John",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>10},
      {"number"=>2, "verse_count"=>29},
      {"number"=>3, "verse_count"=>24},
      {"number"=>4, "verse_count"=>21},
      {"number"=>5, "verse_count"=>21}]},
  {"number"=>63,
    "abbr"=>"2JO",
    "name"=>"2 John",
    "chapters"=>[{"number"=>1, "verse_count"=>13}]},
  {"number"=>64,
    "abbr"=>"3JO",
    "name"=>"3 John",
    "chapters"=>[{"number"=>1, "verse_count"=>15}]},
  {"number"=>65,
    "abbr"=>"JUD",
    "name"=>"Jude",
    "chapters"=>[{"number"=>1, "verse_count"=>25}]},
  {"number"=>66,
    "abbr"=>"REV",
    "name"=>"Revelation",
    "chapters"=>
    [ {"number"=>1, "verse_count"=>20},
      {"number"=>2, "verse_count"=>29},
      {"number"=>3, "verse_count"=>22},
      {"number"=>4, "verse_count"=>11},
      {"number"=>5, "verse_count"=>14},
      {"number"=>6, "verse_count"=>17},
      {"number"=>7, "verse_count"=>17},
      {"number"=>8, "verse_count"=>13},
      {"number"=>9, "verse_count"=>21},
      {"number"=>10, "verse_count"=>11},
      {"number"=>11, "verse_count"=>19},
      {"number"=>12, "verse_count"=>17},
      {"number"=>13, "verse_count"=>18},
      {"number"=>14, "verse_count"=>20},
      {"number"=>15, "verse_count"=>8},
      {"number"=>16, "verse_count"=>21},
      {"number"=>17, "verse_count"=>18},
      {"number"=>18, "verse_count"=>24},
      {"number"=>19, "verse_count"=>21},
      {"number"=>20, "verse_count"=>15},
      {"number"=>21, "verse_count"=>27},
      {"number"=>22, "verse_count"=>21}]}]
end
